// Generated from D:/Dowload/chat_intent_100_positive_examples_per_intent.json.
// These are additional positive examples; merge/dedupe happens in chat_intent_examples.data.ts.
import type { ChatIntent } from "../types/chat.types";

export const CHAT_INTENT_EXTRA_POSITIVE_EXAMPLES: Partial<Record<ChatIntent, readonly string[]>> = {
  "app.navigation_support": [
    "mo trang chu",
    "ve trang chu",
    "quay lai trang chu",
    "mo menu chinh",
    "menu o dau",
    "mo phan luyen de",
    "vao dau de luyen de",
    "tim muc luyen de o dau",
    "lam de moi o dau",
    "bat dau lam de o dau",
    "mo danh sach de thi",
    "xem cac de thi o dau",
    "vao kho de thi",
    "mo trang test",
    "mo trang thi thu",
    "mo ket qua lam bai",
    "xem ket qua o dau",
    "mo lich su lam bai",
    "vao lich su de thi",
    "xem de da lam o dau",
    "mo bai vua lam",
    "mo de gan nhat",
    "xem lai de vua nop",
    "vao man hinh review",
    "mo trang review cau sai",
    "xem cau sai o dau",
    "mo danh sach cau sai",
    "vao muc cau sai",
    "tim cau sai cua toi",
    "mo cau hoi da luu",
    "mo flashcard",
    "vao flashcard o dau",
    "hoc flashcard o dau",
    "mo bo flashcard",
    "tim deck flashcard",
    "mo tu vung",
    "vao muc tu vung",
    "hoc tu vung o dau",
    "xem danh sach tu vung",
    "tim kho tu vung",
    "mo roadmap",
    "vao lo trinh o dau",
    "tim lo trinh hoc",
    "xem lo trinh cua toi",
    "mo ke hoach hoc",
    "mo tien do",
    "xem tien do o dau",
    "vao trang thong ke",
    "mo thong ke hoc tap",
    "xem nang luc o dau",
    "mo profile",
    "vao ho so",
    "sua thong tin ca nhan o dau",
    "mo cai dat tai khoan",
    "vao cai dat",
    "doi mat khau o dau",
    "dang xuat o dau",
    "mo thong bao",
    "xem notification o dau",
    "nut hoc ngay o dau",
    "vao roadmap",
    "tim roadmap",
    "xem roadmap",
    "di toi roadmap",
    "vao flashcard",
    "tim flashcard",
    "xem flashcard",
    "di toi flashcard",
    "mo ket qua",
    "vao ket qua",
    "tim ket qua",
    "xem ket qua",
    "di toi ket qua",
    "mo cau sai",
    "vao cau sai",
    "tim cau sai",
    "xem cau sai",
    "di toi cau sai",
    "mo de thi",
    "vao de thi",
    "tim de thi",
    "xem de thi",
    "di toi de thi",
    "vao tu vung",
    "tim tu vung",
    "xem tu vung",
    "di toi tu vung",
    "mo thong ke",
    "vao thong ke",
    "tim thong ke",
    "xem thong ke",
    "di toi thong ke",
    "mo ho so",
    "tim ho so",
    "xem ho so",
    "di toi ho so",
    "mo cai dat",
    "tim cai dat",
    "xem cai dat",
    "di toi cai dat"
  ],
  "user_profile.identity": [
    "cho toi xem ho so ca nhan",
    "cho minh xem ho so ca nhan",
    "xem thong tin ca nhan cua toi",
    "xem thong tin ca nhan cua minh",
    "thong tin ho so cua toi la gi",
    "thong tin ho so cua minh la gi",
    "ho so tai khoan cua toi",
    "ho so tai khoan cua minh",
    "profile tai khoan cua toi",
    "profile tai khoan cua minh",
    "account profile cua toi",
    "account profile cua minh",
    "toi dang dang nhap bang email nao",
    "minh dang dang nhap bang email nao",
    "email tai khoan cua toi la gi",
    "email tai khoan cua minh la gi",
    "email nao dang gan voi tai khoan nay",
    "email nao dang gan voi account nay",
    "tai khoan hien tai cua toi la gi",
    "tai khoan hien tai cua minh la gi",
    "account hien tai cua toi la gi",
    "account hien tai cua minh la gi",
    "username cua toi la gi",
    "username cua minh la gi",
    "ten username cua toi la gi",
    "ten username cua minh la gi",
    "ten hien thi trong app cua toi la gi",
    "ten hien thi trong app cua minh la gi",
    "ten tren ho so cua toi la gi",
    "ten tren ho so cua minh la gi",
    "ten tai khoan cua toi la gi",
    "ten tai khoan cua minh la gi",
    "ten dang nhap cua toi la gi",
    "ten dang nhap cua minh la gi",
    "toi dang la user nao",
    "minh dang la user nao",
    "toi dang o tai khoan nao",
    "minh dang o tai khoan nao",
    "toi dang dung account nao vay",
    "minh dang dung account nao vay",
    "toi dang dung user nao trong he thong",
    "minh dang dung user nao trong he thong",
    "he thong dang nhan toi la ai",
    "he thong dang nhan minh la ai",
    "he thong biet thong tin gi ve toi",
    "he thong biet thong tin gi ve minh",
    "ban dang thay thong tin nao cua toi",
    "ban dang thay thong tin nao cua minh",
    "ban co thong tin ca nhan nao cua toi",
    "ban co thong tin ca nhan nao cua minh",
    "thong tin cua toi tren app la gi",
    "thong tin cua minh tren app la gi",
    "thong tin cua toi tren web la gi",
    "thong tin cua minh tren web la gi",
    "tom tat ho so cua toi",
    "tom tat ho so cua minh",
    "tom tat tai khoan cua toi",
    "tom tat tai khoan cua minh",
    "gioi thieu ho so cua toi",
    "gioi thieu ho so cua minh",
    "tai khoan nay dang la cua ai",
    "account nay dang la cua ai",
    "nguoi dung hien tai la ai",
    "user hien tai la ai",
    "nguoi dung dang dang nhap la ai",
    "user dang dang nhap la ai",
    "cho toi biet ten va email cua toi",
    "cho minh biet ten va email cua minh",
    "ten va email tai khoan cua toi",
    "ten va email tai khoan cua minh",
    "kiem tra thong tin account cua toi",
    "kiem tra thong tin account cua minh",
    "kiem tra profile cua toi",
    "kiem tra profile cua minh",
    "kiem tra ho so cua toi",
    "kiem tra ho so cua minh",
    "tai khoan cua toi co thong tin gi",
    "tai khoan cua minh co thong tin gi",
    "profile cua toi gom nhung gi",
    "profile cua minh gom nhung gi",
    "ho so cua toi gom nhung gi",
    "ho so cua minh gom nhung gi",
    "toi da tham gia he thong tu khi nao",
    "minh da tham gia he thong tu khi nao",
    "ngay tao tai khoan cua toi la khi nao",
    "ngay tao tai khoan cua minh la khi nao",
    "tai khoan cua toi dang hoat dong khong",
    "tai khoan cua minh dang hoat dong khong",
    "trang thai tai khoan cua toi la gi",
    "trang thai tai khoan cua minh la gi",
    "trang thai account cua toi la gi",
    "trang thai account cua minh la gi",
    "toi co streak bao nhieu ngay trong ho so",
    "minh co streak bao nhieu ngay trong ho so",
    "ho so hoc tap rut gon cua toi",
    "ho so hoc tap rut gon cua minh",
    "thong tin dinh danh cua toi",
    "thong tin dinh danh cua minh",
    "ban dang goi toi theo ten nao",
    "ban dang goi minh theo ten nao",
    "toi la ai trong app nay",
    "minh la ai trong app nay"
  ],
  "flashcard.create": [
    "tao flashcard",
    "tao the tu vung",
    "tao bo flashcard",
    "tao deck flashcard",
    "lap bo the cho toi",
    "luu vao flashcard",
    "luu tu nay vao flashcard",
    "luu cau nay vao flashcard",
    "cho vao flashcard",
    "them vao flashcard",
    "tao 10 tu chu de cau nay",
    "tao 10 tu vung lien quan cau nay",
    "sinh 10 tu tu cau nay",
    "lay 10 tu de hoc",
    "tao deck tu cau nay",
    "tao bo tu vung tu cau nay",
    "luu 10 tu cua cau nay",
    "sinh bo tu vung tu cau nay",
    "tao flashcard tu cau nay",
    "tao flashcard cho bai nay",
    "tao the cho cac tu kho",
    "lay tu kho tao flashcard",
    "bien thanh flashcard",
    "chuyen thanh flashcard",
    "chuyen cau nay thanh the hoc",
    "tao flashcard giup toi",
    "lam flashcard giup toi",
    "tao the on tap",
    "luu lai de hoc sau",
    "hoc lai tu nay sau",
    "luu lai",
    "luu giup",
    "luu lai nhe",
    "them vao bo hoc",
    "them vao deck",
    "tao 5 flashcard tu cau nay",
    "tao 5 tu vung tu cau nay",
    "luu 5 tu tu cau nay",
    "sinh 5 the tu cau nay",
    "tao 5 flashcard tu doan nay",
    "tao 5 tu vung tu doan nay",
    "luu 5 tu tu doan nay",
    "sinh 5 the tu doan nay",
    "tao 5 flashcard tu bai nay",
    "tao 5 tu vung tu bai nay",
    "luu 5 tu tu bai nay",
    "sinh 5 the tu bai nay",
    "tao 5 flashcard tu phan nay",
    "tao 5 tu vung tu phan nay",
    "luu 5 tu tu phan nay",
    "sinh 5 the tu phan nay",
    "tao 5 flashcard tu cau hoi hien tai",
    "tao 5 tu vung tu cau hoi hien tai",
    "luu 5 tu tu cau hoi hien tai",
    "sinh 5 the tu cau hoi hien tai",
    "tao 8 flashcard tu cau nay",
    "tao 8 tu vung tu cau nay",
    "luu 8 tu tu cau nay",
    "sinh 8 the tu cau nay",
    "tao 8 flashcard tu doan nay",
    "tao 8 tu vung tu doan nay",
    "luu 8 tu tu doan nay",
    "sinh 8 the tu doan nay",
    "tao 8 flashcard tu bai nay",
    "tao 8 tu vung tu bai nay",
    "luu 8 tu tu bai nay",
    "sinh 8 the tu bai nay",
    "tao 8 flashcard tu phan nay",
    "tao 8 tu vung tu phan nay",
    "luu 8 tu tu phan nay",
    "sinh 8 the tu phan nay",
    "tao 8 flashcard tu cau hoi hien tai",
    "tao 8 tu vung tu cau hoi hien tai",
    "luu 8 tu tu cau hoi hien tai",
    "sinh 8 the tu cau hoi hien tai",
    "tao 10 flashcard tu cau nay",
    "tao 10 tu vung tu cau nay",
    "luu 10 tu tu cau nay",
    "sinh 10 the tu cau nay",
    "tao 10 flashcard tu doan nay",
    "tao 10 tu vung tu doan nay",
    "luu 10 tu tu doan nay",
    "sinh 10 the tu doan nay",
    "tao 10 flashcard tu bai nay",
    "tao 10 tu vung tu bai nay",
    "luu 10 tu tu bai nay",
    "sinh 10 the tu bai nay",
    "tao 10 flashcard tu phan nay",
    "tao 10 tu vung tu phan nay",
    "luu 10 tu tu phan nay",
    "sinh 10 the tu phan nay",
    "tao 10 flashcard tu cau hoi hien tai",
    "tao 10 tu vung tu cau hoi hien tai",
    "luu 10 tu tu cau hoi hien tai",
    "sinh 10 the tu cau hoi hien tai",
    "tao 12 flashcard tu cau nay",
    "tao 12 tu vung tu cau nay",
    "luu 12 tu tu cau nay",
    "sinh 12 the tu cau nay",
    "tao 12 flashcard tu doan nay"
  ],
  "flashcard.personal": [
    "flashcard cua toi the nao",
    "hom nay co flashcard nao can on khong",
    "toi can on flashcard nao",
    "flashcard den han chua",
    "tu nao den han on lai",
    "xem flashcard cua toi",
    "bo flashcard cua toi dau",
    "toi co bao nhieu flashcard",
    "deck cua toi co gi",
    "nhung tu toi da luu la gi",
    "tu nao toi hay quen",
    "toi hay sai tu nao",
    "tu nao dang learning",
    "tu nao dang reviewing",
    "tu nao da mastered",
    "kiem tra trang thai flashcard",
    "tien do flashcard cua toi",
    "flashcard hom nay nen hoc gi",
    "toi nen hoc deck nao",
    "goi y flashcard cho toi",
    "xem cac tu can on",
    "lich on flashcard cua toi",
    "hom nay toi phai on may tu",
    "bao nhieu tu qua han",
    "tu nao sap den han",
    "tu nao p recall thap",
    "tu nao kho voi toi",
    "tu nao half life thap",
    "tu nao nen uu tien",
    "cac tu yeu cua toi",
    "flashcard cua toi co gi",
    "flashcard hom nay nen hoc cai nao",
    "flashcard dang den han khong",
    "flashcard can on lai khong",
    "deck cua toi the nao",
    "deck hom nay nen hoc cai nao",
    "deck dang den han khong",
    "deck can on lai khong",
    "tu vung da luu cua toi co gi",
    "tu vung da luu cua toi the nao",
    "tu vung da luu hom nay nen hoc cai nao",
    "tu vung da luu dang den han khong",
    "tu vung da luu can on lai khong",
    "the da tao cua toi co gi",
    "the da tao cua toi the nao",
    "the da tao hom nay nen hoc cai nao",
    "the da tao dang den han khong",
    "the da tao can on lai khong",
    "bo tu vung cua toi co gi",
    "bo tu vung cua toi the nao",
    "bo tu vung hom nay nen hoc cai nao",
    "bo tu vung dang den han khong",
    "bo tu vung can on lai khong",
    "xem tu learning",
    "co tu nao learning khong",
    "danh sach flashcard learning",
    "bao nhieu flashcard learning",
    "xem tu reviewing",
    "co tu nao reviewing khong",
    "danh sach flashcard reviewing",
    "bao nhieu flashcard reviewing",
    "xem tu mastered",
    "co tu nao mastered khong",
    "danh sach flashcard mastered",
    "bao nhieu flashcard mastered",
    "xem tu dang hoc",
    "co tu nao dang hoc khong",
    "danh sach flashcard dang hoc",
    "bao nhieu flashcard dang hoc",
    "xem tu dang on lai",
    "co tu nao dang on lai khong",
    "danh sach flashcard dang on lai",
    "bao nhieu flashcard dang on lai",
    "xem tu da thanh thao",
    "co tu nao da thanh thao khong",
    "danh sach flashcard da thanh thao",
    "bao nhieu flashcard da thanh thao",
    "xem tu qua han",
    "co tu nao qua han khong",
    "danh sach flashcard qua han",
    "bao nhieu flashcard qua han",
    "xem tu sap den han",
    "co tu nao sap den han khong",
    "danh sach flashcard sap den han",
    "bao nhieu flashcard sap den han",
    "toi nho duoc bao nhieu tu",
    "do nho flashcard cua toi",
    "thong ke nho tu cua toi",
    "muc do ghi nho cua toi",
    "cac tu nen on truoc",
    "flashcard cua toi the nao giup toi",
    "flashcard cua toi the nao nhe",
    "flashcard cua toi the nao duoc khong",
    "flashcard cua toi the nao cho toi",
    "flashcard cua toi the nao mot chut",
    "flashcard cua toi the nao nhanh giup",
    "flashcard cua toi the nao di",
    "flashcard cua toi the nao voi",
    "hom nay co flashcard nao can on khong giup toi",
    "hom nay co flashcard nao can on khong nhe"
  ],
  "grammar.contextual": [
    "ngu phap cau nay la gi",
    "giai thich ngu phap cau nay",
    "cau nay dung ngu phap nao",
    "diem ngu phap o dau",
    "phan ngu phap nay la gi",
    "tai sao dung thi nay",
    "vi sao la thi hien tai hoan thanh",
    "vi sao dung qua khu",
    "vi sao dung bi dong",
    "tai sao dung to v",
    "tai sao dung v ing",
    "tai sao them ed",
    "tai sao them s",
    "tai sao dung danh tu",
    "tai sao dung tinh tu",
    "tai sao dung trang tu",
    "tai sao dung gioi tu nay",
    "gioi tu nay co nghia gi",
    "cau nay cau truc gi",
    "cau truc nay la sao",
    "phan relative clause o dau",
    "menh de quan he o dau",
    "rut gon menh de nhu the nao",
    "day la loai tu gi",
    "chon loai tu nao",
    "can danh tu hay dong tu",
    "sau cho trong can gi",
    "truoc cho trong can gi",
    "dau hieu ngu phap la gi",
    "meo ngu phap cau nay",
    "giai thich cau truc",
    "phan tich cau truc cau nay",
    "subject verb object o dau",
    "chu ngu la gi",
    "dong tu chinh la gi",
    "sao lai dung because",
    "sao lai dung although",
    "sao lai dung despite",
    "sao lai dung however",
    "sao lai dung which",
    "giai thich thi hien tai don",
    "thi hien tai don trong cau nay",
    "vi sao cau nay dung thi hien tai don",
    "dau hieu cua thi hien tai don la gi",
    "giai thich thi qua khu don",
    "thi qua khu don trong cau nay",
    "vi sao cau nay dung thi qua khu don",
    "dau hieu cua thi qua khu don la gi",
    "giai thich thi tuong lai",
    "thi tuong lai trong cau nay",
    "vi sao cau nay dung thi tuong lai",
    "dau hieu cua thi tuong lai la gi",
    "giai thich hien tai hoan thanh",
    "hien tai hoan thanh trong cau nay",
    "vi sao cau nay dung hien tai hoan thanh",
    "dau hieu cua hien tai hoan thanh la gi",
    "giai thich bi dong",
    "bi dong trong cau nay",
    "vi sao cau nay dung bi dong",
    "dau hieu cua bi dong la gi",
    "giai thich cau dieu kien",
    "cau dieu kien trong cau nay",
    "vi sao cau nay dung cau dieu kien",
    "dau hieu cua cau dieu kien la gi",
    "giai thich menh de quan he",
    "menh de quan he trong cau nay",
    "vi sao cau nay dung menh de quan he",
    "dau hieu cua menh de quan he la gi",
    "giai thich rut gon menh de",
    "rut gon menh de trong cau nay",
    "vi sao cau nay dung rut gon menh de",
    "dau hieu cua rut gon menh de la gi",
    "giai thich so sanh hon",
    "so sanh hon trong cau nay",
    "vi sao cau nay dung so sanh hon",
    "dau hieu cua so sanh hon la gi",
    "giai thich so sanh nhat",
    "so sanh nhat trong cau nay",
    "vi sao cau nay dung so sanh nhat",
    "dau hieu cua so sanh nhat la gi",
    "giai thich danh dong tu",
    "danh dong tu trong cau nay",
    "vi sao cau nay dung danh dong tu",
    "dau hieu cua danh dong tu la gi",
    "giai thich dong tu nguyen mau",
    "dong tu nguyen mau trong cau nay",
    "vi sao cau nay dung dong tu nguyen mau",
    "dau hieu cua dong tu nguyen mau la gi",
    "giai thich gioi tu",
    "gioi tu trong cau nay",
    "vi sao cau nay dung gioi tu",
    "dau hieu cua gioi tu la gi",
    "giai thich lien tu",
    "lien tu trong cau nay",
    "vi sao cau nay dung lien tu",
    "dau hieu cua lien tu la gi",
    "giai thich dai tu quan he",
    "dai tu quan he trong cau nay",
    "vi sao cau nay dung dai tu quan he",
    "dau hieu cua dai tu quan he la gi"
  ],
  "out_of_project.general": [
    "thoi tiet hom nay the nao",
    "hom nay co mua khong",
    "nhiet do hom nay bao nhieu",
    "gia vang hom nay",
    "bitcoin gia bao nhieu",
    "co phieu nao nen mua",
    "du doan chung khoan",
    "tin chinh tri moi nhat",
    "lich bong da toi nay",
    "ket qua bong da hom qua",
    "nau pho nhu the nao",
    "cong thuc nau an don gian",
    "lam banh mi sao",
    "goi y mon an toi nay",
    "dat ve may bay di da nang",
    "khach san nao tot o da lat",
    "lich chieu phim hom nay",
    "phim nao dang hot",
    "ke chuyen ma di",
    "viet tho tinh cho toi",
    "viet code python cho toi",
    "sua bug react giup toi",
    "tao app ban hang bang nextjs",
    "tu van mua laptop",
    "dien thoai nao tot",
    "toi bi sot uong thuoc gi",
    "dau dau nen uong gi",
    "tap gym the nao",
    "giam can sao cho nhanh",
    "tu van skincare",
    "dich tieng nhat cau nay",
    "hoc tieng han o dau",
    "viet cv xin viec",
    "soan email xin nghi phep",
    "dat ban nha hang",
    "thoi tiet moi nhat la gi",
    "thoi tiet tu van giup toi",
    "thoi tiet co gi hay khong",
    "vang hom nay the nao",
    "vang moi nhat la gi",
    "vang tu van giup toi",
    "vang co gi hay khong",
    "bitcoin hom nay the nao",
    "bitcoin moi nhat la gi",
    "bitcoin tu van giup toi",
    "bitcoin co gi hay khong",
    "chung khoan hom nay the nao",
    "chung khoan moi nhat la gi",
    "chung khoan tu van giup toi",
    "chung khoan co gi hay khong",
    "bong da hom nay the nao",
    "bong da moi nhat la gi",
    "bong da tu van giup toi",
    "bong da co gi hay khong",
    "nau an hom nay the nao",
    "nau an moi nhat la gi",
    "nau an tu van giup toi",
    "nau an co gi hay khong",
    "du lich hom nay the nao",
    "du lich moi nhat la gi",
    "du lich tu van giup toi",
    "du lich co gi hay khong",
    "phim hom nay the nao",
    "phim moi nhat la gi",
    "phim tu van giup toi",
    "phim co gi hay khong",
    "suc khoe hom nay the nao",
    "suc khoe moi nhat la gi",
    "suc khoe tu van giup toi",
    "suc khoe co gi hay khong",
    "lap trinh hom nay the nao",
    "lap trinh moi nhat la gi",
    "lap trinh tu van giup toi",
    "lap trinh co gi hay khong",
    "mua sam hom nay the nao",
    "mua sam moi nhat la gi",
    "mua sam tu van giup toi",
    "mua sam co gi hay khong",
    "tin tuc hom nay the nao",
    "tin tuc moi nhat la gi",
    "tin tuc tu van giup toi",
    "tin tuc co gi hay khong",
    "game hom nay the nao",
    "game moi nhat la gi",
    "game tu van giup toi",
    "game co gi hay khong",
    "am nhac hom nay the nao",
    "am nhac moi nhat la gi",
    "am nhac tu van giup toi",
    "am nhac co gi hay khong",
    "doi song hom nay the nao",
    "doi song moi nhat la gi",
    "doi song tu van giup toi",
    "doi song co gi hay khong",
    "ban biet xem tarot khong",
    "boi bai giup toi",
    "dat xe di san bay",
    "toi nen mua xe nao",
    "tu van nha dat",
    "chuyen tien quoc te sao"
  ],
  "question.explain_specific": [
    "giai thich cau nay",
    "giai thich dap an cau nay",
    "cau nay vi sao dung dap an nay",
    "tai sao dap an nay dung",
    "vi sao cau nay sai",
    "sao toi sai cau nay",
    "minh sai o dau",
    "loi sai cua toi la gi",
    "dap an dung la gi",
    "giai thich tung dap an",
    "phan tich cau hoi nay",
    "phan tich dap an",
    "noi ro hon cau nay",
    "cau nay la sao",
    "sao lai chon dap an nay",
    "sao khong chon a",
    "sao khong chon b",
    "sao khong chon c",
    "sao khong chon d",
    "dap an a sai o dau",
    "dap an b sai o dau",
    "dap an c sai o dau",
    "dap an d sai o dau",
    "giai thich vi sao a dung",
    "giai thich vi sao b dung",
    "giai thich vi sao c dung",
    "giai thich vi sao d dung",
    "em chua hieu cau nay",
    "doc cau nay khong hieu",
    "cau nay kho qua",
    "sao vay",
    "sao sai",
    "vi sao sai",
    "tai sao sai",
    "giai dum",
    "giai giup",
    "giai nhanh",
    "noi lai de hieu hon",
    "phan tich cau nay",
    "noi ro cau nay",
    "chi loi sai cau nay",
    "giai chi tiet cau nay",
    "giai ngan gon cau nay",
    "giai thich bai nay",
    "phan tich bai nay",
    "noi ro bai nay",
    "chi loi sai bai nay",
    "giai chi tiet bai nay",
    "giai ngan gon bai nay",
    "giai thich cau hoi nay",
    "noi ro cau hoi nay",
    "chi loi sai cau hoi nay",
    "giai chi tiet cau hoi nay",
    "giai ngan gon cau hoi nay",
    "giai thich dap an nay",
    "phan tich dap an nay",
    "noi ro dap an nay",
    "chi loi sai dap an nay",
    "giai chi tiet dap an nay",
    "giai ngan gon dap an nay",
    "giai thich phan nay",
    "phan tich phan nay",
    "noi ro phan nay",
    "chi loi sai phan nay",
    "giai chi tiet phan nay",
    "giai ngan gon phan nay",
    "giai thich cho nay",
    "phan tich cho nay",
    "noi ro cho nay",
    "chi loi sai cho nay",
    "giai chi tiet cho nay",
    "giai ngan gon cho nay",
    "tai sao khong phai dap an con lai",
    "dap an con lai sai vi sao",
    "co meo nao cho cau nay khong",
    "can nhin dau hieu nao",
    "cach lam cau nay la gi",
    "luan diem chon dap an la gi",
    "giai theo tung buoc",
    "hay chi minh cach lam",
    "cau nay ap dung quy tac gi",
    "cau nay hoi cai gi",
    "giai thich cau nay giup toi",
    "giai thich cau nay nhe",
    "giai thich cau nay duoc khong",
    "giai thich cau nay cho toi",
    "giai thich cau nay mot chut",
    "giai thich cau nay nhanh giup",
    "giai thich cau nay di",
    "giai thich cau nay voi",
    "giai thich dap an cau nay giup toi",
    "giai thich dap an cau nay nhe",
    "giai thich dap an cau nay duoc khong",
    "giai thich dap an cau nay cho toi",
    "giai thich dap an cau nay mot chut",
    "giai thich dap an cau nay nhanh giup",
    "giai thich dap an cau nay di",
    "giai thich dap an cau nay voi",
    "cau nay vi sao dung dap an nay giup toi",
    "cau nay vi sao dung dap an nay nhe"
  ],
  "question.similar_practice": [
    "tao cau tuong tu",
    "cho cau luyen tap tuong tu",
    "tao bai tap giong cau nay",
    "cho minh lam cau giong vay",
    "luyen them dang nay",
    "co cau nao tuong tu khong",
    "ra them cau nhu nay",
    "cho bai tap cung dang",
    "tao cau hoi cung grammar",
    "tao cau hoi cung tu vung",
    "luyen cau nay them",
    "lam them dang nay",
    "cho 5 cau tuong tu",
    "cho 10 cau tuong tu",
    "tao 3 cau luyen tap",
    "tao practice cau nay",
    "generate similar question",
    "more practice like this",
    "tao bai tap part 5 giong cau nay",
    "tao cau part 5 tuong tu",
    "tao 3 cau tuong tu",
    "cho toi 3 cau tuong tu",
    "tao 3 bai tap tuong tu",
    "cho toi 3 bai tap tuong tu",
    "tao 3 cau cung dang",
    "cho toi 3 cau cung dang",
    "cho toi 3 cau luyen tap",
    "tao 3 cau giong cau nay",
    "cho toi 3 cau giong cau nay",
    "tao 3 question similar",
    "cho toi 3 question similar",
    "tao 5 cau tuong tu",
    "cho toi 5 cau tuong tu",
    "tao 5 bai tap tuong tu",
    "cho toi 5 bai tap tuong tu",
    "tao 5 cau cung dang",
    "cho toi 5 cau cung dang",
    "tao 5 cau luyen tap",
    "cho toi 5 cau luyen tap",
    "tao 5 cau giong cau nay",
    "cho toi 5 cau giong cau nay",
    "tao 5 question similar",
    "cho toi 5 question similar",
    "tao 7 cau tuong tu",
    "cho toi 7 cau tuong tu",
    "tao 7 bai tap tuong tu",
    "cho toi 7 bai tap tuong tu",
    "tao 7 cau cung dang",
    "cho toi 7 cau cung dang",
    "tao 7 cau luyen tap",
    "cho toi 7 cau luyen tap",
    "tao 7 cau giong cau nay",
    "cho toi 7 cau giong cau nay",
    "tao 7 question similar",
    "cho toi 7 question similar",
    "tao 10 cau tuong tu",
    "cho toi 10 cau tuong tu",
    "tao 10 bai tap tuong tu",
    "cho toi 10 bai tap tuong tu",
    "tao 10 cau cung dang",
    "cho toi 10 cau cung dang",
    "tao 10 cau luyen tap",
    "cho toi 10 cau luyen tap",
    "tao 10 cau giong cau nay",
    "cho toi 10 cau giong cau nay",
    "tao 10 question similar",
    "cho toi 10 question similar",
    "tao 15 cau tuong tu",
    "cho toi 15 cau tuong tu",
    "tao 15 bai tap tuong tu",
    "cho toi 15 bai tap tuong tu",
    "tao 15 cau cung dang",
    "cho toi 15 cau cung dang",
    "tao 15 cau luyen tap",
    "cho toi 15 cau luyen tap",
    "tao 15 cau giong cau nay",
    "cho toi 15 cau giong cau nay",
    "tao 15 question similar",
    "cho toi 15 question similar",
    "luyen them ngu phap nay",
    "tao cau hoi ve ngu phap nay",
    "cho bai tap ve ngu phap nay",
    "ra them cau ve ngu phap nay",
    "luyen them tu vung nay",
    "tao cau hoi ve tu vung nay",
    "cho bai tap ve tu vung nay",
    "ra them cau ve tu vung nay",
    "luyen them dang cau nay",
    "tao cau hoi ve dang cau nay",
    "cho bai tap ve dang cau nay",
    "ra them cau ve dang cau nay",
    "luyen them loai cau nay",
    "tao cau hoi ve loai cau nay",
    "cho bai tap ve loai cau nay",
    "ra them cau ve loai cau nay",
    "luyen them part nay",
    "tao cau hoi ve part nay",
    "cho bai tap ve part nay",
    "ra them cau ve part nay",
    "luyen them chu de nay"
  ],
  "question.translate_context": [
    "dich cau nay",
    "dich sang tieng viet",
    "dich giup cau nay",
    "dich dum",
    "dich di",
    "dich",
    "nghia cau nay la gi",
    "cau nay nghia la gi",
    "doan nay nghia la gi",
    "noi tieng viet la sao",
    "viet lai bang tieng viet",
    "doc khong hieu dich giup",
    "dich ca cau hoi",
    "dich dap an",
    "dich cac lua chon",
    "dich phan de bai",
    "dich phan giai thich",
    "cau nay noi ve cai gi",
    "noi y chinh bang tieng viet",
    "paraphrase tieng viet",
    "chuyen cau nay sang tieng viet",
    "giai nghia cau nay",
    "hieu cau nay sao",
    "cau nay co nghia gi",
    "y cau nay la gi",
    "noi nghia cau nay",
    "chuyen sang tieng viet cau nay",
    "viet lai tieng viet cau nay",
    "dich bai nay",
    "dich giup bai nay",
    "giai nghia bai nay",
    "noi nghia bai nay",
    "chuyen sang tieng viet bai nay",
    "viet lai tieng viet bai nay",
    "dich doan nay",
    "dich giup doan nay",
    "giai nghia doan nay",
    "noi nghia doan nay",
    "chuyen sang tieng viet doan nay",
    "viet lai tieng viet doan nay",
    "dich de bai nay",
    "dich giup de bai nay",
    "giai nghia de bai nay",
    "noi nghia de bai nay",
    "chuyen sang tieng viet de bai nay",
    "viet lai tieng viet de bai nay",
    "dich dap an nay",
    "dich giup dap an nay",
    "giai nghia dap an nay",
    "noi nghia dap an nay",
    "chuyen sang tieng viet dap an nay",
    "viet lai tieng viet dap an nay",
    "dich lua chon nay",
    "dich giup lua chon nay",
    "giai nghia lua chon nay",
    "noi nghia lua chon nay",
    "chuyen sang tieng viet lua chon nay",
    "viet lai tieng viet lua chon nay",
    "dich phan nay",
    "dich giup phan nay",
    "giai nghia phan nay",
    "noi nghia phan nay",
    "chuyen sang tieng viet phan nay",
    "viet lai tieng viet phan nay",
    "dich cau hoi nay",
    "dich giup cau hoi nay",
    "giai nghia cau hoi nay",
    "noi nghia cau hoi nay",
    "chuyen sang tieng viet cau hoi nay",
    "viet lai tieng viet cau hoi nay",
    "translate this sentence",
    "translate please",
    "what does this mean",
    "meaning of this sentence",
    "i do not understand this sentence",
    "dich sang vi",
    "dich tieng viet di",
    "dich câu này",
    "nghia la gi",
    "la sao",
    "y la sao",
    "hieu sao",
    "doc sao hieu",
    "dich nhanh",
    "dich tung cau",
    "dich tung dap an",
    "dich de bai",
    "dich option",
    "dich cau nay giup toi",
    "dich cau nay nhe",
    "dich cau nay duoc khong",
    "dich cau nay cho toi",
    "dich cau nay mot chut",
    "dich cau nay nhanh giup",
    "dich cau nay di",
    "dich cau nay voi",
    "dich sang tieng viet giup toi",
    "dich sang tieng viet nhe",
    "dich sang tieng viet duoc khong",
    "dich sang tieng viet cho toi"
  ],
  "roadmap.adjust": [
    "dieu chinh lo trinh",
    "doi lo trinh hoc",
    "cap nhat roadmap",
    "sua roadmap cua toi",
    "thay doi ke hoach hoc",
    "toi muon hoc cham hon",
    "toi muon hoc nhanh hon",
    "tang muc tieu diem",
    "giam muc tieu diem",
    "doi muc tieu toeic",
    "doi target score",
    "toi chi hoc duoc 30 phut moi ngay",
    "toi ban qua giam lich hoc",
    "tang so buoi hoc",
    "giam so buoi hoc",
    "doi thoi gian hoc moi ngay",
    "chuyen sang tap trung listening",
    "chuyen sang tap trung reading",
    "uu tien part 5",
    "uu tien part 7",
    "toi sap thi roi hay rut ngan lo trinh",
    "ke hoach nay nang qua",
    "ke hoach nay nhe qua",
    "roadmap kho qua",
    "roadmap de qua",
    "doi muc tieu len 450",
    "cap nhat target 450",
    "lap lai lo trinh muc tieu 450",
    "toi muon dat 450 diem",
    "doi muc tieu len 500",
    "cap nhat target 500",
    "lap lai lo trinh muc tieu 500",
    "toi muon dat 500 diem",
    "doi muc tieu len 550",
    "cap nhat target 550",
    "lap lai lo trinh muc tieu 550",
    "toi muon dat 550 diem",
    "doi muc tieu len 600",
    "cap nhat target 600",
    "lap lai lo trinh muc tieu 600",
    "toi muon dat 600 diem",
    "doi muc tieu len 650",
    "cap nhat target 650",
    "lap lai lo trinh muc tieu 650",
    "toi muon dat 650 diem",
    "doi muc tieu len 700",
    "cap nhat target 700",
    "lap lai lo trinh muc tieu 700",
    "toi muon dat 700 diem",
    "doi muc tieu len 750",
    "cap nhat target 750",
    "lap lai lo trinh muc tieu 750",
    "toi muon dat 750 diem",
    "doi muc tieu len 800",
    "cap nhat target 800",
    "lap lai lo trinh muc tieu 800",
    "toi muon dat 800 diem",
    "doi muc tieu len 850",
    "cap nhat target 850",
    "lap lai lo trinh muc tieu 850",
    "toi muon dat 850 diem",
    "dieu chinh lo trinh trong 1 tuan",
    "toi chi con 1 tuan",
    "cap nhat ke hoach hoc 1 tuan",
    "dieu chinh lo trinh trong 2 tuan",
    "toi chi con 2 tuan",
    "cap nhat ke hoach hoc 2 tuan",
    "dieu chinh lo trinh trong 1 thang",
    "toi chi con 1 thang",
    "cap nhat ke hoach hoc 1 thang",
    "dieu chinh lo trinh trong 2 thang",
    "toi chi con 2 thang",
    "cap nhat ke hoach hoc 2 thang",
    "dieu chinh lo trinh trong 3 thang",
    "toi chi con 3 thang",
    "cap nhat ke hoach hoc 3 thang",
    "dieu chinh lo trinh trong 6 thang",
    "toi chi con 6 thang",
    "cap nhat ke hoach hoc 6 thang",
    "dieu chinh roadmap them part listening",
    "dieu chinh roadmap them part reading",
    "dieu chinh roadmap bot ngu phap",
    "dieu chinh roadmap them tu vung",
    "dieu chinh roadmap giam so bai tap",
    "dieu chinh roadmap tang so de thi",
    "dieu chinh roadmap doi lich on flashcard",
    "dieu chinh roadmap doi ngay hoc",
    "dieu chinh lo trinh giup toi",
    "dieu chinh lo trinh nhe",
    "dieu chinh lo trinh duoc khong",
    "dieu chinh lo trinh cho toi",
    "dieu chinh lo trinh mot chut",
    "dieu chinh lo trinh nhanh giup",
    "dieu chinh lo trinh di",
    "dieu chinh lo trinh voi",
    "doi lo trinh hoc giup toi",
    "doi lo trinh hoc nhe",
    "doi lo trinh hoc duoc khong",
    "doi lo trinh hoc cho toi",
    "doi lo trinh hoc mot chut"
  ],
  "roadmap.explain_recommendation": [
    "vi sao he thong goi y bai nay",
    "tai sao de xuat hoc cai nay",
    "giai thich goi y nay",
    "ly do chon bai nay la gi",
    "tai sao roadmap bao hoc phan nay",
    "vi sao nen hoc part 5",
    "vi sao nen hoc part 7",
    "vi sao nen on tu vung",
    "vi sao nen lam de",
    "tai sao uu tien bai nay",
    "goi y nay dua tren dau",
    "he thong dua vao gi de de xuat",
    "tai sao toi phai hoc muc nay",
    "phan nay lien quan gi den diem cua toi",
    "giai thich recommendation",
    "why this recommendation",
    "tai sao bai nay phu hop voi toi",
    "vi sao chon chu de nay",
    "tai sao lo trinh sap xep nhu vay",
    "he thong tinh nhu the nao",
    "bai nay vi sao duoc de xuat",
    "bai nay tai sao nen hoc",
    "bai nay dua tren du lieu nao",
    "bai nay co ly do gi",
    "bai nay phu hop voi toi o dau",
    "lesson nay vi sao duoc de xuat",
    "lesson nay tai sao nen hoc",
    "lesson nay dua tren du lieu nao",
    "lesson nay co ly do gi",
    "lesson nay phu hop voi toi o dau",
    "nhiem vu nay vi sao duoc de xuat",
    "nhiem vu nay tai sao nen hoc",
    "nhiem vu nay dua tren du lieu nao",
    "nhiem vu nay co ly do gi",
    "nhiem vu nay phu hop voi toi o dau",
    "part nay vi sao duoc de xuat",
    "part nay tai sao nen hoc",
    "part nay dua tren du lieu nao",
    "part nay co ly do gi",
    "part nay phu hop voi toi o dau",
    "chu de nay vi sao duoc de xuat",
    "chu de nay tai sao nen hoc",
    "chu de nay dua tren du lieu nao",
    "chu de nay co ly do gi",
    "chu de nay phu hop voi toi o dau",
    "flashcard nay vi sao duoc de xuat",
    "flashcard nay tai sao nen hoc",
    "flashcard nay dua tren du lieu nao",
    "flashcard nay co ly do gi",
    "flashcard nay phu hop voi toi o dau",
    "de thi nay vi sao duoc de xuat",
    "de thi nay tai sao nen hoc",
    "de thi nay dua tren du lieu nao",
    "de thi nay co ly do gi",
    "de thi nay phu hop voi toi o dau",
    "lo trinh nay vi sao duoc de xuat",
    "lo trinh nay tai sao nen hoc",
    "lo trinh nay dua tren du lieu nao",
    "lo trinh nay co ly do gi",
    "lo trinh nay phu hop voi toi o dau",
    "buoc nay vi sao duoc de xuat",
    "buoc nay tai sao nen hoc",
    "buoc nay dua tren du lieu nao",
    "buoc nay co ly do gi",
    "buoc nay phu hop voi toi o dau",
    "goi y nay vi sao duoc de xuat",
    "goi y nay tai sao nen hoc",
    "goi y nay dua tren du lieu nao",
    "goi y nay co ly do gi",
    "goi y nay phu hop voi toi o dau",
    "giai thich vi sao hoc cai nay truoc",
    "tai sao khong hoc phan khac",
    "tai sao khong lam de luon",
    "tai sao he thong bao toi yeu phan nay",
    "lo trinh ca nhan hoa nhu the nao",
    "recommendation logic la gi",
    "goi y dua tren cau sai nao",
    "goi y dua tren tien do nao",
    "tai sao sap xep uu tien nhu vay",
    "vi sao can on lai bai nay",
    "vi sao he thong goi y bai nay giup toi",
    "vi sao he thong goi y bai nay nhe",
    "vi sao he thong goi y bai nay duoc khong",
    "vi sao he thong goi y bai nay cho toi",
    "vi sao he thong goi y bai nay mot chut",
    "vi sao he thong goi y bai nay nhanh giup",
    "vi sao he thong goi y bai nay di",
    "vi sao he thong goi y bai nay voi",
    "tai sao de xuat hoc cai nay giup toi",
    "tai sao de xuat hoc cai nay nhe",
    "tai sao de xuat hoc cai nay duoc khong",
    "tai sao de xuat hoc cai nay cho toi",
    "tai sao de xuat hoc cai nay mot chut",
    "tai sao de xuat hoc cai nay nhanh giup",
    "tai sao de xuat hoc cai nay di",
    "tai sao de xuat hoc cai nay voi",
    "giai thich goi y nay giup toi",
    "giai thich goi y nay nhe",
    "giai thich goi y nay duoc khong",
    "giai thich goi y nay cho toi"
  ],
  "roadmap.guidance": [
    "mo roadmap cho toi",
    "dua toi den roadmap",
    "vao lo trinh hoc",
    "lo trinh hoc o dau",
    "toi muon xem roadmap",
    "bat dau lo trinh nhu the nao",
    "huong dan su dung roadmap",
    "cach xem lo trinh",
    "cach theo doi roadmap",
    "vao dau de xem ke hoach hoc",
    "mo ke hoach hoc",
    "tim ke hoach hoc cua toi",
    "xem cac buoc trong roadmap",
    "roadmap nam o muc nao",
    "nut roadmap o dau",
    "lam sao mo lo trinh",
    "chi toi duong vao roadmap",
    "huong dan vao lo trinh",
    "toi can xem lo trinh",
    "show roadmap",
    "mo roadmap",
    "mo lo trinh",
    "mo lo trinh ca nhan",
    "mo study plan",
    "vao roadmap",
    "vao lo trinh",
    "vao ke hoach hoc",
    "vao lo trinh ca nhan",
    "vao study plan",
    "xem roadmap",
    "xem lo trinh",
    "xem ke hoach hoc",
    "xem lo trinh ca nhan",
    "xem study plan",
    "tim roadmap",
    "tim lo trinh",
    "tim ke hoach hoc",
    "tim lo trinh ca nhan",
    "tim study plan",
    "di toi roadmap",
    "di toi lo trinh",
    "di toi ke hoach hoc",
    "di toi lo trinh ca nhan",
    "di toi study plan",
    "dua toi den lo trinh",
    "dua toi den ke hoach hoc",
    "dua toi den lo trinh ca nhan",
    "dua toi den study plan",
    "chi toi roadmap",
    "chi toi lo trinh",
    "chi toi ke hoach hoc",
    "chi toi lo trinh ca nhan",
    "chi toi study plan",
    "roadmap dung sao",
    "lo trinh dung nhu the nao",
    "xem buoc tiep theo o dau",
    "xem bai trong roadmap o dau",
    "hoan thanh task trong roadmap sao",
    "bo qua buoc trong roadmap sao",
    "vao bai hoc tu roadmap sao",
    "tim lesson trong lo trinh",
    "roadmap co nhung gi",
    "hoc theo roadmap nhu the nao",
    "roadmap co nam trong trang dashboard khong",
    "lo trinh nam o trang dashboard khong",
    "roadmap co nam trong sidebar khong",
    "lo trinh nam o sidebar khong",
    "roadmap co nam trong menu hoc tap khong",
    "lo trinh nam o menu hoc tap khong",
    "roadmap co nam trong man hinh tien do khong",
    "lo trinh nam o man hinh tien do khong",
    "roadmap co nam trong trang ca nhan khong",
    "lo trinh nam o trang ca nhan khong",
    "mo roadmap cho toi giup toi",
    "mo roadmap cho toi nhe",
    "mo roadmap cho toi duoc khong",
    "mo roadmap cho toi cho toi",
    "mo roadmap cho toi mot chut",
    "mo roadmap cho toi nhanh giup",
    "mo roadmap cho toi di",
    "mo roadmap cho toi voi",
    "dua toi den roadmap giup toi",
    "dua toi den roadmap nhe",
    "dua toi den roadmap duoc khong",
    "dua toi den roadmap cho toi",
    "dua toi den roadmap mot chut",
    "dua toi den roadmap nhanh giup",
    "dua toi den roadmap di",
    "dua toi den roadmap voi",
    "vao lo trinh hoc giup toi",
    "vao lo trinh hoc nhe",
    "vao lo trinh hoc duoc khong",
    "vao lo trinh hoc cho toi",
    "vao lo trinh hoc mot chut",
    "vao lo trinh hoc nhanh giup",
    "vao lo trinh hoc di",
    "vao lo trinh hoc voi",
    "lo trinh hoc o dau giup toi",
    "lo trinh hoc o dau nhe",
    "lo trinh hoc o dau duoc khong"
  ],
  "roadmap.next_step": [
    "hom nay hoc gi",
    "gio hoc gi tiep",
    "tiep theo nen lam gi",
    "toi nen hoc gi tiep",
    "nen hoc phan nao tiep",
    "bat dau tu dau",
    "hom nay nen on gi",
    "goi y bai hoc tiep theo",
    "next step cua toi la gi",
    "buoc tiep theo la gi",
    "nen lam de hay hoc tu vung",
    "nen hoc listening hay reading",
    "toi nen lam bai nao",
    "nen on part nao",
    "nen hoc roadmap buoc nao",
    "hoc gi de tang diem",
    "toi nen uu tien gi",
    "hom nay nen lam task nao",
    "co viec gi can hoc khong",
    "cho lich hoc hom nay",
    "toi roi khong biet hoc gi",
    "chi minh buoc tiep theo",
    "hoc tiep di dau",
    "nen luyen cai nao",
    "chon bai hoc cho toi",
    "hom nay co nen hoc part 5 khong",
    "tiep theo co nen on part 5 khong",
    "part 5 co nen uu tien khong",
    "hom nay co nen hoc part 6 khong",
    "tiep theo co nen on part 6 khong",
    "part 6 co nen uu tien khong",
    "hom nay co nen hoc part 7 khong",
    "tiep theo co nen on part 7 khong",
    "part 7 co nen uu tien khong",
    "hom nay co nen hoc listening khong",
    "tiep theo co nen on listening khong",
    "listening co nen uu tien khong",
    "hom nay co nen hoc reading khong",
    "tiep theo co nen on reading khong",
    "reading co nen uu tien khong",
    "hom nay co nen hoc ngu phap khong",
    "tiep theo co nen on ngu phap khong",
    "ngu phap co nen uu tien khong",
    "hom nay co nen hoc tu vung khong",
    "tiep theo co nen on tu vung khong",
    "tu vung co nen uu tien khong",
    "hom nay co nen hoc flashcard khong",
    "tiep theo co nen on flashcard khong",
    "flashcard co nen uu tien khong",
    "hom nay co nen hoc de thi khong",
    "tiep theo co nen on de thi khong",
    "de thi co nen uu tien khong",
    "hom nay co nen hoc cau sai khong",
    "tiep theo co nen on cau sai khong",
    "cau sai co nen uu tien khong",
    "sang nay hoc gi",
    "sang nay nen on gi",
    "sang nay lam gi tiep",
    "chieu nay hoc gi",
    "chieu nay nen on gi",
    "chieu nay lam gi tiep",
    "toi nay hoc gi",
    "toi nay nen on gi",
    "toi nay lam gi tiep",
    "hom nay lam gi tiep",
    "ngay mai hoc gi",
    "ngay mai nen on gi",
    "ngay mai lam gi tiep",
    "cuoi tuan nay hoc gi",
    "cuoi tuan nay nen on gi",
    "cuoi tuan nay lam gi tiep",
    "hoc gi",
    "lam gi",
    "tieptheo lam gi",
    "nen hoc gi",
    "on gi",
    "lam bai nao",
    "chot bai nao",
    "di tiep the nao",
    "hom nay hoc gi giup toi",
    "hom nay hoc gi nhe",
    "hom nay hoc gi duoc khong",
    "hom nay hoc gi cho toi",
    "hom nay hoc gi mot chut",
    "hom nay hoc gi nhanh giup",
    "hom nay hoc gi di",
    "hom nay hoc gi voi",
    "gio hoc gi tiep giup toi",
    "gio hoc gi tiep nhe",
    "gio hoc gi tiep duoc khong",
    "gio hoc gi tiep cho toi",
    "gio hoc gi tiep mot chut",
    "gio hoc gi tiep nhanh giup",
    "gio hoc gi tiep di",
    "gio hoc gi tiep voi",
    "tiep theo nen lam gi giup toi",
    "tiep theo nen lam gi nhe",
    "tiep theo nen lam gi duoc khong",
    "tiep theo nen lam gi cho toi",
    "tiep theo nen lam gi mot chut"
  ],
  "roadmap.summary": [
    "roadmap cua toi the nao",
    "tom tat lo trinh cua toi",
    "tinh trang roadmap cua toi",
    "toi dang o dau trong lo trinh",
    "xem tien do lo trinh",
    "lo trinh cua toi con bao nhieu",
    "toi da hoan thanh bao nhieu roadmap",
    "ke hoach hoc cua toi ra sao",
    "tong quan roadmap",
    "bao cao lo trinh hoc",
    "hom nay roadmap co gi",
    "cac muc trong lo trinh cua toi",
    "toi dang hoc buoc nao",
    "buoc nao da xong",
    "buoc nao chua xong",
    "roadmap con task nao",
    "lo trinh hien tai cua toi",
    "xem ke hoach hien tai",
    "summary roadmap",
    "study plan summary",
    "roadmap hien tai ra sao",
    "roadmap da hoan thanh bao nhieu",
    "roadmap con viec gi",
    "roadmap tom tat giup toi",
    "roadmap tong quan giup toi",
    "lo trinh cua toi the nao",
    "lo trinh hien tai ra sao",
    "lo trinh da hoan thanh bao nhieu",
    "lo trinh con viec gi",
    "lo trinh tom tat giup toi",
    "lo trinh tong quan giup toi",
    "ke hoach hoc cua toi the nao",
    "ke hoach hoc hien tai ra sao",
    "ke hoach hoc da hoan thanh bao nhieu",
    "ke hoach hoc con viec gi",
    "ke hoach hoc tom tat giup toi",
    "ke hoach hoc tong quan giup toi",
    "study plan cua toi the nao",
    "study plan hien tai ra sao",
    "study plan da hoan thanh bao nhieu",
    "study plan con viec gi",
    "study plan tom tat giup toi",
    "study plan tong quan giup toi",
    "lo trinh ca nhan cua toi the nao",
    "lo trinh ca nhan hien tai ra sao",
    "lo trinh ca nhan da hoan thanh bao nhieu",
    "lo trinh ca nhan con viec gi",
    "lo trinh ca nhan tom tat giup toi",
    "lo trinh ca nhan tong quan giup toi",
    "toi dang tre lo trinh khong",
    "toi co theo kip roadmap khong",
    "roadmap hom nay trang thai gi",
    "con bao nhieu bai phai hoc",
    "cac milestone cua toi",
    "lo trinh sap toi co gi",
    "thang nay roadmap sao",
    "tuan nay roadmap sao",
    "muc tieu roadmap cua toi",
    "tien do theo ke hoach",
    "hom nay lo trinh cua toi sao",
    "hom nay roadmap cua toi sao",
    "hom nay ke hoach hoc cua toi sao",
    "tuan nay lo trinh cua toi sao",
    "tuan nay roadmap cua toi sao",
    "tuan nay ke hoach hoc cua toi sao",
    "thang nay lo trinh cua toi sao",
    "thang nay roadmap cua toi sao",
    "thang nay ke hoach hoc cua toi sao",
    "gan day lo trinh cua toi sao",
    "gan day roadmap cua toi sao",
    "gan day ke hoach hoc cua toi sao",
    "hien tai lo trinh cua toi sao",
    "hien tai roadmap cua toi sao",
    "hien tai ke hoach hoc cua toi sao",
    "roadmap cua toi the nao giup toi",
    "roadmap cua toi the nao nhe",
    "roadmap cua toi the nao duoc khong",
    "roadmap cua toi the nao cho toi",
    "roadmap cua toi the nao mot chut",
    "roadmap cua toi the nao nhanh giup",
    "roadmap cua toi the nao di",
    "roadmap cua toi the nao voi",
    "tom tat lo trinh cua toi giup toi",
    "tom tat lo trinh cua toi nhe",
    "tom tat lo trinh cua toi duoc khong",
    "tom tat lo trinh cua toi cho toi",
    "tom tat lo trinh cua toi mot chut",
    "tom tat lo trinh cua toi nhanh giup",
    "tom tat lo trinh cua toi di",
    "tom tat lo trinh cua toi voi",
    "tinh trang roadmap cua toi giup toi",
    "tinh trang roadmap cua toi nhe",
    "tinh trang roadmap cua toi duoc khong",
    "tinh trang roadmap cua toi cho toi",
    "tinh trang roadmap cua toi mot chut",
    "tinh trang roadmap cua toi nhanh giup",
    "tinh trang roadmap cua toi di",
    "tinh trang roadmap cua toi voi",
    "toi dang o dau trong lo trinh giup toi",
    "toi dang o dau trong lo trinh nhe"
  ],
  "smalltalk.greeting_feedback": [
    "hi",
    "hello",
    "hey",
    "alo",
    "chao",
    "xin chao",
    "chao ban",
    "co ai o do khong",
    "ban oi",
    "minh hoi chut",
    "giup minh voi",
    "ban giup minh voi",
    "bat dau hoc nao",
    "bat dau tiep nhe",
    "minh quay lai hoc tiep day",
    "hoc tiep thoi",
    "ok",
    "oke",
    "uh",
    "um",
    "roi",
    "duoc roi",
    "minh hieu roi",
    "ro roi",
    "ngon roi",
    "cam on",
    "cam on ban",
    "cam on nhe",
    "cam on nhieu",
    "thanks",
    "thank you",
    "thanks ban",
    "xin loi minh hoi nham",
    "khong sao",
    "bo qua di",
    "thoi duoc roi",
    "de sau tinh",
    "minh chan",
    "toi chan",
    "chan qua",
    "hoc kho qua",
    "met qua",
    "buon ngu qua",
    "nan qua",
    "kho qua",
    "toi nan qua",
    "minh hoi met",
    "hom nay hoc met qua",
    "dong vien minh chut di",
    "toi thay toeic kho qua",
    "hi minh can hoi",
    "hi giup minh nhe",
    "hi bat dau nha",
    "hi co ranh khong",
    "hello minh can hoi",
    "hello giup minh nhe",
    "hello bat dau nha",
    "hello co ranh khong",
    "chao minh can hoi",
    "chao giup minh nhe",
    "chao bat dau nha",
    "chao co ranh khong",
    "alo minh can hoi",
    "alo giup minh nhe",
    "alo bat dau nha",
    "alo co ranh khong",
    "hey minh can hoi",
    "hey giup minh nhe",
    "hey bat dau nha",
    "hey co ranh khong",
    "ban oi minh can hoi",
    "ban oi giup minh nhe",
    "ban oi bat dau nha",
    "ban oi co ranh khong",
    "tro ly oi",
    "tro ly oi minh can hoi",
    "tro ly oi giup minh nhe",
    "tro ly oi bat dau nha",
    "tro ly oi co ranh khong",
    "chatbot oi",
    "chatbot oi minh can hoi",
    "chatbot oi giup minh nhe",
    "chatbot oi bat dau nha",
    "chatbot oi co ranh khong",
    "cam on nha",
    "cam on rat nhieu",
    "cam on minh hieu roi",
    "thanks nhe",
    "thanks nha",
    "thanks rat nhieu",
    "thanks minh hieu roi",
    "thank you nhe",
    "thank you nha",
    "thank you rat nhieu",
    "thank you minh hieu roi",
    "cam on nhieu nhe",
    "cam on nhieu nha",
    "cam on nhieu rat nhieu",
    "cam on nhieu minh hieu roi",
    "cam on nha nhe"
  ],
  "test_attempt.analysis": [
    "phan tich de thi nay",
    "de nay toi sai nhieu khong",
    "bai thi nay the nao",
    "ket qua de nay ra sao",
    "de vua lam sao",
    "phan tich bai vua lam",
    "xem diem de gan nhat",
    "de gan nhat cua toi the nao",
    "toi lam on khong",
    "bai nay on khong",
    "de nay te khong",
    "sai nhieu khong",
    "sai phan nao nhieu",
    "part nao sai nhieu",
    "listening sai nhieu khong",
    "reading sai nhieu khong",
    "phan tich loi sai trong de",
    "toi yeu part nao trong de nay",
    "de nay mat diem o dau",
    "diem nay co tot khong",
    "ket qua vua roi the nao",
    "vua roi lam sao",
    "de thi nay on khong",
    "de thi nay kho khong",
    "bai lam nay co tien bo khong",
    "so voi lan truoc the nao",
    "toi co cai thien khong",
    "giai thich ket qua bai thi",
    "tom tat bai thi vua lam",
    "review attempt nay",
    "de nay the nao",
    "de nay on khong",
    "de nay sai nhieu khong",
    "de nay can cai thien gi",
    "de nay yeu phan nao",
    "de nay phan tich giup toi",
    "de nay tom tat giup toi",
    "bai nay the nao",
    "bai nay sai nhieu khong",
    "bai nay can cai thien gi",
    "bai nay yeu phan nao",
    "bai nay mat diem o dau",
    "bai nay phan tich giup toi",
    "bai nay tom tat giup toi",
    "attempt nay the nao",
    "attempt nay on khong",
    "attempt nay sai nhieu khong",
    "attempt nay can cai thien gi",
    "attempt nay yeu phan nao",
    "attempt nay mat diem o dau",
    "attempt nay phan tich giup toi",
    "attempt nay tom tat giup toi",
    "bai vua lam the nao",
    "bai vua lam on khong",
    "bai vua lam sai nhieu khong",
    "bai vua lam can cai thien gi",
    "bai vua lam yeu phan nao",
    "bai vua lam mat diem o dau",
    "bai vua lam phan tich giup toi",
    "bai vua lam tom tat giup toi",
    "de gan nhat the nao",
    "de gan nhat on khong",
    "de gan nhat sai nhieu khong",
    "de gan nhat can cai thien gi",
    "de gan nhat yeu phan nao",
    "de gan nhat mat diem o dau",
    "de gan nhat phan tich giup toi",
    "de gan nhat tom tat giup toi",
    "ket qua nay the nao",
    "ket qua nay on khong",
    "ket qua nay sai nhieu khong",
    "ket qua nay can cai thien gi",
    "ket qua nay yeu phan nao",
    "ket qua nay mat diem o dau",
    "ket qua nay phan tich giup toi",
    "ket qua nay tom tat giup toi",
    "bai thi nay on khong",
    "bai thi nay sai nhieu khong",
    "bai thi nay can cai thien gi",
    "bai thi nay yeu phan nao",
    "bai thi nay mat diem o dau",
    "bai thi nay phan tich giup toi",
    "bai thi nay tom tat giup toi",
    "lan lam bai nay the nao",
    "lan lam bai nay on khong",
    "lan lam bai nay sai nhieu khong",
    "lan lam bai nay can cai thien gi",
    "lan lam bai nay yeu phan nao",
    "lan lam bai nay mat diem o dau",
    "lan lam bai nay phan tich giup toi",
    "lan lam bai nay tom tat giup toi",
    "trong de nay part 1 the nao",
    "part 1 sai nhieu khong trong de nay",
    "phan tich part 1 cua bai nay",
    "trong de nay part 2 the nao",
    "part 2 sai nhieu khong trong de nay",
    "phan tich part 2 cua bai nay",
    "trong de nay part 3 the nao",
    "part 3 sai nhieu khong trong de nay",
    "phan tich part 3 cua bai nay"
  ],
  "toeic_knowledge.general": [
    "toeic la gi",
    "cau truc de thi toeic",
    "format de thi toeic",
    "toeic co may part",
    "part 5 la gi",
    "part 6 la gi",
    "part 7 la gi",
    "listening co may phan",
    "reading co may phan",
    "thang diem toeic la gi",
    "toeic tinh diem nhu the nao",
    "bao nhieu cau trong toeic",
    "thoi gian lam bai toeic",
    "meo lam part 5",
    "meo lam part 7",
    "cach hoc tu vung toeic",
    "cach tang diem listening",
    "cach tang diem reading",
    "nen hoc toeic nhu the nao",
    "ngu phap toeic can hoc gi",
    "tu vung toeic chu de nao quan trong",
    "toeic 600 can hoc gi",
    "toeic 700 kho khong",
    "luyen de toeic bao nhieu lan",
    "co nen hoc flashcard toeic khong",
    "part 1 la gi",
    "cach lam part 1",
    "meo lam part 1",
    "part 1 co dang cau nao",
    "part 1 can luu y gi",
    "part 2 la gi",
    "cach lam part 2",
    "meo lam part 2",
    "part 2 co dang cau nao",
    "part 2 can luu y gi",
    "part 3 la gi",
    "cach lam part 3",
    "meo lam part 3",
    "part 3 co dang cau nao",
    "part 3 can luu y gi",
    "part 4 la gi",
    "cach lam part 4",
    "meo lam part 4",
    "part 4 co dang cau nao",
    "part 4 can luu y gi",
    "cach lam part 5",
    "part 5 co dang cau nao",
    "part 5 can luu y gi",
    "cach lam part 6",
    "meo lam part 6",
    "part 6 co dang cau nao",
    "part 6 can luu y gi",
    "cach lam part 7",
    "part 7 co dang cau nao",
    "part 7 can luu y gi",
    "listening trong toeic la gi",
    "cach hoc listening",
    "meo listening toeic",
    "reading trong toeic la gi",
    "cach hoc reading",
    "meo reading toeic",
    "ngu phap trong toeic la gi",
    "cach hoc ngu phap",
    "meo ngu phap toeic",
    "tu vung trong toeic la gi",
    "cach hoc tu vung",
    "meo tu vung toeic",
    "paraphrase trong toeic la gi",
    "cach hoc paraphrase",
    "meo paraphrase toeic",
    "skimming trong toeic la gi",
    "cach hoc skimming",
    "meo skimming toeic",
    "scanning trong toeic la gi",
    "cach hoc scanning",
    "meo scanning toeic",
    "inference question trong toeic la gi",
    "cach hoc inference question",
    "meo inference question toeic",
    "double passage trong toeic la gi",
    "cach hoc double passage",
    "meo double passage toeic",
    "email memo notice trong toeic la gi",
    "cach hoc email memo notice",
    "meo email memo notice toeic",
    "toeic khac ielts nhu the nao",
    "toeic 2 ky nang la gi",
    "toeic 4 ky nang la gi",
    "diem toeic bao nhieu la tot",
    "toeic co kho khong",
    "hoc toeic tu con so 0",
    "loi thuong gap khi thi toeic",
    "nen hoc nghe truoc hay doc truoc",
    "tai lieu toeic nen hoc",
    "chien luoc lam de toeic",
    "toeic la gi giup toi",
    "toeic la gi nhe",
    "toeic la gi duoc khong",
    "toeic la gi cho toi",
    "toeic la gi mot chut"
  ],
  "user_progress.ability_map": [
    "toi yeu phan nao",
    "toi manh phan nao",
    "nang luc cua toi the nao",
    "level toeic cua toi sao",
    "trinh do hien tai cua toi",
    "toi kem listening hay reading",
    "toi yeu listening khong",
    "toi yeu reading khong",
    "part nao toi yeu nhat",
    "part nao toi tot nhat",
    "phan nao can cai thien",
    "ky nang nao can uu tien",
    "diem yeu cua toi la gi",
    "diem manh cua toi la gi",
    "toi dang o muc nao",
    "ban do nang luc cua toi",
    "ability map cua toi",
    "phan tich nang luc cua toi",
    "toi co loi sai nao lap lai",
    "toi hay sai dang nao",
    "ngu phap cua toi yeu khong",
    "tu vung cua toi on khong",
    "toi co yeu part 5 khong",
    "toi co yeu part 7 khong",
    "toi can tap trung ky nang nao",
    "listening cua toi the nao",
    "toi manh listening khong",
    "listening co can cai thien khong",
    "reading cua toi the nao",
    "toi manh reading khong",
    "reading co can cai thien khong",
    "toi yeu part 1 khong",
    "part 1 cua toi the nao",
    "toi manh part 1 khong",
    "part 1 co can cai thien khong",
    "toi yeu part 2 khong",
    "part 2 cua toi the nao",
    "toi manh part 2 khong",
    "part 2 co can cai thien khong",
    "toi yeu part 3 khong",
    "part 3 cua toi the nao",
    "toi manh part 3 khong",
    "part 3 co can cai thien khong",
    "toi yeu part 4 khong",
    "part 4 cua toi the nao",
    "toi manh part 4 khong",
    "part 4 co can cai thien khong",
    "toi yeu part 5 khong",
    "part 5 cua toi the nao",
    "toi manh part 5 khong",
    "part 5 co can cai thien khong",
    "toi yeu part 6 khong",
    "part 6 cua toi the nao",
    "toi manh part 6 khong",
    "part 6 co can cai thien khong",
    "toi yeu part 7 khong",
    "part 7 cua toi the nao",
    "toi manh part 7 khong",
    "part 7 co can cai thien khong",
    "toi yeu ngu phap khong",
    "ngu phap cua toi the nao",
    "toi manh ngu phap khong",
    "ngu phap co can cai thien khong",
    "toi yeu tu vung khong",
    "tu vung cua toi the nao",
    "toi manh tu vung khong",
    "tu vung co can cai thien khong",
    "toi nen uu tien ky nang nao",
    "nang luc tong quan cua toi",
    "kiem tra diem yeu cua toi",
    "toi dang kem o dau",
    "toi co tien bo ky nang nao",
    "ky nang nao tut nhat",
    "ky nang nao dang on dinh",
    "so do nang luc cua toi",
    "phan tich diem manh yeu",
    "toi co gap van de ve grammar khong",
    "toi yeu phan nao giup toi",
    "toi yeu phan nao nhe",
    "toi yeu phan nao duoc khong",
    "toi yeu phan nao cho toi",
    "toi yeu phan nao mot chut",
    "toi yeu phan nao nhanh giup",
    "toi yeu phan nao di",
    "toi yeu phan nao voi",
    "toi manh phan nao giup toi",
    "toi manh phan nao nhe",
    "toi manh phan nao duoc khong",
    "toi manh phan nao cho toi",
    "toi manh phan nao mot chut",
    "toi manh phan nao nhanh giup",
    "toi manh phan nao di",
    "toi manh phan nao voi",
    "nang luc cua toi the nao giup toi",
    "nang luc cua toi the nao nhe",
    "nang luc cua toi the nao duoc khong",
    "nang luc cua toi the nao cho toi",
    "nang luc cua toi the nao mot chut",
    "nang luc cua toi the nao nhanh giup",
    "nang luc cua toi the nao di"
  ],
  "user_progress.summary": [
    "tien do cua toi the nao",
    "tom tat tien do hoc tap",
    "bao cao hoc tap cua toi",
    "hom nay toi hoc duoc gi",
    "tuan nay toi hoc sao",
    "thang nay tien do sao",
    "toi hoc bao nhieu bai roi",
    "toi lam bao nhieu de roi",
    "toi da hoc bao nhieu tu",
    "tong quan tien do",
    "xem progress cua toi",
    "thong ke hoc tap cua toi",
    "toi co cham hoc khong",
    "toi co tien bo khong",
    "tien bo gan day cua toi",
    "nhat ky hoc tap cua toi",
    "so buoi hoc cua toi",
    "streak cua toi",
    "hom nay da hoan thanh gi",
    "cac muc da hoan thanh",
    "toi dang hoc toi dau",
    "ket qua hoc tap gan day",
    "bao cao nhanh cho toi",
    "summary progress",
    "learning summary",
    "hom nay tien do cua toi sao",
    "hom nay toi lam duoc bao nhieu",
    "tom tat hom nay",
    "hom qua toi hoc duoc gi",
    "hom qua tien do cua toi sao",
    "hom qua toi lam duoc bao nhieu",
    "tom tat hom qua",
    "tuan nay toi hoc duoc gi",
    "tuan nay tien do cua toi sao",
    "tuan nay toi lam duoc bao nhieu",
    "tom tat tuan nay",
    "tuan truoc toi hoc duoc gi",
    "tuan truoc tien do cua toi sao",
    "tuan truoc toi lam duoc bao nhieu",
    "tom tat tuan truoc",
    "thang nay toi hoc duoc gi",
    "thang nay tien do cua toi sao",
    "thang nay toi lam duoc bao nhieu",
    "tom tat thang nay",
    "gan day toi hoc duoc gi",
    "gan day tien do cua toi sao",
    "gan day toi lam duoc bao nhieu",
    "tom tat gan day",
    "7 ngay qua toi hoc duoc gi",
    "7 ngay qua tien do cua toi sao",
    "7 ngay qua toi lam duoc bao nhieu",
    "tom tat 7 ngay qua",
    "30 ngay qua toi hoc duoc gi",
    "30 ngay qua tien do cua toi sao",
    "30 ngay qua toi lam duoc bao nhieu",
    "tom tat 30 ngay qua",
    "toi da hoan thanh bao nhieu bai hoc",
    "bai hoc cua toi tien do sao",
    "thong ke bai hoc cua toi",
    "toi da hoan thanh bao nhieu de thi",
    "de thi cua toi tien do sao",
    "thong ke de thi cua toi",
    "toi da hoan thanh bao nhieu flashcard",
    "flashcard cua toi tien do sao",
    "thong ke flashcard cua toi",
    "toi da hoan thanh bao nhieu tu vung",
    "tu vung cua toi tien do sao",
    "thong ke tu vung cua toi",
    "toi da hoan thanh bao nhieu cau hoi",
    "cau hoi cua toi tien do sao",
    "thong ke cau hoi cua toi",
    "toi da hoan thanh bao nhieu cau sai",
    "cau sai cua toi tien do sao",
    "thong ke cau sai cua toi",
    "toi da hoan thanh bao nhieu roadmap task",
    "roadmap task cua toi tien do sao",
    "thong ke roadmap task cua toi",
    "toi co dat muc tieu tuan nay khong",
    "toi co bo lo bai nao khong",
    "hom nay con viec gi chua xong",
    "tien do so voi muc tieu",
    "toi hoc deu khong",
    "bao nhieu ngay lien tiep",
    "toi co cham tien do khong",
    "nhan xet qua trinh hoc cua toi",
    "tong ket hoc tap",
    "xem thanh tich cua toi",
    "tien do cua toi the nao giup toi",
    "tien do cua toi the nao nhe",
    "tien do cua toi the nao duoc khong",
    "tien do cua toi the nao cho toi",
    "tien do cua toi the nao mot chut",
    "tien do cua toi the nao nhanh giup",
    "tien do cua toi the nao di",
    "tien do cua toi the nao voi",
    "tom tat tien do hoc tap giup toi",
    "tom tat tien do hoc tap nhe",
    "tom tat tien do hoc tap duoc khong",
    "tom tat tien do hoc tap cho toi",
    "tom tat tien do hoc tap mot chut"
  ],
  "vocabulary.contextual": [
    "tu nay nghia la gi",
    "giai thich tu nay",
    "tu vung cau nay la gi",
    "tu nao quan trong trong cau nay",
    "lay tu vung cau nay",
    "co tu kho nao khong",
    "giai thich cac tu kho",
    "tu nay dung sao",
    "tu nay la loai tu gi",
    "nghia cua tu nay",
    "tu nay dong nghia voi gi",
    "tu nay trai nghia voi gi",
    "phat am tu nay sao",
    "vi du voi tu nay",
    "collocation cua tu nay",
    "cum tu nay nghia la gi",
    "phrase nay la gi",
    "idiom nay la gi",
    "tu nay trong toeic hay gap khong",
    "tu nay co nghia nao khac khong",
    "chon tu vung quan trong",
    "tach tu vung trong cau",
    "vocabulary cua cau nay",
    "tu kho trong doan nay",
    "tu nao can hoc",
    "tu nay",
    "nghia tu",
    "tu kho",
    "vocab",
    "vocabulary",
    "giai thich vocab",
    "word meaning",
    "meaning of this word",
    "tu nay dung nhu the nao",
    "tu nay co vi du khong",
    "tu nay co hay gap trong toeic khong",
    "cum tu nay dung nhu the nao",
    "cum tu nay la loai tu gi",
    "cum tu nay co vi du khong",
    "cum tu nay dong nghia voi gi",
    "cum tu nay trai nghia voi gi",
    "cum tu nay co hay gap trong toeic khong",
    "phrase nay nghia la gi",
    "phrase nay dung nhu the nao",
    "phrase nay la loai tu gi",
    "phrase nay co vi du khong",
    "phrase nay dong nghia voi gi",
    "phrase nay trai nghia voi gi",
    "phrase nay co hay gap trong toeic khong",
    "vocab nay nghia la gi",
    "vocab nay dung nhu the nao",
    "vocab nay la loai tu gi",
    "vocab nay co vi du khong",
    "vocab nay dong nghia voi gi",
    "vocab nay trai nghia voi gi",
    "vocab nay co hay gap trong toeic khong",
    "word nay nghia la gi",
    "word nay dung nhu the nao",
    "word nay la loai tu gi",
    "word nay co vi du khong",
    "word nay dong nghia voi gi",
    "word nay trai nghia voi gi",
    "word nay co hay gap trong toeic khong",
    "tu trong cau nay nghia la gi",
    "tu trong cau nay dung nhu the nao",
    "tu trong cau nay la loai tu gi",
    "tu trong cau nay co vi du khong",
    "tu trong cau nay dong nghia voi gi",
    "tu trong cau nay trai nghia voi gi",
    "tu trong cau nay co hay gap trong toeic khong",
    "tu kho nay nghia la gi",
    "tu kho nay dung nhu the nao",
    "tu kho nay la loai tu gi",
    "tu kho nay co vi du khong",
    "tu kho nay dong nghia voi gi",
    "tu kho nay trai nghia voi gi",
    "tu kho nay co hay gap trong toeic khong",
    "liet ke tu vung quan trong",
    "lay 5 tu kho",
    "lay 10 tu kho",
    "tu nao nen luu",
    "tu nao kho nhat",
    "giai thich tung tu kho",
    "tach vocabulary trong doan",
    "noi nghia cac tu moi",
    "co collocation nao khong",
    "tu nay formal hay informal",
    "tu nay dung trong business sao",
    "tu nay co prefix suffix khong",
    "word family cua tu nay",
    "danh tu dong tu tinh tu cua tu nay",
    "cach dung tu nay trong cau",
    "tu nay nghia la gi giup toi",
    "tu nay nghia la gi nhe",
    "tu nay nghia la gi duoc khong",
    "tu nay nghia la gi cho toi",
    "tu nay nghia la gi mot chut",
    "tu nay nghia la gi nhanh giup",
    "tu nay nghia la gi di",
    "tu nay nghia la gi voi"
  ],
  "lesson.recommendation": [
    "goi y bai hoc part 1",
    "goi y bai hoc part 2",
    "goi y bai hoc part 3",
    "goi y bai hoc part 4",
    "goi y bai hoc part 5",
    "goi y bai hoc part 6",
    "goi y bai hoc part 7",
    "cho toi bai luyen part 1",
    "cho toi bai luyen part 2",
    "cho toi bai luyen part 3",
    "cho toi bai luyen part 4",
    "cho toi bai luyen part 5",
    "cho toi bai luyen part 6",
    "cho toi bai luyen part 7",
    "tim bai hoc part 5 cho toi",
    "tim bai hoc part 7 cho minh",
    "de xuat lesson part 3",
    "recommend lesson part 4",
    "suggest lesson part 6",
    "cho minh activity part 2",
    "goi y unit part 5",
    "tim bai luyen reading part 7",
    "tim bai luyen listening part 3",
    "goi y bai hoc nghe part 4",
    "goi y bai hoc doc part 6",
    "goi y bai hoc menh de quan he",
    "goi y bai hoc ve menh de quan he",
    "tim lesson relative clause",
    "recommend lesson relative clause",
    "bai hoc ve relative clauses",
    "goi y bai hoc tu loai",
    "tim bai hoc ve danh tu",
    "tim bai hoc ve tinh tu",
    "tim bai hoc ve trang tu",
    "tim bai hoc ve dong tu",
    "goi y bai hoc thi hien tai",
    "goi y bai hoc thi qua khu",
    "goi y bai hoc gioi tu",
    "goi y bai hoc lien tu",
    "goi y bai hoc cau bi dong",
    "tim bai hoc ve cau bi dong",
    "goi y bai hoc ve clause",
    "goi y bai hoc ve participle",
    "tim bai hoc ve v ing",
    "tim bai hoc ve to v",
    "goi y bai hoc dang suy luan",
    "tim bai luyen dang suy luan",
    "goi y bai hoc inference",
    "suggest inference lessons",
    "goi y bai hoc dang tim thong tin",
    "tim bai luyen dang chi tiet",
    "goi y bai hoc main idea",
    "goi y bai hoc chu de doan van",
    "tim bai hoc ve purpose question",
    "goi y bai hoc ve implied meaning",
    "goi y bai hoc ve cau hoi do thi",
    "tim bai hoc ve graphic question",
    "goi y bai hoc chu de company",
    "goi y bai hoc chu de office",
    "goi y bai hoc chu de shopping",
    "goi y bai hoc chu de travel",
    "goi y bai hoc chu de restaurant",
    "goi y bai hoc chu de personnel",
    "goi y bai hoc chu de meeting",
    "goi y bai hoc chu de email",
    "goi y bai hoc part 5 menh de quan he",
    "goi y bai hoc part 5 tu loai",
    "goi y bai hoc part 5 gioi tu",
    "goi y bai hoc part 5 lien tu",
    "goi y bai hoc part 5 cau bi dong",
    "goi y bai hoc part 6 lien ket cau",
    "goi y bai hoc part 6 tu loai",
    "goi y bai hoc part 6 ngu canh",
    "goi y bai hoc part 7 dang suy luan",
    "goi y bai hoc part 7 tim thong tin",
    "goi y bai hoc part 7 main idea",
    "goi y bai hoc part 7 double passage",
    "goi y bai hoc part 3 implied meaning",
    "goi y bai hoc part 3 graphic question",
    "goi y bai hoc part 4 main idea",
    "goi y bai hoc part 4 chi tiet",
    "goi y bai hoc part 2 cau hoi why",
    "goi y bai hoc part 2 yes no question",
    "goi y bai hoc part 1 tranh nguoi",
    "goi y bai hoc part 1 tranh vat",
    "suggest part 5 grammar lessons",
    "recommend part 5 relative clause lessons",
    "recommend part 7 inference lessons",
    "suggest part 7 detail question activities",
    "find lessons about noun adjective adverb",
    "find grammar lesson about passive voice",
    "recommend toeic lesson about prepositions",
    "suggest reading lesson about main idea",
    "suggest listening lesson part 3",
    "find activity for part 4",
    "recommend unit about business email",
    "suggest lesson for company topic",
    "goi y 3 bai hoc part 5",
    "goi y 5 bai hoc part 7",
    "cho toi 4 bai luyen ve suy luan",
    "tim 3 lesson relative clause",
    "de xuat 5 activity part 6",
    "goi y bai hoc phu hop part 5",
    "goi y bai luyen dung trinh do ve tu loai",
    "tim bai hoc phu hop voi muc diem cua toi part 7",
    "cho toi bai hoc dung trinh do ve menh de quan he",
    "goi y bai hoc theo kha nang hien tai part 3"
  ]
};
