import { ChatIntent, IntentAvailability, IntentLane } from "../types/chat.types";
import type { IntentSignalMetadata } from "./chat_intent_signal.service";
import { CHAT_INTENT_EXTRA_POSITIVE_EXAMPLES } from "./chat_intent_extra_examples.data";

export type IntentEngine =
  | "TEMPLATE"
  | "ACTION"
  | "DB_FIRST"
  | "DB_FIRST_AI"
  | "GENERAL_AI";

export type ContextPolicy = {
  auth?: boolean;
  allOf?: string[];
  anyOf?: string[];
  onMissing: "CLARIFY" | "SAFE_FALLBACK";
};

export type IntentCatalogEntry = {
  id: string;
  intentId: ChatIntent;
  lane: IntentLane;
  engine: IntentEngine;
  availability: IntentAvailability;
  semanticSearchEnabled: boolean;
  contextType: string;
  contextPolicy: ContextPolicy;
  priority: number;
  examples: string[];
  hardNegatives: string[];
} & IntentSignalMetadata;

type RawIntentCatalogEntry = Omit<IntentCatalogEntry, keyof IntentSignalMetadata>;

export const CHAT_INTENT_COLLECTION = "chat_intent_examples";
export const CHAT_INTENT_CATALOG_VERSION = 18;

const INTENT_SIGNAL_METADATA: Partial<Record<ChatIntent, IntentSignalMetadata>> = {
  "smalltalk.greeting_feedback": {
    entities: ["smalltalk"],
    actions: ["general_ask"],
    defaultAction: "general_ask",
    forbiddenActions: ["create", "translate", "analyze", "locate_ui", "open", "navigate"],
  },
  "user_profile.identity": {
    entities: ["user_profile"],
    actions: ["ask_status", "general_ask"],
    defaultAction: "ask_status",
    requiredContext: ["userId"],
    forbiddenActions: ["locate_ui", "open", "navigate", "create", "translate"],
  },
  "user_progress.summary": {
    entities: ["progress"],
    actions: ["ask_status", "general_ask", "analyze"],
    defaultAction: "ask_status",
    requiredContext: ["userId"],
    forbiddenActions: ["locate_ui", "open", "navigate", "create", "translate"],
  },
  "user_progress.ability_map": {
    entities: ["progress"],
    actions: ["ask_status", "general_ask", "analyze"],
    defaultAction: "ask_status",
    requiredContext: ["userId"],
    forbiddenActions: ["locate_ui", "open", "navigate", "create", "translate"],
  },
  "test_attempt.analysis": {
    entities: ["attempt"],
    actions: ["analyze", "ask_status", "general_ask"],
    defaultAction: "analyze",
    requiredContext: ["userId"],
    forbiddenActions: ["locate_ui", "open", "navigate", "create", "translate"],
  },
  "question.explain_specific": {
    entities: ["question"],
    actions: ["explain", "analyze"],
    defaultAction: "explain",
    requiredContext: ["questionId", "attemptId"],
    forbiddenActions: ["locate_ui", "open", "navigate", "create", "ask_status"],
  },
  "question.translate_context": {
    entities: ["question"],
    actions: ["translate"],
    defaultAction: "translate",
    requiredContext: ["questionId", "attemptId"],
    forbiddenActions: ["locate_ui", "open", "navigate", "create", "ask_status"],
  },
  "question.similar_practice": {
    entities: ["question"],
    actions: ["recommend", "next_step"],
    defaultAction: "recommend",
    requiredContext: ["questionId"],
    forbiddenActions: ["locate_ui", "open", "navigate", "create", "ask_status", "translate"],
  },
  "lesson.recommendation": {
    entities: ["lesson"],
    actions: ["recommend"],
    defaultAction: "recommend",
    requiredContext: ["userId"],
    forbiddenActions: ["locate_ui", "open", "navigate", "create", "translate", "ask_status"],
  },
  "vocabulary.contextual": {
    entities: ["question"],
    actions: ["explain", "translate", "general_ask"],
    defaultAction: "explain",
    requiredContext: ["questionId", "attemptId"],
    forbiddenActions: ["locate_ui", "open", "navigate", "create", "ask_status"],
  },
  "grammar.contextual": {
    entities: ["question"],
    actions: ["explain", "analyze", "general_ask"],
    defaultAction: "explain",
    requiredContext: ["questionId", "attemptId"],
    forbiddenActions: ["locate_ui", "open", "navigate", "create", "ask_status"],
  },
  "toeic_knowledge.general": {
    entities: ["toeic_knowledge"],
    actions: ["general_ask", "recommend", "explain"],
    defaultAction: "general_ask",
    forbiddenActions: ["locate_ui", "open", "navigate", "create"],
  },
  "roadmap.guidance": {
    entities: ["roadmap"],
    actions: ["locate_ui", "open", "navigate"],
    defaultAction: "locate_ui",
    requiredContext: ["userId"],
    forbiddenActions: ["ask_status", "analyze", "create", "translate"],
  },
  "roadmap.summary": {
    entities: ["roadmap"],
    actions: ["ask_status", "general_ask"],
    defaultAction: "ask_status",
    requiredContext: ["userId"],
    forbiddenActions: ["locate_ui", "open", "navigate", "create", "translate"],
  },
  "roadmap.next_step": {
    entities: ["roadmap"],
    actions: ["next_step", "recommend"],
    defaultAction: "next_step",
    requiredContext: ["userId"],
    forbiddenActions: ["locate_ui", "open", "navigate", "create", "translate"],
  },
  "roadmap.explain_recommendation": {
    entities: ["roadmap"],
    actions: ["explain", "analyze"],
    defaultAction: "explain",
    requiredContext: ["userId"],
    forbiddenActions: ["locate_ui", "open", "navigate", "create", "translate"],
  },
  "roadmap.adjust": {
    entities: ["roadmap"],
    actions: ["adjust"],
    defaultAction: "adjust",
    requiredContext: ["userId"],
    forbiddenActions: ["locate_ui", "open", "navigate", "translate"],
  },
  "flashcard.create": {
    entities: ["flashcard"],
    actions: ["create"],
    defaultAction: "create",
    requiredContext: ["userId"],
    forbiddenActions: ["locate_ui", "open", "navigate", "ask_status", "translate"],
  },
  "flashcard.personal": {
    entities: ["flashcard"],
    actions: ["locate_ui", "open", "navigate", "general_ask"],
    defaultAction: "open",
    requiredContext: ["userId"],
    forbiddenActions: ["create", "translate", "analyze"],
  },
  "listening_practice.analysis": {
    entities: ["attempt"],
    actions: ["analyze"],
    defaultAction: "analyze",
    requiredContext: ["attemptId"],
    forbiddenActions: ["locate_ui", "open", "navigate", "create"],
  },
  "app.navigation_support": {
    entities: ["app"],
    actions: ["locate_ui", "open", "navigate"],
    defaultAction: "locate_ui",
    forbiddenActions: ["ask_status", "analyze", "create", "translate"],
  },
  "out_of_project.general": {
    entities: ["out_of_project"],
    actions: ["general_ask"],
    defaultAction: "general_ask",
    forbiddenActions: ["create", "translate", "analyze", "locate_ui", "open", "navigate"],
  },
};

const DEFAULT_SIGNAL_METADATA: IntentSignalMetadata = {
  entities: ["toeic_knowledge"],
  actions: ["general_ask"],
  defaultAction: "general_ask",
  forbiddenActions: [],
};

const RAW_CHAT_INTENT_EXAMPLES: RawIntentCatalogEntry[] = [
  {
    id: "out_of_project_general",
    intentId: "out_of_project.general",
    lane: "SYSTEM",
    engine: "TEMPLATE",
    availability: "ACTIVE",
    semanticSearchEnabled: true,
    contextType: "out_of_project",
    contextPolicy: { onMissing: "SAFE_FALLBACK" },
    priority: 95,
    examples: [
      "thoi tiet hom nay the nao",
      "hom nay mua hay nang",
      "bitcoin gia bao nhieu",
      "gia vang hom nay",
      "du doan chung khoan hom nay",
      "bong da toi nay ai da",
      "lich thi dau bong da",
      "tu van thuoc dau dau",
      "toi bi sot uong thuoc gi",
      "nau pho nhu the nao",
      "cong thuc nau an don gian",
      "viet code python cho toi",
      "sua bug react giup toi",
      "tin chinh tri moi nhat",
      "mua laptop nao tot",
      "dat ve may bay di da nang",
      "lich chieu phim hom nay",
      "ke chuyen ma di",
      "viet tho tinh cho toi",
      "crypto nao nen mua",
    ],
    hardNegatives: [
      "dich cau nay",
      "giai thich cau nay",
      "toi yeu ky nang nao",
      "mo roadmap",
      "tao flashcard",
      "TOEIC Part 5 la gi",
      "cach hoc tu vung TOEIC",
    ],
  },
  {
    id: "smalltalk_greeting_feedback",
    intentId: "smalltalk.greeting_feedback",
    lane: "SYSTEM",
    engine: "TEMPLATE",
    availability: "ACTIVE",
    semanticSearchEnabled: true,
    contextType: "template",
    contextPolicy: { onMissing: "SAFE_FALLBACK" },
    priority: 80,
    examples: [
      "hi",
      "hello",
      "hey",
      "alo",
      "chao",
      "xin chao",
      "chao ban",
      "co ai o do khong",
      "bat dau hoc nao",
      "minh can hoi nhanh",
      "ban giup minh voi",
      "cam on",
      "cam on ban",
      "cam on nhe",
      "cam on nhieu",
      "cam on ban nhe",
      "cam on ban nhieu",
      "cam on nha",
      "cam on ban nha",
      "minh cam on",
      "minh cam on ban",
      "thanks ban",
      "thank you ban",
      "thanks",
      "thank you",
      "ok",
      "oke",
      "uh",
      "um",
      "roi",
      "duoc roi",
      "minh hieu roi",
      "ro roi",
      "ngon roi",
      "chan",
      "toi chan",
      "minh chan",
      "hoc kho qua",
      "chan qua",
      "toi chan qua",
      "minh chan qua",
      "hoc chan qua",
      "met qua",
      "buon ngu qua",
      "hom nay hoc met qua",
      "nan qua",
      "kho qua",
      "toi nan qua",
      "minh hoi met",
      "hom nay hoc hoi duoi",
      "minh dang bi roi",
      "dong vien minh chut di",
      "toi thay TOEIC kho qua",
      "minh quay lai hoc tiep day",
      "bat dau tiep nhe",
      "xin loi minh hoi nham",
    ],
    hardNegatives: [
      "toi yeu phan nao",
      "giai thich cau nay",
      "meo lam part 5",
    ],
  },
  {
    id: "user_profile_identity",
    intentId: "user_profile.identity",
    lane: "CONTEXTUAL",
    engine: "DB_FIRST",
    availability: "ACTIVE",
    semanticSearchEnabled: true,
    contextType: "user_profile_identity",
    contextPolicy: { auth: true, onMissing: "SAFE_FALLBACK" },
    priority: 87,
    examples: [
      "toi la ai",
      "toi la ai tren he thong",
      "ban biet toi la ai khong",
      "ban dang biet gi ve toi",
      "thong tin ca nhan cua toi",
      "thong tin account cua toi",
      "ho so cua toi tren he thong",
      "profile cua toi co gi",
      "email dang dang nhap la gi",
      "ten hien thi cua toi la gi",
      "toi dang dung tai khoan nao",
      "tai khoan nao dang dang nhap",
    ],
    hardNegatives: [
      "toi la ai trong cuoc doi nay",
      "toi la ai tren doi nay",
      "ban nghi toi la nguoi nhu the nao",
      "toi co phai nguoi tot khong",
      "toi nen song nhu the nao",
      "ban co biet toi ngoai doi khong",
      "toi yeu phan nao",
      "tien do cua toi",
      "diem gan nhat cua toi",
      "lo trinh cua toi",
      "doi ten tai khoan",
      "doi mat khau",
    ],
  },
  {
    id: "user_progress_summary",
    intentId: "user_progress.summary",
    lane: "CONTEXTUAL",
    engine: "DB_FIRST",
    availability: "ACTIVE",
    semanticSearchEnabled: true,
    contextType: "user_progress",
    contextPolicy: { auth: true, onMissing: "SAFE_FALLBACK" },
    priority: 85,
    examples: [
      "tien do hoc cua toi the nao",
      "tien do hoc cua toi ra sao",
      "tien do hoc tap cua toi the nao",
      "tien do hoc tap cua toi ra sao",
      "tong quan tien do cua toi ra sao",
      "tong hop tien do hoc cua toi",
      "toi dang hoc duoc bao nhieu phan tram",
      "toi yeu phan nao",
      "toi yeu phan nao vay",
      "toi yeu phan nao nhi",
      "toi yeu phan nao nhat",
      "toi yeu phan nao trong TOEIC",
      "toi yeu phan nao trong qua trinh hoc",
      "toi dang yeu phan nao",
      "toi con yeu phan nao",
      "toi can cai thien phan nao",
      "phan nao cua toi dang yeu",
      "phan nao toi yeu nhat",
      "phan nao cua toi yeu nhat",
      "ky nang nao cua toi yeu nhat",
      "skill nao cua toi dang yeu",
      "trong TOEIC toi yeu phan nao",
      "xem tong quan toi yeu phan nao",
      "dua tren tien do toi yeu phan nao",
      "phan nao toi can on nhieu nhat",
      "toi da hoan thanh bao nhieu bai",
      "muc tieu diem cua toi la bao nhieu",
      "diem hien tai cua toi la bao nhieu",
      "target TOEIC cua toi con xa khong",
      "toi dang o trinh do nao",
      "toi tien bo nhanh hay cham",
      "toc do hoc cua toi co on khong",
      "streak hoc cua toi hien tai la may ngay",
      "chuoi ngay hoc cua toi con khong",
      "tong thoi gian hoc cua toi la bao nhieu",
      "toi hoc co deu khong",
      "diem manh cua toi la gi",
      "toi co dang theo kip muc tieu khong",
      "toi con thieu bao nhieu diem de dat target",
      "trang thai hoc tap cua toi hien tai ra sao",
      "toi co bo hoc nhieu khong",
      "ban tong hop tien do hoc tap cua toi di",
    ],
    hardNegatives: [
      "bai test nay toi yeu phan nao",
      "de gan nhat cua toi the nao",
      "phan tich de gan nhat cua toi",
      "bai test vua lam cua toi ra sao",
      "bai nay toi sai phan nao",
      "buoc tiep theo trong roadmap la gi",
      "meo tang diem reading",
    ],
  },
  {
    id: "user_progress_ability_map",
    intentId: "user_progress.ability_map",
    lane: "CONTEXTUAL",
    engine: "DB_FIRST",
    availability: "ACTIVE",
    semanticSearchEnabled: true,
    contextType: "ability_map",
    contextPolicy: { auth: true, onMissing: "SAFE_FALLBACK" },
    priority: 88,
    examples: [
      "nang luc cua toi the nao",
      "ban do nang luc cua toi",
      "toi dang o muc nao",
      "trinh do hien tai cua toi ra sao",
      "toi yeu part nao",
      "toi manh part nao",
      "nang luc tung part cua toi the nao",
      "skill cua toi hien tai ra sao",
      "kha nang TOEIC hien tai cua toi the nao",
      "trinh do toeic hien tai cua toi",
      "uoc tinh diem hien tai theo nang luc",
      "toi dang manh yeu nhu the nao",
      "part nao cua toi dang yeu",
      "part nao cua toi dang tot",
      "xem ban do nang luc rut gon cho toi",
    ],
    hardNegatives: [
      "tien do hoc cua toi the nao",
      "tong quan tien do cua toi",
      "streak hoc cua toi",
      "de gan nhat cua toi the nao",
      "phan tich de gan nhat cua toi",
      "lo trinh cua toi the nao",
      "buoc tiep theo trong roadmap la gi",
    ],
  },
  {
    id: "test_attempt_analysis",
    intentId: "test_attempt.analysis",
    lane: "CONTEXTUAL",
    engine: "DB_FIRST_AI",
    availability: "ACTIVE",
    semanticSearchEnabled: true,
    contextType: "test_attempt_summary",
    contextPolicy: { auth: true, onMissing: "CLARIFY" },
    priority: 90,
    examples: [
      "phan tich bai test nay",
      "phan tich ket qua bai test nay",
      "xem giup minh bai test vua lam",
      "bai test nay toi lam the nao",
      "bai test nay diem yeu cua toi la gi",
      "bai test nay toi yeu phan nao",
      "trong bai test nay toi sai nhieu part nao",
      "part nao trong bai nay sai nhieu nhat",
      "nhung loi sai chinh trong bai test nay la gi",
      "toi nen sua loi nao truoc trong bai test nay",
      "hay tong ket bai lam nay",
      "ket qua attempt nay noi len dieu gi",
      "phan tich attempt hien tai",
      "bai nay toi mat diem o dau",
      "bai test nay co mau loi nao lap lai khong",
      "nhom loi sai trong ket qua nay la gi",
      "toi can on lai tag nao sau bai test nay",
      "dua tren bai test nay nen luyen phan nao",
      "xem ty le dung sai trong bai test nay",
      "bai lam nay reading yeu hay listening yeu",
      "bai test gan nhat cua toi can phan tich",
      "phan tich bai test gan nhat",
      "de gan nhat cua toi the nao",
      "phan tich de gan nhat cua toi",
      "de moi nhat cua toi ra sao",
      "bai nay toi sai phan nao",
      "phan tich de thi nay",
      "de thi nay toi sai nhieu khong",
      "de thi nay toi sai phan nao",
      "ket qua de thi nay ra sao",
      "de thi gan nhat cua toi the nao",
      "phan tich de thi gan nhat cua toi",
      "de gan nhat toi sai chu yeu o dau",
      "de gan nhat toi sai o dau",
      "de gan nhat toi sai nhieu o dau",
      "de gan nhat toi sai nhieu phan nao",
      "de gan nhat toi hay sai gi",
      "de gan nhat loi sai chinh cua toi la gi",
      "bai gan nhat toi sai chu yeu o dau",
      "bai test gan nhat toi sai chu yeu o dau",
      "attempt gan nhat toi sai chu yeu o dau",
      "bai thi gan nhat toi sai chu yeu o dau",
      "de moi nhat toi sai nhieu phan nao",
      "ket qua bai test gan nhat cua toi the nao",
      "bai thi gan nhat cua toi the nao",
      "ket qua bai thi gan nhat ra sao",
      "bai lam gan nhat cua toi the nao",
      "bai test vua lam cua toi ra sao",
      "phan tich bai thi gan nhat",
      "bai thi gan nhat toi sai phan nao",
      "diem bai thi gan nhat noi len dieu gi",
      "review bai thi vua nop",
      "review diem bai test vua nop",
      "toi sai bao nhieu cau trong bai nay",
      "bai test nay co cau sai nao can xem truoc",
      "hay chi ra uu tien sua loi trong attempt nay",
      "toi muon xem bao cao cua bai test nay",
      "phan tich phan sai trong ket qua test nay",
      "bai thi thu nay cho thay toi can hoc gi",
    ],
    hardNegatives: [
      "cau nay toi sai o dau",
      "toi sai o dau trong cau nay",
      "loi sai cua toi o cau nay la gi",
      "dap an cua toi sai cho nao",
      "tien do hoc cua toi the nao",
      "nang luc cua toi the nao",
      "tien do hoc cua toi ra sao",
      "tong quan tien do cua toi",
      "giai thich cau nay",
      "meo lam bai test toeic",
    ],
  },
  {
    id: "question_explain_specific",
    intentId: "question.explain_specific",
    lane: "CONTEXTUAL",
    engine: "DB_FIRST_AI",
    availability: "ACTIVE",
    semanticSearchEnabled: true,
    contextType: "quick_question",
    contextPolicy: {
      auth: true,
      allOf: ["questionId", "attemptId"],
      onMissing: "CLARIFY",
    },
    priority: 95,
    examples: [
      "sao toi sai cau nay",
      "vi sao dap an la C",
      "tai sao dap an dung la B",
      "sao A sai ma C dung",
      "giai thich cau nay",
      "giai thich cau so 5",
      "giai thich nhanh cau nay",
      "cau nay lam nhu the nao",
      "dap an nay tai sao dung",
      "vi sao lua chon cua toi sai",
      "tai sao khong chon A",
      "tai sao phai chon D",
      "cach suy luan cau nay la gi",
      "huong dan cach lam cau nay",
      "phan tich dap an dung sai cua cau nay",
      "cau nay can chu y diem nao",
      "cau nay toi sai o dau",
      "cau nay toi sai o dau vay",
      "cau nay minh sai o dau",
      "cau nay em sai o dau",
      "cau nay sai cho nao",
      "cau nay toi sai cho nao",
      "cau nay minh sai cho nao",
      "toi sai o dau o cau nay",
      "minh sai o dau o cau nay",
      "toi sai cho nao trong cau nay",
      "minh sai cho nao trong cau nay",
      "loi sai cua toi o cau nay la gi",
      "toi bi sai o dau trong cau nay",
      "toi sai o dau trong cau nay",
      "dap an cua toi sai cho nao",
      "dap an toi chon sai o dau trong cau nay",
      "vi sao toi sai cau nay",
      "tai sao toi sai cau nay",
      "sai o dau trong cau hien tai",
      "cau nay co meo gi de lam khong",
      "tai sao cau nay dung theo dap an he thong",
      "giai thich tung lua chon cua cau nay",
      "so sanh dap an toi chon voi dap an dung",
      "cau nay nen loai dap an nao truoc",
      "tai sao dap an khac khong phu hop",
      "minh khong hieu cau hoi nay",
      "giai thich logic cua cau hoi nay",
      "dap an dung dua vao dau",
      "tai sao cau nay khong phai dap an A",
      "chi minh cach nhan ra dap an dung cau nay",
      "cau hoi nay kiem tra kien thuc gi de ra dap an",
    ],
    hardNegatives: [
      "menh de quan he la gi",
      "phan tich bai test nay",
      "tien do cua toi the nao",
      "lo trinh hoc o dau",
      "xem lo trinh o cho nao",
      "mo flashcard",
      "nang luc cua toi the nao",
    ],
  },
  {
    id: "question_translate_context",
    intentId: "question.translate_context",
    lane: "CONTEXTUAL",
    engine: "DB_FIRST_AI",
    availability: "ACTIVE",
    semanticSearchEnabled: true,
    contextType: "question_review",
    contextPolicy: {
      auth: true,
      allOf: ["questionId", "attemptId"],
      onMissing: "CLARIFY",
    },
    priority: 88,
    examples: [
      "dich cau nay",
      "dich cau nay sang tieng viet",
      "dich giup minh cau nay",
      "dich giup toi cau nay",
      "hay dich cau nay",
      "cho minh ban dich cau nay",
      "ban dich cua cau nay",
      "cau nay dich la gi",
      "dich noi dung cau hoi nay",
      "dich phan de bai nay",
      "dich 4 dap an",
      "dich cac lua chon cua cau nay",
      "dich passage nay",
      "dich doan van nay",
      "dich transcript nay",
      "dich doan nghe nay",
      "cau nay nghia tieng viet la gi",
      "doan nay nghia tieng viet la gi",
      "viet ban dich tieng viet cho cau nay",
      "hay dich nguyen cau hoi",
      "dich ca cau va dap an",
      "dich phan listening script",
      "dich noi dung audio transcript",
      "dich bai doc nay sang tieng viet",
      "dich sentence hien tai",
      "dich option A B C D",
      "cho minh ban dich cua passage",
      "minh muon hieu nghia tieng viet cua doan nay",
      "giai nghia bang tieng viet toan bo cau nay",
      "dich cum trong dap an nay",
      "dich dong transcript dang xem",
      "ban dich cua cau hoi nay la gi",
      "dich phan huong dan trong cau nay",
      "dich noi dung dang hien tren man hinh",
      "chuyen cau nay sang tieng viet",
      "dich cau tieng anh nay cho minh",
      "viet lai nghia tieng viet cua cau hoi",
    ],
    hardNegatives: [
      "tao cho toi 10 tu vung cho chu de house",
      "tao 10 tu vung chu de house",
      "tao bo tu vung ve chu de house",
      "sinh flashcard chu de house",
      "affect va effect khac nhau the nao",
      "meo lam part 7",
      "phan tich ket qua bai test",
      "cau nay dung ngu phap gi",
      "ngu phap cua cau nay la gi",
      "lo trinh hoc o dau",
      "xem lo trinh o cho nao",
      "roadmap nam o dau trong app",
      "mo flashcard",
      "nang luc cua toi the nao",
    ],
  },
  {
    id: "question_similar_practice",
    intentId: "question.similar_practice",
    lane: "CONTEXTUAL",
    engine: "DB_FIRST",
    availability: "ACTIVE",
    semanticSearchEnabled: true,
    contextType: "similar_practice",
    contextPolicy: {
      auth: true,
      allOf: ["questionId"],
      onMissing: "CLARIFY",
    },
    priority: 87,
    examples: [
      "luyen cau tuong tu",
      "goi y bai luyen tuong tu",
      "cho toi bai luyen tuong tu cau nay",
      "on luyen cau tuong tu",
      "tim bai luyen cung tag cau nay",
      "luyen them tag cua cau nay",
      "goi y bai tap lien quan cau nay",
      "toi muon luyen dang cau nay",
      "co bai nao giong cau nay de luyen khong",
      "luyen lai skill cua cau nay",
    ],
    hardNegatives: [
      "giai thich cau nay",
      "dich cau nay",
      "tu nay nghia la gi",
      "cau nay dung ngu phap gi",
      "tao flashcard tu cau nay",
      "mo flashcard",
    ],
  },
  {
    id: "lesson_recommendation",
    intentId: "lesson.recommendation",
    lane: "CONTEXTUAL",
    engine: "DB_FIRST",
    availability: "ACTIVE",
    semanticSearchEnabled: true,
    contextType: "lesson_recommendation",
    contextPolicy: { auth: true, onMissing: "SAFE_FALLBACK" },
    priority: 86,
    examples: [
      "goi y bai hoc part 5",
      "cho toi bai luyen part 7",
      "tim lesson part 3",
      "goi y bai hoc menh de quan he",
      "bai hoc ve tu loai",
      "bai luyen dang suy luan",
      "goi y bai hoc part 5 menh de quan he",
      "goi y bai hoc part 7 dang suy luan",
      "recommend lesson relative clause",
      "suggest part 7 inference lessons",
      "tim bai hoc ngu phap part 5",
      "cho minh activity ve chu de company",
    ],
    hardNegatives: [
      "hom nay hoc gi",
      "bai tiep theo la gi",
      "goi y bai hoc tiep theo cho toi",
      "hoc gi theo lo trinh",
      "bai hoc tiep theo cua toi",
      "goi y theo tien do hien tai",
      "menh de quan he la gi",
      "cach lam part 7",
      "ngu phap part 5 gom gi",
      "tao flashcard tu cau nay",
      "luu tu nay vao flashcard",
      "liet ke tu vung trong cau nay",
      "giai thich tu nay",
      "dich cau nay",
      "luyen cau tuong tu cau nay",
    ],
  },
  {
    id: "vocabulary_contextual",
    intentId: "vocabulary.contextual",
    lane: "CONTEXTUAL",
    engine: "DB_FIRST_AI",
    availability: "ACTIVE",
    semanticSearchEnabled: true,
    contextType: "question_review",
    contextPolicy: {
      auth: true,
      allOf: ["questionId", "attemptId"],
      onMissing: "CLARIFY",
    },
    priority: 86,
    examples: [
      "awning nghia la gi",
      "pick up nghia la gi",
      "pick up trong cau nay nghia la gi",
      "pick up trong cau nay co nghia la gi",
      "cum pick up trong cau nay nghia la gi",
      "cum tu pick up trong cau nay nghia la gi",
      "pick up o day nghia la gi",
      "pick up trong ngu canh nay nghia la gi",
      "tu pick up trong cau nay co nghia gi",
      "giai thich nghia pick up trong cau nay",
      "nghia cua pick up trong cau nay",
      "tu nay nghia la gi",
      "tu nay trong cau nay nghia la gi",
      "tu nay trong cau nay co nghia gi",
      "cum tu nay nghia la gi",
      "cum tu nay trong cau nay nghia la gi",
      "cum tu nay trong ngu canh nay nghia la gi",
      "load voi unload khac gi",
      "cho toi vocab cau nay",
      "liet ke tu vung trong cau nay",
      "tu nao quan trong trong cau nay",
      "giai thich tu significant trong cau nay",
      "giai thich nghia cua tu nay",
      "giai thich cum tu nay",
      "nghia cua word nay la gi",
      "tu nay la danh tu hay dong tu",
      "tu nay trong ngu canh nay co nghia gi",
      "cum nay trong TOEIC hay dung the nao",
      "hay cho vi du ve tu nay",
      "phan biet hai tu nay giup minh",
      "tu nay co dong nghia nao",
      "tu nay trai nghia voi gi",
      "collocation cua tu nay la gi",
      "cach dung tu nay trong cau",
      "tu nay co sac thai nghia gi",
      "keyword tu vung cua cau nay la gi",
      "vocabulary trong passage nay gom gi",
      "cho minh nghia cua cum tu duoc chon",
      "tu duoc highlight co nghia gi",
      "nghia tieng viet cua tu nay la gi",
      "giai thich phrase nay bang tieng viet",
      "tu vung nao lam minh sai cau nay",
      "tu nay trong dap an co nghia gi",
    ],
    hardNegatives: [
      "cach hoc tu vung toeic",
      "affect va effect khac nhau the nao",
      "mo flashcard",
      "lo trinh hoc o dau",
      "xem lo trinh o cho nao",
      "roadmap nam o dau trong app",
      "nang luc cua toi the nao",
    ],
  },
  {
    id: "grammar_contextual",
    intentId: "grammar.contextual",
    lane: "CONTEXTUAL",
    engine: "DB_FIRST_AI",
    availability: "ACTIVE",
    semanticSearchEnabled: true,
    contextType: "question_review",
    contextPolicy: {
      auth: true,
      allOf: ["questionId", "attemptId"],
      onMissing: "CLARIFY",
    },
    priority: 86,
    examples: [
      "cau nay dung ngu phap gi",
      "cau nay dung ngu phap gi vay",
      "cau nay dung ngu phap gi nhi",
      "cau nay dung ngu phap gi the",
      "cau nay dung ngu phap gi day",
      "cau nay dung ngu phap gi de ra dap an",
      "cau nay dang dung ngu phap gi",
      "cau nay la dang ngu phap gi",
      "cau nay dung diem ngu phap gi",
      "cau nay thuoc ngu phap gi",
      "cau nay ap dung ngu phap nao",
      "cau nay la ngu phap nao",
      "cau nay dang dung ngu phap nao",
      "cau nay dung grammar gi",
      "cau nay dung grammar point nao",
      "cau nay thuoc grammar point nao",
      "cau nay kiem tra ngu phap nao",
      "cau nay kiem tra diem ngu phap nao",
      "cau nay co ngu phap gi",
      "cau nay co diem ngu phap nao",
      "ngu phap nao trong cau nay",
      "ngu phap cua cau nay la diem nao",
      "ngu phap cua cau nay la gi",
      "cho trong can loai tu gi",
      "vi sao khong dung V-ing",
      "tai sao o day dung danh tu",
      "tai sao o day dung dong tu",
      "phan biet cau truc cau nay",
      "cau truc ngu phap cua cau nay la gi",
      "cho minh phan tich ngu phap cau nay",
      "chu ngu vi ngu trong cau nay la gi",
      "menh de trong cau nay la menh de gi",
      "tai sao dung thi hien tai hoan thanh",
      "tai sao dung bi dong o day",
      "tai sao phai chia dong tu nhu vay",
      "tu loai can dien vao cho trong la gi",
      "dau hieu ngu phap cua cau nay la gi",
      "cau nay kiem tra grammar point nao",
      "phan tich cau truc sau cho trong",
      "vi sao khong dung to V",
      "vi sao dap an la adjective",
      "vi sao can adverb trong cau nay",
      "cau nay lien quan den relative clause khong",
      "cau nay co cau truc song song khong",
      "sau gioi tu phai dung gi trong cau nay",
      "vi sao dung past participle o day",
      "cach nhan biet loai tu trong cau nay",
      "phan tich thanh phan cau giup minh",
      "grammar rule nao ap dung cho cau nay",
      "cau nay sai vi ngu phap nao",
      "tai sao lua chon dung hop ngu phap",
    ],
    hardNegatives: [
      "menh de quan he la gi",
      "cac chu diem ngu phap toeic quan trong",
      "meo lam part 5",
      "lo trinh hoc o dau",
      "xem lo trinh o cho nao",
      "roadmap nam o dau trong app",
      "mo flashcard",
      "nang luc cua toi the nao",
    ],
  },
  {
    id: "toeic_knowledge_general",
    intentId: "toeic_knowledge.general",
    lane: "GENERAL_AI",
    engine: "GENERAL_AI",
    availability: "ACTIVE",
    semanticSearchEnabled: true,
    contextType: "general_rag",
    contextPolicy: { onMissing: "SAFE_FALLBACK" },
    priority: 70,
    examples: [
      "menh de quan he la gi",
      "affect va effect khac nhau the nao",
      "meo lam Part 5",
      "TOEIC co may phan",
      "tu 400 len 600 hoc sao",
      "cach hoc tu vung TOEIC",
      "chien luoc lam Part 7",
      "Part 3 nen nghe nhu the nao",
      "Part 4 co meo gi khong",
      "Part 1 can chu y gi",
      "Part 2 lam sao de bat keyword",
      "cach lam cau incomplete sentences",
      "cach lam text completion TOEIC",
      "cach doc nhanh Part 7",
      "nen hoc grammar TOEIC theo thu tu nao",
      "cac chu diem ngu phap TOEIC quan trong",
      "phan biet much va many",
      "phan biet since va for",
      "cach dung although va despite",
      "cach dung because va because of",
      "collocation TOEIC nen hoc la gi",
      "lam sao tang diem listening",
      "lam sao tang diem reading",
      "mot ngay nen hoc TOEIC bao lau",
      "nguoi moi bat dau TOEIC hoc gi truoc",
      "cach luyen de TOEIC hieu qua",
      "chien luoc phan bo thoi gian TOEIC",
      "lam sao tranh bay trong Part 5",
      "tu vung TOEIC ve van phong gom gi",
      "cach ghi nho tu vung TOEIC lau hon",
      "lo trinh hoc o dau tot",
      "nen hoc TOEIC o dau hieu qua",
    ],
    hardNegatives: [
      "giai thich cau nay",
      "tien do cua toi the nao",
      "phan tich bai test vua lam",
    ],
  },
  {
    id: "roadmap_guidance",
    intentId: "roadmap.guidance",
    lane: "CONTEXTUAL",
    engine: "ACTION",
    availability: "ACTION_ONLY",
    semanticSearchEnabled: true,
    contextType: "roadmap",
    contextPolicy: { auth: true, onMissing: "SAFE_FALLBACK" },
    priority: 82,
    examples: [
      "mo roadmap",
      "mo roadmap cua toi",
      "mo phan roadmap",
      "mo muc roadmap",
      "mo trang roadmap",
      "vao roadmap",
      "vao trang roadmap",
      "di toi roadmap",
      "di den trang roadmap",
      "chuyen sang roadmap",
      "mo lo trinh",
      "di den roadmap",
      "cho toi xem trang roadmap",
      "mo phan ke hoach hoc",
      "di den lo trinh hoc",
      "lo trinh hoc o dau",
      "xem lo trinh o cho nao",
      "toi xem lo trinh o cho nao",
      "roadmap nam o dau trong app",
      "mo lo trinh hoc",
    ],
    hardNegatives: [
      "roadmap cua toi toi dau roi",
      "lo trinh hoc",
      "lo trinh thi sao",
      "toi dang o dau trong lo trinh",
      "lo trinh hoc o dau tot",
      "vi sao roadmap chon bai nay",
      "tien do hoc cua toi the nao",
    ],
  },
  {
    id: "roadmap_summary",
    intentId: "roadmap.summary",
    lane: "CONTEXTUAL",
    engine: "DB_FIRST",
    availability: "ACTIVE",
    semanticSearchEnabled: true,
    contextType: "roadmap_summary",
    contextPolicy: { auth: true, onMissing: "SAFE_FALLBACK" },
    priority: 90,
    examples: [
      "lo trinh hoc",
      "lo trinh thi sao",
      "lo trinh cua toi",
      "lo trinh cua toi the nao",
      "roadmap cua toi toi dau roi",
      "lo trinh hien tai ra sao",
      "toi dang o dau trong lo trinh",
      "toi da hoan thanh bao nhieu lo trinh",
      "tien do roadmap cua toi",
      "toi dang o stage nao",
      "toi dang o giai doan nao",
      "cycle hien tai cua toi la gi",
      "lo trinh cua toi dang o cycle nao",
      "cycle hien tai tap trung phan nao",
    ],
    hardNegatives: [
      "mo lo trinh",
      "lo trinh hoc o dau",
      "xem lo trinh o cho nao",
      "roadmap nam o dau trong app",
      "lo trinh hoc o dau tot",
      "hom nay toi nen hoc gi",
      "tai sao he thong chon bai nay",
    ],
  },
  {
    id: "roadmap_next_step",
    intentId: "roadmap.next_step",
    lane: "CONTEXTUAL",
    engine: "DB_FIRST",
    availability: "ACTIVE",
    semanticSearchEnabled: true,
    contextType: "roadmap_next_step",
    contextPolicy: { auth: true, onMissing: "SAFE_FALLBACK" },
    priority: 91,
    examples: [
      "hom nay toi nen hoc gi",
      "buoc tiep theo la gi",
      "toi nen hoc gi tiep theo",
      "roadmap giao bai gi tiep theo",
      "tiep theo toi can lam gi",
      "stage tiep theo toi hoc gi",
      "giai doan tiep theo cua lo trinh la gi",
      "cycle nay toi can lam gi tiep theo",
      "session tiep theo trong roadmap la gi",
    ],
    hardNegatives: [
      "mo roadmap",
      "lo trinh cua toi the nao",
      "tai sao he thong chon bai nay",
    ],
  },
  {
    id: "roadmap_explain_recommendation",
    intentId: "roadmap.explain_recommendation",
    lane: "CONTEXTUAL",
    engine: "DB_FIRST_AI",
    availability: "ACTIVE",
    semanticSearchEnabled: true,
    contextType: "roadmap_recommendation",
    contextPolicy: { auth: true, onMissing: "SAFE_FALLBACK" },
    priority: 92,
    examples: [
      "tai sao he thong chon bai nay",
      "vi sao roadmap de xuat bai nay",
      "ly do toi phai hoc buoc nay",
      "tai sao bai nay duoc xep tiep theo",
      "giai thich de xuat hoc tap nay",
      "vi sao stage nay hoc bai nay",
      "tai sao cycle nay tap trung part nay",
      "vi sao giai doan nay lai hoc skill nay",
      "giai thich ly do stage hien tai",
    ],
    hardNegatives: [
      "mo roadmap",
      "lo trinh cua toi toi dau roi",
      "doi lo trinh",
    ],
  },
  {
    id: "roadmap_adjust",
    intentId: "roadmap.adjust",
    lane: "CONTEXTUAL",
    engine: "ACTION",
    availability: "ACTION_ONLY",
    semanticSearchEnabled: true,
    contextType: "roadmap_adjust",
    contextPolicy: { auth: true, onMissing: "SAFE_FALLBACK" },
    priority: 89,
    examples: [
      "doi lo trinh",
      "chinh lo trinh hoc",
      "giam khoi luong hoc",
      "tang thoi gian hoc moi ngay",
      "cap nhat ke hoach hoc",
    ],
    hardNegatives: [
      "mo lo trinh",
      "lo trinh cua toi the nao",
      "hom nay toi nen hoc gi",
    ],
  },
  {
    id: "flashcard_create",
    intentId: "flashcard.create",
    lane: "CONTEXTUAL",
    engine: "DB_FIRST",
    availability: "ACTIVE",
    semanticSearchEnabled: true,
    contextType: "flashcard_supply",
    contextPolicy: { auth: true, onMissing: "CLARIFY" },
    priority: 91,
    examples: [
      "tao 20 tu chu de office",
      "tao cho toi 10 tu vung cho chu de house",
      "tao cho toi 10 tu vung ve chu de house",
      "tao cho toi muoi tu vung chu de house",
      "tao giup toi 10 tu vung chu de house",
      "tao 10 tu vung chu de house",
      "tao 10 tu vung ve house",
      "tao 10 tu vung ve chu de house",
      "tao bo tu vung ve chu de house",
      "tao danh sach tu vung chu de house",
      "tao tu vung theo chu de house",
      "tao flashcard tu vung chu de house",
      "sinh flashcard chu de house",
      "sinh 10 flashcard chu de house",
      "sinh bo tu vung chu de house",
      "tao flashcard chu de house",
      "tao flashcard chu de business",
      "tao 15 flashcard ve travel",
      "tao bo tu vung ve meeting",
      "tao nhanh 20 tu de hoc flashcard",
      "tao flashcard tu cau nay",
      "tao 10 tu trong cau nay",
      "tao cho toi 10 tu chu de cau nay",
      "tao 10 tu vung lien quan den cau nay",
      "sinh bo tu vung tu cau nay de hoc",
      "luu cac tu kho cua cau nay thanh flashcard",
      "chi lay tu trong cau nay de tao flashcard",
      "tao flashcard tu cau sai nay",
      "tao bo tu de on cau nay",
    ],
    hardNegatives: [
      "mo flashcard",
      "di den flashcard",
      "toi co bao nhieu flashcard can on",
      "cach hoc tu vung toeic",
      "liet ke tu vung trong cau nay",
      "giai thich tu significant trong cau nay",
      "tu nao quan trong trong cau nay",
      "luyen cau tuong tu",
    ],
  },
  {
    id: "flashcard_personal",
    intentId: "flashcard.personal",
    lane: "CONTEXTUAL",
    engine: "ACTION",
    availability: "ACTION_ONLY",
    semanticSearchEnabled: true,
    contextType: "flashcard",
    contextPolicy: { auth: true, onMissing: "SAFE_FALLBACK" },
    priority: 82,
    examples: [
      "mo flashcard",
      "mo flashcard cua toi",
      "mo phan flashcard",
      "mo muc flashcard",
      "mo trang flashcard",
      "vao flashcard",
      "vao trang flashcard",
      "di toi flashcard",
      "di den trang flashcard",
      "chuyen sang flashcard",
      "di den flashcard",
      "cho toi vao phan on flashcard",
      "mo trang on tu",
      "toi muon mo bo flashcard",
      "chuyen toi trang flashcard",
    ],
    hardNegatives: [
      "toi co bao nhieu flashcard can on",
      "tu nao toi hay quen nhat",
      "cach hoc tu vung toeic",
    ],
  },
  {
    id: "listening_practice_analysis",
    intentId: "listening_practice.analysis",
    lane: "CONTEXTUAL",
    engine: "DB_FIRST_AI",
    availability: "DISABLED",
    // Internal-only capability for future listening/shadowing analysis flows.
    // It is intentionally not routable from userText and stays out of Chroma.
    semanticSearchEnabled: false,
    contextType: "listening_practice",
    contextPolicy: {
      auth: true,
      anyOf: ["dictationAttemptId", "shadowingAttemptId"],
      onMissing: "CLARIFY",
    },
    priority: 84,
    examples: [
      "bai dictation nay sai o dau",
      "phan tich bai dictation hien tai",
      "toi nghe thieu tu nao trong dictation",
      "so sanh transcript voi cau tra loi cua toi",
      "dictation nay toi bo sot nhung tu nao",
      "loi nghe sai trong bai dictation nay la gi",
      "toi can nghe lai cau nao trong dictation",
      "goi y luyen lai cau nao trong bai nghe nay",
      "phan tich transcript diff cua toi",
      "cau nao toi nghe sai nhieu nhat",
      "bai shadowing nay toi phat am sai tu nao",
      "phan tich bai shadowing hien tai",
      "toi phat am sai tu nao trong shadowing",
      "diem phat am cua toi the nao",
      "fluency cua toi trong shadowing ra sao",
      "intonation cua toi co on khong",
      "tu nao can luyen phat am lai",
      "shadowing nay can sua am nao",
      "so sanh phan noi cua toi voi transcript",
      "phan tich loi nghe va noi trong bai nay",
      "bai nghe nay toi nen luyen lai doan nao",
      "toi nghe nham tu nao trong attempt nay",
      "dictation attempt nay can cai thien gi",
      "shadowing attempt nay can cai thien gi",
      "transcript cua toi sai khac cho nao",
      "phan tich listening practice vua lam",
      "goi y cach sua loi dictation nay",
      "goi y cach sua loi shadowing nay",
      "toi nen tap nghe lai timestamp nao",
      "cau nao trong bai listening nay can replay de sua loi",
    ],
    hardNegatives: [
      "meo lam part 3",
      "lam sao tang diem listening",
      "mo bai dictation",
    ],
  },
  {
    id: "app_navigation_support",
    intentId: "app.navigation_support",
    lane: "SYSTEM",
    engine: "ACTION",
    availability: "ACTION_ONLY",
    semanticSearchEnabled: true,
    contextType: "app_navigation",
    contextPolicy: { onMissing: "SAFE_FALLBACK" },
    priority: 78,
    examples: [
      "lam bai test o dau",
      "xem cau sai o dau",
      "cho toi xem cau sai",
      "mo man hinh luyen tap",
      "mo trang lam de",
      "nut xem ket qua nam o dau",
      "toi muon vao phan review cau sai",
      "mo lai trang ket qua test",
      "huong dan cach bat dau bai test",
      "lam sao de xem dap an dung",
      "toi khong biet mo bai hoc o dau",
      "chi toi cach vao study calendar",
      "trang luyen skill nam o dau",
      "mo phan practice skill",
      "chuyen toi man hinh review mistakes",
      "toi muon quay lai dashboard",
      "huong dan thao tac trong app",
    ],
    hardNegatives: [
      "audio khong chay",
      "tien do cua toi the nao",
      "phan tich bai test nay",
    ],
  },
];

function normalizeIntentExample(value = "") {
  return value
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/\u0111/g, "d")
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function mergeExtraPositiveExamples(
  catalog: RawIntentCatalogEntry[]
): RawIntentCatalogEntry[] {
  const searchableIntentIds = new Set(
    catalog
      .filter(
        (entry) =>
          entry.semanticSearchEnabled && entry.availability !== "DISABLED"
      )
      .map((entry) => entry.intentId)
  );
  const extraIntentIds = new Set(
    Object.keys(CHAT_INTENT_EXTRA_POSITIVE_EXAMPLES) as ChatIntent[]
  );
  const missingExtra = [...searchableIntentIds].filter(
    (intentId) => !extraIntentIds.has(intentId)
  );
  const unknownExtra = [...extraIntentIds].filter(
    (intentId) => !searchableIntentIds.has(intentId)
  );
  if (missingExtra.length || unknownExtra.length) {
    throw new Error(
      `Chat intent extra examples mismatch. Missing: ${missingExtra.join(", ") || "none"}; unknown: ${unknownExtra.join(", ") || "none"}`
    );
  }

  const seen = new Set<string>();
  for (const entry of catalog) {
    if (!searchableIntentIds.has(entry.intentId)) continue;
    for (const example of [...entry.hardNegatives, ...entry.examples]) {
      const key = normalizeIntentExample(example);
      if (key) seen.add(key);
    }
  }

  return catalog.map((entry) => {
    if (
      !entry.semanticSearchEnabled ||
      entry.availability === "DISABLED"
    ) {
      return entry;
    }

    const additions: string[] = [];
    for (const example of CHAT_INTENT_EXTRA_POSITIVE_EXAMPLES[entry.intentId] ?? []) {
      const key = normalizeIntentExample(example);
      if (!key || seen.has(key)) continue;
      seen.add(key);
      additions.push(example);
    }

    return {
      ...entry,
      examples: [...entry.examples, ...additions],
    };
  });
}

const MERGED_CHAT_INTENT_EXAMPLES = mergeExtraPositiveExamples(
  RAW_CHAT_INTENT_EXAMPLES
);

export const CHAT_INTENT_EXAMPLES: IntentCatalogEntry[] = MERGED_CHAT_INTENT_EXAMPLES.map((entry) => ({
  ...entry,
  ...(INTENT_SIGNAL_METADATA[entry.intentId] ?? DEFAULT_SIGNAL_METADATA),
}));

export function validateIntentCatalog(
  catalog: IntentCatalogEntry[] = CHAT_INTENT_EXAMPLES
) {
  const ids = new Set<string>();
  const intentIds = new Set<string>();

  for (const entry of catalog) {
    if (ids.has(entry.id)) throw new Error(`Duplicate intent catalog id: ${entry.id}`);
    if (intentIds.has(entry.intentId)) {
      throw new Error(`Duplicate intentId in catalog: ${entry.intentId}`);
    }
    ids.add(entry.id);
    intentIds.add(entry.intentId);

    if (entry.availability === "DISABLED" && entry.semanticSearchEnabled) {
      throw new Error(`Disabled intent cannot be indexed: ${entry.intentId}`);
    }
    if (entry.availability === "ACTIVE" && !entry.semanticSearchEnabled) {
      throw new Error(`Active intent must be searchable or marked DISABLED: ${entry.intentId}`);
    }
    if (entry.availability === "ACTION_ONLY" && entry.engine !== "ACTION") {
      throw new Error(`ACTION_ONLY intent must use ACTION engine: ${entry.intentId}`);
    }
    if (entry.semanticSearchEnabled && entry.examples.length === 0) {
      throw new Error(`Semantic intent requires positive examples: ${entry.intentId}`);
    }
    if (!entry.entities.length || !entry.actions.length) {
      throw new Error(`Intent signal metadata is required: ${entry.intentId}`);
    }
    if (
      entry.lane === "CONTEXTUAL" &&
      entry.contextPolicy.auth &&
      !["CLARIFY", "SAFE_FALLBACK"].includes(entry.contextPolicy.onMissing)
    ) {
      throw new Error(`Personal contextual intent cannot fall through to AI: ${entry.intentId}`);
    }
  }

  return catalog;
}

export function getChatIntentCatalogStats(
  catalog: IntentCatalogEntry[] = CHAT_INTENT_EXAMPLES
) {
  const searchable = catalog.filter(
    (entry) => entry.semanticSearchEnabled && entry.availability !== "DISABLED"
  );
  return {
    catalogVersion: CHAT_INTENT_CATALOG_VERSION,
    searchableIntentCount: searchable.length,
    searchableExampleCount: searchable.reduce((count, entry) => count + entry.examples.length, 0),
    disabledIntentCount: catalog.filter((entry) => entry.availability === "DISABLED").length,
    totalIntentCount: catalog.length,
  };
}

export function getIntentCatalogEntry(intentId: ChatIntent) {
  return CHAT_INTENT_EXAMPLES.find((entry) => entry.intentId === intentId);
}

export function getIntentSignalMetadata(intentId: ChatIntent) {
  return getIntentCatalogEntry(intentId);
}
