import { ChatIntent, IntentAvailability, IntentLane } from "../types/chat.types";

export type IntentEngine =
  | "TEMPLATE"
  | "ACTION"
  | "DB_FIRST"
  | "DB_FIRST_AI"
  | "GENERAL_AI";

export type ContextPolicy = {
  auth?: boolean;
  allOf?: string[];
  anyOf?: string[];
  onMissing: "CLARIFY" | "SAFE_FALLBACK";
};

export type IntentCatalogEntry = {
  id: string;
  intentId: ChatIntent;
  lane: IntentLane;
  engine: IntentEngine;
  availability: IntentAvailability;
  semanticSearchEnabled: boolean;
  contextType: string;
  contextPolicy: ContextPolicy;
  priority: number;
  examples: string[];
  hardNegatives: string[];
};

export const CHAT_INTENT_COLLECTION = "chat_intent_examples";
export const CHAT_INTENT_CATALOG_VERSION = 4;

export const CHAT_INTENT_EXAMPLES: IntentCatalogEntry[] = [
  {
    id: "smalltalk_greeting_feedback",
    intentId: "smalltalk.greeting_feedback",
    lane: "SYSTEM",
    engine: "TEMPLATE",
    availability: "ACTIVE",
    semanticSearchEnabled: false,
    contextType: "template",
    contextPolicy: { onMissing: "SAFE_FALLBACK" },
    priority: 80,
    examples: [
      "xin chao",
      "chao ban",
      "hello",
      "hi",
      "hey",
      "alo",
      "co ai o do khong",
      "bat dau hoc nao",
      "minh can hoi nhanh",
      "ban giup minh voi",
      "cam on ban",
      "cam on nhe",
      "thanks",
      "thank you",
      "ok",
      "oke",
      "duoc roi",
      "minh hieu roi",
      "ro roi",
      "ngon roi",
      "hoc kho qua",
      "chan qua",
      "toi chan qua",
      "met qua",
      "buon ngu qua",
      "hom nay hoc met qua",
      "nan qua",
      "kho qua",
      "toi nan qua",
      "minh hoi met",
      "hom nay hoc hoi duoi",
      "minh dang bi roi",
      "dong vien minh chut di",
      "toi thay TOEIC kho qua",
      "minh quay lai hoc tiep day",
      "bat dau tiep nhe",
      "xin loi minh hoi nham",
    ],
    hardNegatives: [
      "toi yeu phan nao",
      "giai thich cau nay",
      "meo lam part 5",
    ],
  },
  {
    id: "user_progress_summary",
    intentId: "user_progress.summary",
    lane: "CONTEXTUAL",
    engine: "DB_FIRST",
    availability: "ACTIVE",
    semanticSearchEnabled: true,
    contextType: "user_progress",
    contextPolicy: { auth: true, onMissing: "SAFE_FALLBACK" },
    priority: 85,
    examples: [
      "tien do hoc cua toi the nao",
      "tong quan tien do cua toi ra sao",
      "toi dang hoc duoc bao nhieu phan tram",
      "toi da hoan thanh bao nhieu bai",
      "muc tieu diem cua toi la bao nhieu",
      "diem hien tai cua toi la bao nhieu",
      "target TOEIC cua toi con xa khong",
      "toi dang o trinh do nao",
      "toi tien bo nhanh hay cham",
      "toc do hoc cua toi co on khong",
      "streak hoc cua toi hien tai la may ngay",
      "chuoi ngay hoc cua toi con khong",
      "tong thoi gian hoc cua toi la bao nhieu",
      "toi hoc co deu khong",
      "diem manh cua toi la gi",
      "toi co dang theo kip muc tieu khong",
      "toi con thieu bao nhieu diem de dat target",
      "trang thai hoc tap cua toi hien tai ra sao",
      "toi co bo hoc nhieu khong",
      "ban tong hop tien do hoc tap cua toi di",
    ],
    hardNegatives: [
      "bai test nay toi yeu phan nao",
      "de gan nhat cua toi the nao",
      "phan tich de gan nhat cua toi",
      "bai test vua lam cua toi ra sao",
      "bai nay toi sai phan nao",
      "buoc tiep theo trong roadmap la gi",
      "meo tang diem reading",
    ],
  },
  {
    id: "test_attempt_analysis",
    intentId: "test_attempt.analysis",
    lane: "CONTEXTUAL",
    engine: "DB_FIRST_AI",
    availability: "ACTIVE",
    semanticSearchEnabled: true,
    contextType: "test_attempt_summary",
    contextPolicy: { auth: true, onMissing: "CLARIFY" },
    priority: 90,
    examples: [
      "phan tich bai test nay",
      "phan tich ket qua bai test nay",
      "xem giup minh bai test vua lam",
      "bai test nay toi lam the nao",
      "bai test nay diem yeu cua toi la gi",
      "bai test nay toi yeu phan nao",
      "trong bai test nay toi sai nhieu part nao",
      "part nao trong bai nay sai nhieu nhat",
      "nhung loi sai chinh trong bai test nay la gi",
      "toi nen sua loi nao truoc trong bai test nay",
      "hay tong ket bai lam nay",
      "ket qua attempt nay noi len dieu gi",
      "phan tich attempt hien tai",
      "bai nay toi mat diem o dau",
      "bai test nay co mau loi nao lap lai khong",
      "nhom loi sai trong ket qua nay la gi",
      "toi can on lai tag nao sau bai test nay",
      "dua tren bai test nay nen luyen phan nao",
      "xem ty le dung sai trong bai test nay",
      "bai lam nay reading yeu hay listening yeu",
      "bai test gan nhat cua toi can phan tich",
      "phan tich bai test gan nhat",
      "de gan nhat cua toi the nao",
      "phan tich de gan nhat cua toi",
      "de moi nhat cua toi ra sao",
      "bai nay toi sai phan nao",
      "de thi gan nhat cua toi the nao",
      "phan tich de thi gan nhat cua toi",
      "de gan nhat toi sai chu yeu o dau",
      "de moi nhat toi sai nhieu phan nao",
      "ket qua bai test gan nhat cua toi the nao",
      "bai thi gan nhat cua toi the nao",
      "ket qua bai thi gan nhat ra sao",
      "bai lam gan nhat cua toi the nao",
      "bai test vua lam cua toi ra sao",
      "phan tich bai thi gan nhat",
      "bai thi gan nhat toi sai phan nao",
      "diem bai thi gan nhat noi len dieu gi",
      "review bai thi vua nop",
      "review diem bai test vua nop",
      "toi sai bao nhieu cau trong bai nay",
      "bai test nay co cau sai nao can xem truoc",
      "hay chi ra uu tien sua loi trong attempt nay",
      "toi muon xem bao cao cua bai test nay",
      "phan tich phan sai trong ket qua test nay",
      "bai thi thu nay cho thay toi can hoc gi",
    ],
    hardNegatives: [
      "tien do hoc cua toi the nao",
      "nang luc cua toi the nao",
      "tien do hoc cua toi ra sao",
      "tong quan tien do cua toi",
      "giai thich cau nay",
      "meo lam bai test toeic",
    ],
  },
  {
    id: "question_explain_specific",
    intentId: "question.explain_specific",
    lane: "CONTEXTUAL",
    engine: "DB_FIRST_AI",
    availability: "ACTIVE",
    semanticSearchEnabled: true,
    contextType: "quick_question",
    contextPolicy: {
      auth: true,
      allOf: ["questionId", "attemptId"],
      onMissing: "CLARIFY",
    },
    priority: 95,
    examples: [
      "sao toi sai cau nay",
      "vi sao dap an la C",
      "tai sao dap an dung la B",
      "sao A sai ma C dung",
      "giai thich cau nay",
      "giai thich cau so 5",
      "giai thich nhanh cau nay",
      "cau nay lam nhu the nao",
      "dap an nay tai sao dung",
      "vi sao lua chon cua toi sai",
      "tai sao khong chon A",
      "tai sao phai chon D",
      "cach suy luan cau nay la gi",
      "huong dan cach lam cau nay",
      "phan tich dap an dung sai cua cau nay",
      "cau nay can chu y diem nao",
      "loi sai cua toi o cau nay la gi",
      "toi bi sai o dau trong cau nay",
      "cau nay co meo gi de lam khong",
      "tai sao cau nay dung theo dap an he thong",
      "giai thich tung lua chon cua cau nay",
      "so sanh dap an toi chon voi dap an dung",
      "cau nay nen loai dap an nao truoc",
      "tai sao dap an khac khong phu hop",
      "minh khong hieu cau hoi nay",
      "giai thich logic cua cau hoi nay",
      "dap an dung dua vao dau",
      "tai sao cau nay khong phai dap an A",
      "chi minh cach nhan ra dap an dung cau nay",
      "cau hoi nay kiem tra kien thuc gi de ra dap an",
    ],
    hardNegatives: [
      "menh de quan he la gi",
      "phan tich bai test nay",
      "tien do cua toi the nao",
    ],
  },
  {
    id: "question_translate_context",
    intentId: "question.translate_context",
    lane: "CONTEXTUAL",
    engine: "DB_FIRST_AI",
    availability: "ACTIVE",
    semanticSearchEnabled: true,
    contextType: "question_review",
    contextPolicy: {
      auth: true,
      allOf: ["questionId", "attemptId"],
      onMissing: "CLARIFY",
    },
    priority: 88,
    examples: [
      "dich cau nay",
      "dich noi dung cau hoi nay",
      "dich phan de bai nay",
      "dich 4 dap an",
      "dich cac lua chon cua cau nay",
      "dich passage nay",
      "dich doan van nay",
      "dich transcript nay",
      "dich doan nghe nay",
      "cau nay nghia tieng viet la gi",
      "doan nay nghia tieng viet la gi",
      "viet ban dich tieng viet cho cau nay",
      "hay dich nguyen cau hoi",
      "dich ca cau va dap an",
      "dich phan listening script",
      "dich noi dung audio transcript",
      "dich bai doc nay sang tieng viet",
      "dich sentence hien tai",
      "dich option A B C D",
      "cho minh ban dich cua passage",
      "minh muon hieu nghia tieng viet cua doan nay",
      "giai nghia bang tieng viet toan bo cau nay",
      "dich cum trong dap an nay",
      "dich dong transcript dang xem",
      "ban dich cua cau hoi nay la gi",
      "dich phan huong dan trong cau nay",
      "dich noi dung dang hien tren man hinh",
      "chuyen cau nay sang tieng viet",
      "dich cau tieng anh nay cho minh",
      "viet lai nghia tieng viet cua cau hoi",
    ],
    hardNegatives: [
      "affect va effect khac nhau the nao",
      "meo lam part 7",
      "phan tich ket qua bai test",
    ],
  },
  {
    id: "vocabulary_contextual",
    intentId: "vocabulary.contextual",
    lane: "CONTEXTUAL",
    engine: "DB_FIRST_AI",
    availability: "ACTIVE",
    semanticSearchEnabled: true,
    contextType: "question_review",
    contextPolicy: {
      auth: true,
      allOf: ["questionId", "attemptId"],
      onMissing: "CLARIFY",
    },
    priority: 86,
    examples: [
      "awning nghia la gi",
      "pick up nghia la gi",
      "pick up trong cau nay nghia la gi",
      "tu nay nghia la gi",
      "cum tu nay nghia la gi",
      "load voi unload khac gi",
      "cho toi vocab cau nay",
      "liet ke tu vung trong cau nay",
      "tu nao quan trong trong cau nay",
      "giai thich nghia cua tu nay",
      "giai thich cum tu nay",
      "nghia cua word nay la gi",
      "tu nay la danh tu hay dong tu",
      "tu nay trong ngu canh nay co nghia gi",
      "cum nay trong TOEIC hay dung the nao",
      "hay cho vi du ve tu nay",
      "phan biet hai tu nay giup minh",
      "tu nay co dong nghia nao",
      "tu nay trai nghia voi gi",
      "collocation cua tu nay la gi",
      "cach dung tu nay trong cau",
      "tu nay co sac thai nghia gi",
      "keyword tu vung cua cau nay la gi",
      "vocabulary trong passage nay gom gi",
      "cho minh nghia cua cum tu duoc chon",
      "tu duoc highlight co nghia gi",
      "nghia tieng viet cua tu nay la gi",
      "giai thich phrase nay bang tieng viet",
      "tu vung nao lam minh sai cau nay",
      "tu nay trong dap an co nghia gi",
    ],
    hardNegatives: [
      "cach hoc tu vung toeic",
      "affect va effect khac nhau the nao",
      "mo flashcard",
    ],
  },
  {
    id: "grammar_contextual",
    intentId: "grammar.contextual",
    lane: "CONTEXTUAL",
    engine: "DB_FIRST_AI",
    availability: "ACTIVE",
    semanticSearchEnabled: true,
    contextType: "question_review",
    contextPolicy: {
      auth: true,
      allOf: ["questionId", "attemptId"],
      onMissing: "CLARIFY",
    },
    priority: 86,
    examples: [
      "cau nay dung ngu phap gi",
      "ngu phap cua cau nay la gi",
      "cho trong can loai tu gi",
      "vi sao khong dung V-ing",
      "tai sao o day dung danh tu",
      "tai sao o day dung dong tu",
      "phan biet cau truc cau nay",
      "cau truc ngu phap cua cau nay la gi",
      "cho minh phan tich ngu phap cau nay",
      "chu ngu vi ngu trong cau nay la gi",
      "menh de trong cau nay la menh de gi",
      "tai sao dung thi hien tai hoan thanh",
      "tai sao dung bi dong o day",
      "tai sao phai chia dong tu nhu vay",
      "tu loai can dien vao cho trong la gi",
      "dau hieu ngu phap cua cau nay la gi",
      "cau nay kiem tra grammar point nao",
      "phan tich cau truc sau cho trong",
      "vi sao khong dung to V",
      "vi sao dap an la adjective",
      "vi sao can adverb trong cau nay",
      "cau nay lien quan den relative clause khong",
      "cau nay co cau truc song song khong",
      "sau gioi tu phai dung gi trong cau nay",
      "vi sao dung past participle o day",
      "cach nhan biet loai tu trong cau nay",
      "phan tich thanh phan cau giup minh",
      "grammar rule nao ap dung cho cau nay",
      "cau nay sai vi ngu phap nao",
      "tai sao lua chon dung hop ngu phap",
    ],
    hardNegatives: [
      "menh de quan he la gi",
      "cac chu diem ngu phap toeic quan trong",
      "meo lam part 5",
    ],
  },
  {
    id: "toeic_knowledge_general",
    intentId: "toeic_knowledge.general",
    lane: "GENERAL_AI",
    engine: "GENERAL_AI",
    availability: "ACTIVE",
    semanticSearchEnabled: true,
    contextType: "general_rag",
    contextPolicy: { onMissing: "SAFE_FALLBACK" },
    priority: 70,
    examples: [
      "menh de quan he la gi",
      "affect va effect khac nhau the nao",
      "meo lam Part 5",
      "TOEIC co may phan",
      "tu 400 len 600 hoc sao",
      "cach hoc tu vung TOEIC",
      "chien luoc lam Part 7",
      "Part 3 nen nghe nhu the nao",
      "Part 4 co meo gi khong",
      "Part 1 can chu y gi",
      "Part 2 lam sao de bat keyword",
      "cach lam cau incomplete sentences",
      "cach lam text completion TOEIC",
      "cach doc nhanh Part 7",
      "nen hoc grammar TOEIC theo thu tu nao",
      "cac chu diem ngu phap TOEIC quan trong",
      "phan biet much va many",
      "phan biet since va for",
      "cach dung although va despite",
      "cach dung because va because of",
      "collocation TOEIC nen hoc la gi",
      "lam sao tang diem listening",
      "lam sao tang diem reading",
      "mot ngay nen hoc TOEIC bao lau",
      "nguoi moi bat dau TOEIC hoc gi truoc",
      "cach luyen de TOEIC hieu qua",
      "chien luoc phan bo thoi gian TOEIC",
      "lam sao tranh bay trong Part 5",
      "tu vung TOEIC ve van phong gom gi",
      "cach ghi nho tu vung TOEIC lau hon",
    ],
    hardNegatives: [
      "giai thich cau nay",
      "tien do cua toi the nao",
      "phan tich bai test vua lam",
    ],
  },
  {
    id: "roadmap_guidance",
    intentId: "roadmap.guidance",
    lane: "CONTEXTUAL",
    engine: "ACTION",
    availability: "ACTION_ONLY",
    semanticSearchEnabled: true,
    contextType: "roadmap",
    contextPolicy: { auth: true, onMissing: "SAFE_FALLBACK" },
    priority: 82,
    examples: [
      "mo roadmap",
      "mo lo trinh",
      "di den roadmap",
      "cho toi xem trang roadmap",
      "mo phan ke hoach hoc",
      "di den lo trinh hoc",
    ],
    hardNegatives: [
      "roadmap cua toi toi dau roi",
      "vi sao roadmap chon bai nay",
      "tien do hoc cua toi the nao",
    ],
  },
  {
    id: "roadmap_summary",
    intentId: "roadmap.summary",
    lane: "CONTEXTUAL",
    engine: "DB_FIRST",
    availability: "ACTIVE",
    semanticSearchEnabled: true,
    contextType: "roadmap_summary",
    contextPolicy: { auth: true, onMissing: "SAFE_FALLBACK" },
    priority: 90,
    examples: [
      "lo trinh cua toi the nao",
      "roadmap cua toi toi dau roi",
      "lo trinh hien tai ra sao",
      "toi da hoan thanh bao nhieu lo trinh",
      "tien do roadmap cua toi",
    ],
    hardNegatives: [
      "mo lo trinh",
      "hom nay toi nen hoc gi",
      "tai sao he thong chon bai nay",
    ],
  },
  {
    id: "roadmap_next_step",
    intentId: "roadmap.next_step",
    lane: "CONTEXTUAL",
    engine: "DB_FIRST",
    availability: "ACTIVE",
    semanticSearchEnabled: true,
    contextType: "roadmap_next_step",
    contextPolicy: { auth: true, onMissing: "SAFE_FALLBACK" },
    priority: 91,
    examples: [
      "hom nay toi nen hoc gi",
      "buoc tiep theo la gi",
      "toi nen hoc gi tiep theo",
      "roadmap giao bai gi tiep theo",
      "tiep theo toi can lam gi",
    ],
    hardNegatives: [
      "mo roadmap",
      "lo trinh cua toi the nao",
      "tai sao he thong chon bai nay",
    ],
  },
  {
    id: "roadmap_explain_recommendation",
    intentId: "roadmap.explain_recommendation",
    lane: "CONTEXTUAL",
    engine: "DB_FIRST_AI",
    availability: "ACTIVE",
    semanticSearchEnabled: true,
    contextType: "roadmap_recommendation",
    contextPolicy: { auth: true, onMissing: "SAFE_FALLBACK" },
    priority: 92,
    examples: [
      "tai sao he thong chon bai nay",
      "vi sao roadmap de xuat bai nay",
      "ly do toi phai hoc buoc nay",
      "tai sao bai nay duoc xep tiep theo",
      "giai thich de xuat hoc tap nay",
    ],
    hardNegatives: [
      "mo roadmap",
      "lo trinh cua toi toi dau roi",
      "doi lo trinh",
    ],
  },
  {
    id: "roadmap_adjust",
    intentId: "roadmap.adjust",
    lane: "CONTEXTUAL",
    engine: "ACTION",
    availability: "ACTION_ONLY",
    semanticSearchEnabled: true,
    contextType: "roadmap_adjust",
    contextPolicy: { auth: true, onMissing: "SAFE_FALLBACK" },
    priority: 89,
    examples: [
      "doi lo trinh",
      "chinh lo trinh hoc",
      "giam khoi luong hoc",
      "tang thoi gian hoc moi ngay",
      "cap nhat ke hoach hoc",
    ],
    hardNegatives: [
      "mo lo trinh",
      "lo trinh cua toi the nao",
      "hom nay toi nen hoc gi",
    ],
  },
  {
    id: "flashcard_personal",
    intentId: "flashcard.personal",
    lane: "CONTEXTUAL",
    engine: "ACTION",
    availability: "ACTION_ONLY",
    semanticSearchEnabled: true,
    contextType: "flashcard",
    contextPolicy: { auth: true, onMissing: "SAFE_FALLBACK" },
    priority: 82,
    examples: [
      "mo flashcard",
      "di den flashcard",
      "cho toi vao phan on flashcard",
      "mo trang on tu",
      "toi muon mo bo flashcard",
      "chuyen toi trang flashcard",
    ],
    hardNegatives: [
      "toi co bao nhieu flashcard can on",
      "tu nao toi hay quen nhat",
      "cach hoc tu vung toeic",
    ],
  },
  {
    id: "listening_practice_analysis",
    intentId: "listening_practice.analysis",
    lane: "CONTEXTUAL",
    engine: "DB_FIRST_AI",
    availability: "DISABLED",
    semanticSearchEnabled: false,
    contextType: "listening_practice",
    contextPolicy: {
      auth: true,
      anyOf: ["dictationAttemptId", "shadowingAttemptId"],
      onMissing: "CLARIFY",
    },
    priority: 84,
    examples: [
      "bai dictation nay sai o dau",
      "phan tich bai dictation hien tai",
      "toi nghe thieu tu nao trong dictation",
      "so sanh transcript voi cau tra loi cua toi",
      "dictation nay toi bo sot nhung tu nao",
      "loi nghe sai trong bai dictation nay la gi",
      "toi can nghe lai cau nao trong dictation",
      "goi y luyen lai cau nao trong bai nghe nay",
      "phan tich transcript diff cua toi",
      "cau nao toi nghe sai nhieu nhat",
      "bai shadowing nay toi phat am sai tu nao",
      "phan tich bai shadowing hien tai",
      "toi phat am sai tu nao trong shadowing",
      "diem phat am cua toi the nao",
      "fluency cua toi trong shadowing ra sao",
      "intonation cua toi co on khong",
      "tu nao can luyen phat am lai",
      "shadowing nay can sua am nao",
      "so sanh phan noi cua toi voi transcript",
      "phan tich loi nghe va noi trong bai nay",
      "bai nghe nay toi nen luyen lai doan nao",
      "toi nghe nham tu nao trong attempt nay",
      "dictation attempt nay can cai thien gi",
      "shadowing attempt nay can cai thien gi",
      "transcript cua toi sai khac cho nao",
      "phan tich listening practice vua lam",
      "goi y cach sua loi dictation nay",
      "goi y cach sua loi shadowing nay",
      "toi nen tap nghe lai timestamp nao",
      "cau nao trong bai listening nay can replay de sua loi",
    ],
    hardNegatives: [
      "meo lam part 3",
      "lam sao tang diem listening",
      "mo bai dictation",
    ],
  },
  {
    id: "app_navigation_support",
    intentId: "app.navigation_support",
    lane: "SYSTEM",
    engine: "ACTION",
    availability: "ACTION_ONLY",
    semanticSearchEnabled: true,
    contextType: "app_navigation",
    contextPolicy: { onMissing: "SAFE_FALLBACK" },
    priority: 78,
    examples: [
      "lam bai test o dau",
      "xem cau sai o dau",
      "cho toi xem cau sai",
      "mo man hinh luyen tap",
      "mo trang lam de",
      "nut xem ket qua nam o dau",
      "toi muon vao phan review cau sai",
      "mo lai trang ket qua test",
      "huong dan cach bat dau bai test",
      "lam sao de xem dap an dung",
      "toi khong biet mo bai hoc o dau",
      "chi toi cach vao study calendar",
      "trang luyen skill nam o dau",
      "mo phan practice skill",
      "chuyen toi man hinh review mistakes",
      "toi muon quay lai dashboard",
      "huong dan thao tac trong app",
    ],
    hardNegatives: [
      "audio khong chay",
      "tien do cua toi the nao",
      "phan tich bai test nay",
    ],
  },
];

export function validateIntentCatalog(
  catalog: IntentCatalogEntry[] = CHAT_INTENT_EXAMPLES
) {
  const ids = new Set<string>();
  const intentIds = new Set<string>();

  for (const entry of catalog) {
    if (ids.has(entry.id)) throw new Error(`Duplicate intent catalog id: ${entry.id}`);
    if (intentIds.has(entry.intentId)) {
      throw new Error(`Duplicate intentId in catalog: ${entry.intentId}`);
    }
    ids.add(entry.id);
    intentIds.add(entry.intentId);

    if (entry.availability === "DISABLED" && entry.semanticSearchEnabled) {
      throw new Error(`Disabled intent cannot be indexed: ${entry.intentId}`);
    }
    if (entry.availability === "ACTION_ONLY" && entry.engine !== "ACTION") {
      throw new Error(`ACTION_ONLY intent must use ACTION engine: ${entry.intentId}`);
    }
    if (entry.semanticSearchEnabled && entry.examples.length === 0) {
      throw new Error(`Semantic intent requires positive examples: ${entry.intentId}`);
    }
    if (
      entry.lane === "CONTEXTUAL" &&
      entry.contextPolicy.auth &&
      !["CLARIFY", "SAFE_FALLBACK"].includes(entry.contextPolicy.onMissing)
    ) {
      throw new Error(`Personal contextual intent cannot fall through to AI: ${entry.intentId}`);
    }
  }

  return catalog;
}

export function getIntentCatalogEntry(intentId: ChatIntent) {
  return CHAT_INTENT_EXAMPLES.find((entry) => entry.intentId === intentId);
}
