import { ChatIntent } from "../types/chat.types";

export type IntentDifferentiationCategory =
  | "clear"
  | "paraphrase"
  | "noise"
  | "hardNegative";

export type IntentDifferentiationCase = {
  id: string;
  focusIntent: ChatIntent;
  category: IntentDifferentiationCategory;
  input: string;
  expectedIntent: ChatIntent;
  forbiddenIntents?: ChatIntent[];
  notes?: string;
};

type RawPositiveCases = {
  clear: string[];
  paraphrase: string[];
  noise: string[];
};

type RawHardNegativeCase = {
  input: string;
  expectedIntent: ChatIntent;
  notes?: string;
};

type RawIntentDifferentiationGroup = {
  focusIntent: ChatIntent;
  positive: RawPositiveCases;
  hardNegatives: RawHardNegativeCase[];
};

export const INTENT_DIFFERENTIATION_EXPECTED_COUNTS = {
  clear: 10,
  paraphrase: 8,
  noise: 5,
  hardNegative: 8,
} as const;

export const CHAT_INTENT_DIFFERENTIATION_GROUPS: RawIntentDifferentiationGroup[] = [
  {
    focusIntent: "out_of_project.general",
    positive: {
      clear: [
        "Tối nay Sài Gòn có mưa không vậy",
        "Giá đô hôm nay lên hay xuống",
        "Bạn gợi ý quán ăn gần đây được không",
        "Tôi muốn hỏi cách đặt vé tàu đi Nha Trang",
        "Tin công nghệ mới nhất có gì hot",
        "Nên mua điện thoại nào tầm 8 triệu",
        "Viết giúp tôi caption đăng Facebook",
        "Lịch chiếu phim cuối tuần có gì hay",
        "Tư vấn giúp tôi chọn máy ảnh du lịch",
        "Cách nấu mì Ý đơn giản ở nhà",
      ],
      paraphrase: [
        "Ngoài TOEIC ra mình hỏi chuyện thời tiết chút được không",
        "Cho mình hỏi giá vàng đang biến động sao",
        "Bạn biết trận bóng tối qua kết quả thế nào không",
        "Mình cần vài ý tưởng trang trí phòng ngủ",
        "Có mẹo nào chọn laptop học đại học không",
        "Kể mình nghe chuyện vui không liên quan học được không",
        "Bạn viết giùm đoạn quảng cáo bán áo được chứ",
        "Hỏi ké chuyện du lịch Đà Lạt mùa này ổn không",
      ],
      noise: [
        "weather hnay sao",
        "btc price now?",
        "phim moi co j hay",
        "recipe phở quick",
        "laptop 15tr recommend",
      ],
    },
    hardNegatives: [
      {
        input: "TOEIC Reading nên luyện Part 7 trước hay Part 5 trước",
        expectedIntent: "toeic_knowledge.general",
        notes: "In-domain TOEIC study question, not out-of-project.",
      },
      {
        input: "Mình cần xem tiến độ học TOEIC hiện tại",
        expectedIntent: "user_progress.summary",
      },
      {
        input: "Câu TOEIC này dịch sang tiếng Việt giúp mình",
        expectedIntent: "question.translate_context",
      },
      {
        input: "Từ highlighted trong câu này nghĩa là gì",
        expectedIntent: "vocabulary.contextual",
      },
      {
        input: "Mở giúp mình màn hình roadmap học TOEIC",
        expectedIntent: "roadmap.guidance",
      },
      {
        input: "Tạo bộ flashcard TOEIC về chủ đề tuyển dụng",
        expectedIntent: "flashcard.create",
      },
      {
        input: "Phân tích bài test TOEIC mới nộp của mình",
        expectedIntent: "test_attempt.analysis",
      },
      {
        input: "Chỉ mình nút review câu sai nằm chỗ nào",
        expectedIntent: "app.navigation_support",
      },
    ],
  },
  {
    focusIntent: "smalltalk.greeting_feedback",
    positive: {
      clear: [
        "Chào buổi sáng, mình vào học đây",
        "Ê bot ơi, nghe mình hỏi chút",
        "Cảm ơn nha, phần này rõ hơn rồi",
        "Ok vậy mình làm tiếp",
        "Mình hơi đuối, nói chuyện một xíu được không",
        "Xin chào, hôm nay bắt đầu học nhé",
        "Cảm ơn bạn nhiều, đúng thứ mình cần",
        "Mình quay lại rồi, học tiếp thôi",
        "Tạm ổn rồi, thanks bạn",
        "Alo, bạn còn ở đó không",
      ],
      paraphrase: [
        "Hôm nay mình hơi mất động lực",
        "Bạn động viên mình vài câu trước khi học đi",
        "Mình bị rối quá, cho mình bình tĩnh chút",
        "Nãy giờ học mệt thật sự",
        "Được rồi, mình hiểu ý bạn rồi",
        "Cảm giác TOEIC khó ghê",
        "Mình cần bạn đồng hành học chút",
        "Hello, mình chuẩn bị hỏi bài nè",
      ],
      noise: [
        "hi bottt",
        "helooo",
        "oke nha",
        "thanks bro",
        "mệt quáaa",
      ],
    },
    hardNegatives: [
      { input: "Mình yếu kỹ năng nào nhất trong TOEIC", expectedIntent: "user_progress.ability_map" },
      { input: "Cảm ơn, nhưng phân tích luôn bài test vừa rồi cho mình", expectedIntent: "test_attempt.analysis" },
      { input: "Hello, mở trang flashcard cá nhân giúp mình", expectedIntent: "flashcard.personal" },
      { input: "Ok rồi, giờ tạo 12 flashcard về hợp đồng", expectedIntent: "flashcard.create" },
      { input: "Bạn ơi dịch đoạn passage hiện tại sang tiếng Việt", expectedIntent: "question.translate_context" },
      { input: "Mệt quá, hôm nay roadmap bắt mình học gì tiếp", expectedIntent: "roadmap.next_step" },
      { input: "Thanks, chỉ mình vào trang làm đề ở đâu", expectedIntent: "app.navigation_support" },
      { input: "Chào, TOEIC Part 2 thường bẫy kiểu gì", expectedIntent: "toeic_knowledge.general" },
    ],
  },
  {
    focusIntent: "user_profile.identity",
    positive: {
      clear: [
        "toi la ai",
        "toi la ai tren he thong",
        "thong tin ca nhan cua toi",
        "thong tin account cua toi",
        "email dang dang nhap la gi",
        "ten hien thi cua toi la gi",
        "toi dang dung tai khoan nao",
        "profile cua toi co gi",
        "ho so cua toi tren he thong",
        "ban dang biet gi ve toi",
      ],
      paraphrase: [
        "he thong dang nhan toi la user nao",
        "cho toi xem ho so tai khoan hien tai",
        "tai khoan nay dang la cua ai",
        "ban co thong tin nao ve account cua toi",
        "email nao dang gan voi tai khoan nay",
        "tom tat profile dang dang nhap",
        "cho minh biet ten va email cua minh",
        "nguoi dung hien tai la ai",
      ],
      noise: [
        "profile toi?",
        "account nao day",
        "email login?",
        "toi la ai app nay",
        "user hien tai?",
      ],
    },
    hardNegatives: [
      { input: "toi la ai trong cuoc doi nay", expectedIntent: "smalltalk.greeting_feedback" },
      { input: "toi la ai tren doi nay", expectedIntent: "smalltalk.greeting_feedback" },
      { input: "ban nghi toi la nguoi nhu the nao", expectedIntent: "smalltalk.greeting_feedback" },
      { input: "toi yeu phan nao", expectedIntent: "user_progress.summary" },
      { input: "tien do cua toi", expectedIntent: "user_progress.summary" },
      { input: "diem gan nhat cua toi", expectedIntent: "test_attempt.analysis" },
      { input: "lo trinh cua toi", expectedIntent: "roadmap.summary" },
      { input: "doi mat khau", expectedIntent: "app.navigation_support" },
    ],
  },
  {
    focusIntent: "lesson.recommendation",
    positive: {
      clear: [
        "goi y bai hoc part 5",
        "cho toi bai luyen part 7",
        "tim lesson part 3",
        "goi y bai hoc menh de quan he",
        "bai hoc ve tu loai",
        "bai luyen dang suy luan",
        "goi y bai hoc part 5 menh de quan he",
        "goi y bai hoc part 7 dang suy luan",
        "recommend lesson relative clause",
        "suggest part 7 inference lessons",
      ],
      paraphrase: [
        "cho minh vai activity part 6 dung trinh do",
        "tim bai hoc phu hop ve gioi tu",
        "de xuat unit part 4 ve chi tiet",
        "goi y lesson reading ve main idea",
        "tim bai luyen listening part 3",
        "cho toi 3 bai hoc ve cau bi dong",
        "suggest grammar activities for part 5",
        "recommend unit about business email",
      ],
      noise: [
        "lesson part 5 recommend",
        "goi y unit suy luan",
        "bai hoc relative clause",
        "suggest activity part 7 inference",
        "tim lesson tu loai",
      ],
    },
    hardNegatives: [
      { input: "hom nay hoc gi", expectedIntent: "roadmap.next_step" },
      { input: "goi y bai hoc tiep theo cho toi", expectedIntent: "roadmap.next_step" },
      { input: "hoc gi theo lo trinh", expectedIntent: "roadmap.next_step" },
      { input: "menh de quan he la gi", expectedIntent: "toeic_knowledge.general" },
      { input: "cach lam part 7", expectedIntent: "toeic_knowledge.general" },
      { input: "luyen cau tuong tu cau nay", expectedIntent: "question.similar_practice" },
      { input: "tao flashcard tu cau nay", expectedIntent: "flashcard.create" },
      { input: "liet ke tu vung trong cau nay", expectedIntent: "vocabulary.contextual" },
    ],
  },
  {
    focusIntent: "user_progress.summary",
    positive: {
      clear: [
        "Cho mình xem tổng quan học tập tuần này",
        "Mình đang tiến bộ được bao nhiêu rồi",
        "Tình hình học TOEIC của mình hiện tại ổn không",
        "Tổng kết giúp mình quá trình học gần đây",
        "Mình còn cách mục tiêu điểm bao xa",
        "Tháng này mình học đều không",
        "Tổng số bài mình đã hoàn thành là bao nhiêu",
        "Bạn xem giúp mình trạng thái học tập chung",
        "Mình có đang theo kịp kế hoạch điểm không",
        "Báo cáo nhanh tiến trình học của mình đi",
      ],
      paraphrase: [
        "Dạo này mình học có lên không vậy",
        "Nhìn chung profile học của mình đang thế nào",
        "Bạn tóm tắt tình hình TOEIC cá nhân cho mình",
        "Mình muốn biết bức tranh tổng thể việc học",
        "Hành trình học của mình đang đi đúng hướng chứ",
        "Mấy hôm nay mình chăm học hơn chưa",
        "Cho mình một cái recap tiến độ cá nhân",
        "Mình cần biết tổng quan trước khi học tiếp",
      ],
      noise: [
        "my progress sao r",
        "tiến độ ntn",
        "hoc dc bn roi",
        "progress check pls",
        "target còn xa ko",
      ],
    },
    hardNegatives: [
      { input: "Kỹ năng Listening hay Reading của mình đang yếu hơn", expectedIntent: "user_progress.ability_map" },
      { input: "Bài test vừa nộp cho thấy mình sai nhóm câu nào", expectedIntent: "test_attempt.analysis" },
      { input: "Roadmap của mình đang ở giai đoạn nào", expectedIntent: "roadmap.summary" },
      { input: "Hôm nay hệ thống muốn mình học bài nào tiếp", expectedIntent: "roadmap.next_step" },
      { input: "Mở trang tiến độ học ở đâu trong app", expectedIntent: "app.navigation_support" },
      { input: "TOEIC 650 cần học bao lâu nếu mới bắt đầu", expectedIntent: "toeic_knowledge.general" },
      { input: "Câu hiện tại mình sai do ngữ pháp gì", expectedIntent: "grammar.contextual" },
      { input: "Tạo flashcard từ các từ mình hay sai", expectedIntent: "flashcard.create" },
    ],
  },
  {
    focusIntent: "user_progress.ability_map",
    positive: {
      clear: [
        "Bản đồ năng lực TOEIC của mình đang ra sao",
        "Phân tích mạnh yếu từng kỹ năng cho mình",
        "Mình đang yếu Part nào nhất",
        "Kỹ năng nghe đọc của mình lệch nhau nhiều không",
        "Bạn đánh giá level TOEIC hiện tại của mình đi",
        "Part nào mình đang làm ổn nhất",
        "Mình cần biết điểm yếu theo từng phần thi",
        "Cho mình xem năng lực từng Part 1 đến 7",
        "Ước lượng trình độ hiện tại của mình dựa trên dữ liệu học",
        "Kỹ năng nào đang kéo điểm mình xuống",
      ],
      paraphrase: [
        "Nhìn năng lực của mình thì phần nào đáng lo",
        "Mình mạnh phần nào yếu phần nào nói rõ giúp",
        "Bạn đọc giúp bản đồ skill TOEIC của mình",
        "Có part nào mình tụt rõ không",
        "Level hiện giờ của mình nghiêng về listening hay reading",
        "Mình muốn biết profile năng lực chi tiết hơn",
        "Đánh giá năng lực theo skill cho mình nhé",
        "Phần thi nào đang là lỗ hổng lớn nhất của mình",
      ],
      noise: [
        "ability map coi",
        "skill nao weak",
        "level toeic now?",
        "part yếu nhất?",
        "reading/listening sao",
      ],
    },
    hardNegatives: [
      { input: "Tổng quan tháng này mình đã học được bao nhiêu phần trăm", expectedIntent: "user_progress.summary" },
      { input: "Bài test mới nhất mình sai nhiều ở đâu", expectedIntent: "test_attempt.analysis" },
      { input: "Roadmap hiện tại của mình còn mấy bước", expectedIntent: "roadmap.summary" },
      { input: "Tại sao roadmap chọn bài Listening này", expectedIntent: "roadmap.explain_recommendation" },
      { input: "Câu này kiểm tra cấu trúc ngữ pháp nào", expectedIntent: "grammar.contextual" },
      { input: "Chiến lược tăng điểm Reading trong TOEIC là gì", expectedIntent: "toeic_knowledge.general" },
      { input: "Xem kết quả bài làm ở màn hình nào", expectedIntent: "app.navigation_support" },
      { input: "Tạo 20 flashcard chủ đề workplace", expectedIntent: "flashcard.create" },
    ],
  },
  {
    focusIntent: "test_attempt.analysis",
    positive: {
      clear: [
        "Bạn review kỹ bài test mình vừa nộp đi",
        "Kết quả lần làm đề mới nhất nói lên điều gì",
        "Phân tích những lỗi chính trong attempt này",
        "Bài thi vừa rồi mình mất điểm ở dạng nào",
        "Cho mình báo cáo chi tiết bài làm hiện tại",
        "Lần test gần đây mình yếu phần nào",
        "Tóm tắt lỗi sai của bài test này giúp mình",
        "Mình muốn biết vì sao điểm bài vừa rồi thấp",
        "Bài làm mới nhất có pattern lỗi nào lặp lại",
        "Xem giúp mình phần sai nhiều nhất trong test vừa rồi",
      ],
      paraphrase: [
        "Nhìn bài mới nộp thì mình nên sửa gì trước",
        "Bạn bóc tách kết quả test này cho mình",
        "Attempt gần nhất có vấn đề chính ở đâu",
        "Đề vừa làm phản ánh điểm yếu gì",
        "Mình cần review hậu kiểm bài thi thử này",
        "Bài đó mình rớt điểm vì nhóm câu nào",
        "Cho mình biết các lỗi đáng chú ý trong lần làm vừa rồi",
        "Kết quả test này nên hiểu thế nào",
      ],
      noise: [
        "review attempt pls",
        "bai vua lam sao",
        "latest test analyze",
        "đề mới sai j",
        "test result breakdown",
      ],
    },
    hardNegatives: [
      { input: "Tổng quan tiến độ học tháng này của mình thế nào", expectedIntent: "user_progress.summary" },
      { input: "Bản đồ kỹ năng của mình yếu Part nào", expectedIntent: "user_progress.ability_map" },
      { input: "Câu này tại sao đáp án B đúng", expectedIntent: "question.explain_specific" },
      { input: "Dịch đoạn transcript hiện tại giúp mình", expectedIntent: "question.translate_context" },
      { input: "Keyword chính trong câu hiện tại nên hiểu thế nào", expectedIntent: "vocabulary.contextual" },
      { input: "Hôm nay trong roadmap mình cần học gì", expectedIntent: "roadmap.next_step" },
      { input: "Mở lại trang kết quả bài test ở đâu", expectedIntent: "app.navigation_support" },
      { input: "Cách phân bổ thời gian khi làm đề TOEIC", expectedIntent: "toeic_knowledge.general" },
    ],
  },
  {
    focusIntent: "question.explain_specific",
    positive: {
      clear: [
        "Giải thích giúp mình vì sao câu này chọn đáp án D",
        "Câu hiện tại sai ở bước suy luận nào",
        "Bạn phân tích từng lựa chọn của câu này đi",
        "Tại sao phương án mình chọn lại không đúng",
        "Đáp án đúng của câu này dựa vào chi tiết nào",
        "Mình chưa hiểu logic chọn đáp án ở câu này",
        "Chỉ mình cách loại đáp án sai trong câu hiện tại",
        "Câu này có bẫy gì khiến mình nhầm không",
        "Vì sao hệ thống không chấp nhận lựa chọn A",
        "Hướng dẫn mình làm lại câu này từ đầu",
      ],
      paraphrase: [
        "Câu này nghĩ kiểu gì mới ra đáp án vậy",
        "Bạn nói dễ hiểu hơn phần đáp án câu này được không",
        "Mình bị kẹt ở câu đang xem, giải thích giùm",
        "Lý do chọn option đúng là gì",
        "Đọc câu này xong mình không biết vì sao sai",
        "Bạn breakdown đáp án câu hiện tại nhé",
        "Câu này nên nhìn dấu hiệu nào trước",
        "Mình muốn hiểu vì sao đáp án kia hợp lý hơn",
      ],
      noise: [
        "why B correct",
        "explain q này",
        "sao sai z",
        "dap an D why",
        "logic câu?",
      ],
    },
    hardNegatives: [
      { input: "Dịch toàn bộ câu hỏi và bốn lựa chọn sang tiếng Việt", expectedIntent: "question.translate_context" },
      { input: "Từ highlighted trong câu này có sắc thái nghĩa gì", expectedIntent: "vocabulary.contextual" },
      { input: "Chỗ trống này cần danh từ hay trạng từ", expectedIntent: "grammar.contextual" },
      { input: "Cho thêm vài câu cùng dạng để mình luyện", expectedIntent: "question.similar_practice" },
      { input: "Relative clause trong TOEIC dùng thế nào", expectedIntent: "toeic_knowledge.general" },
      { input: "Phân tích bài test vừa rồi của mình", expectedIntent: "test_attempt.analysis" },
      { input: "Mở màn hình review câu sai giúp mình", expectedIntent: "app.navigation_support" },
      { input: "Tạo flashcard từ từ vựng của câu này", expectedIntent: "flashcard.create" },
    ],
  },
  {
    focusIntent: "question.translate_context",
    positive: {
      clear: [
        "Chuyển câu hỏi hiện tại sang tiếng Việt giúp mình",
        "Dịch cả đoạn passage đang xem cho mình",
        "Cho mình bản tiếng Việt của bốn đáp án",
        "Đoạn transcript này nghĩa tiếng Việt là gì",
        "Dịch phần đề bài và lựa chọn trong câu này",
        "Bạn dịch nguyên câu hiện tại thật sát nghĩa nhé",
        "Mình muốn đọc bản dịch tiếng Việt của câu này",
        "Dịch đoạn audio script đang mở giúp mình",
        "Câu này nếu hiểu bằng tiếng Việt thì là gì",
        "Viết lại nội dung câu hỏi này bằng tiếng Việt",
      ],
      paraphrase: [
        "Mình không cần giải thích, chỉ cần bản dịch câu này",
        "Bạn chuyển nghĩa đoạn đang xem sang tiếng Việt thôi",
        "Cho mình hiểu passage này bằng tiếng Việt",
        "Dịch nhanh option C và D giúp mình",
        "Nội dung câu này nói gì nếu dịch thẳng",
        "Mình muốn xem nghĩa tiếng Việt của câu hỏi",
        "Bạn dịch transcript hiện tại theo ngữ cảnh nha",
        "Làm bản dịch dễ đọc cho đoạn này",
      ],
      noise: [
        "translate this",
        "dịch q này",
        "meaning VN pls",
        "passage vietsub",
        "dịch option B",
      ],
    },
    hardNegatives: [
      { input: "Giải thích vì sao đáp án C đúng ở câu này", expectedIntent: "question.explain_specific" },
      { input: "Từ này trong ngữ cảnh đang xem nghĩa là gì", expectedIntent: "vocabulary.contextual" },
      { input: "Câu này dùng thì gì để chia động từ", expectedIntent: "grammar.contextual" },
      { input: "Tạo thêm bài luyện giống câu đang xem", expectedIntent: "question.similar_practice" },
      { input: "Cách dịch Part 7 nhanh khi làm TOEIC", expectedIntent: "toeic_knowledge.general" },
      { input: "Phân tích lỗi sai trong bài test vừa nộp", expectedIntent: "test_attempt.analysis" },
      { input: "Gom các từ khó của câu này thành deck để học", expectedIntent: "flashcard.create" },
      { input: "Mở lại trang review bài làm ở đâu", expectedIntent: "app.navigation_support" },
    ],
  },
  {
    focusIntent: "question.similar_practice",
    positive: {
      clear: [
        "Cho mình luyện thêm câu cùng dạng với câu này",
        "Tìm vài bài tương tự để mình sửa lỗi này",
        "Có câu nào giống cấu trúc hiện tại không",
        "Gợi ý bài tập liên quan đến tag của câu này",
        "Mình muốn làm thêm dạng câu vừa sai",
        "Tạo danh sách câu luyện tương tự câu hiện tại",
        "Cho mình bài practice cùng bẫy ngữ pháp này",
        "Tìm nội dung luyện lại đúng kỹ năng của câu này",
        "Đề xuất vài câu cùng chủ điểm để ôn lại",
        "Mình cần bài bổ trợ cho lỗi ở câu này",
      ],
      paraphrase: [
        "Sai kiểu này thì luyện thêm chỗ nào",
        "Bạn kiếm câu na ná để mình làm tiếp",
        "Có bài nào cùng pattern cho mình thử không",
        "Mình muốn drill lại dạng này thêm vài lượt",
        "Gợi ý lesson nào liên quan đến câu đang xem",
        "Cho mình đường dẫn luyện lại loại câu này",
        "Từ câu này thì nên làm thêm bài nào",
        "Bạn đề xuất practice sát với lỗi hiện tại nhé",
      ],
      noise: [
        "similar q pls",
        "practice dạng này",
        "câu giống z",
        "more drills",
        "luyện same tag",
      ],
    },
    hardNegatives: [
      { input: "Giải thích đáp án đúng của câu hiện tại", expectedIntent: "question.explain_specific" },
      { input: "Dịch câu đang xem sang tiếng Việt cho mình", expectedIntent: "question.translate_context" },
      { input: "Từ khóa trong câu này nghĩa là gì", expectedIntent: "vocabulary.contextual" },
      { input: "Câu này đang kiểm tra mệnh đề quan hệ à", expectedIntent: "grammar.contextual" },
      { input: "Tạo flashcard từ những từ khó của câu này", expectedIntent: "flashcard.create" },
      { input: "Hôm nay roadmap gợi ý bài nào tiếp theo", expectedIntent: "roadmap.next_step" },
      { input: "Cách luyện Part 5 hiệu quả cho người mới", expectedIntent: "toeic_knowledge.general" },
      { input: "Mở trang practice skill trong app", expectedIntent: "app.navigation_support" },
    ],
  },
  {
    focusIntent: "vocabulary.contextual",
    positive: {
      clear: [
        "Từ được gạch chân trong câu này nghĩa là gì",
        "Giải thích cụm từ này theo ngữ cảnh giúp mình",
        "Keyword trong câu hiện tại có nghĩa thế nào",
        "Từ này là danh từ hay động từ trong câu",
        "Cụm này dùng trong TOEIC với nghĩa gì",
        "Cho mình ví dụ khác của từ đang highlight",
        "Paraphrase của từ này trong câu là gì",
        "Từ trong đáp án B có nghĩa tiếng Việt là gì",
        "Phân biệt hai từ trong lựa chọn này giúp mình",
        "Collocation ở câu này nên hiểu thế nào",
      ],
      paraphrase: [
        "Mình vướng vocab của câu đang xem",
        "Bạn giải nghĩa word này ngắn gọn thôi",
        "Cụm được chọn ở đây mang nghĩa gì vậy",
        "Từ đó trong passage có phải nghĩa thông thường không",
        "Có synonym nào cho từ này không",
        "Nghĩa đúng của phrase này trong bài đọc là gì",
        "Từ nào trong câu làm mình hiểu sai",
        "Bạn chỉ các từ quan trọng ở câu hiện tại",
      ],
      noise: [
        "word này meaning?",
        "vocab câu này",
        "phrase nghĩa j",
        "synonym pls",
        "keyword là gì",
      ],
    },
    hardNegatives: [
      { input: "Dịch cả câu hỏi hiện tại sang tiếng Việt", expectedIntent: "question.translate_context" },
      { input: "Giải thích tại sao đáp án A bị loại", expectedIntent: "question.explain_specific" },
      { input: "Chỗ trống này cần loại từ nào", expectedIntent: "grammar.contextual" },
      { input: "Tạo 15 flashcard về chủ đề văn phòng", expectedIntent: "flashcard.create" },
      { input: "Mở trang ôn flashcard cá nhân", expectedIntent: "flashcard.personal" },
      { input: "Cách học từ vựng TOEIC để nhớ lâu", expectedIntent: "toeic_knowledge.general" },
      { input: "Tìm câu luyện thêm cùng dạng từ vựng này", expectedIntent: "question.similar_practice" },
      { input: "Bạn xem năng lực vocabulary của mình yếu không", expectedIntent: "user_progress.ability_map" },
    ],
  },
  {
    focusIntent: "grammar.contextual",
    positive: {
      clear: [
        "Câu này đang kiểm tra điểm ngữ pháp nào",
        "Chỗ trống cần loại từ gì để đúng cấu trúc",
        "Tại sao ở đây phải dùng past participle",
        "Phân tích chủ ngữ vị ngữ trong câu hiện tại",
        "Cấu trúc sau giới từ ở câu này là gì",
        "Vì sao đáp án đúng là trạng từ chứ không phải tính từ",
        "Câu này có dùng mệnh đề quan hệ không",
        "Bạn chỉ dấu hiệu ngữ pháp để chọn đáp án",
        "Tại sao động từ trong câu này chia như vậy",
        "Mẫu câu hiện tại thuộc grammar point nào",
      ],
      paraphrase: [
        "Mình muốn hiểu rule ngữ pháp của câu này",
        "Bạn phân tích cấu trúc câu đang xem giúp",
        "Đoạn này cần tense nào mới hợp",
        "Câu này bẫy loại từ đúng không",
        "Grammar ở đây là phần nào vậy",
        "Sao không dùng V-ing trong chỗ này",
        "Bạn bóc cấu trúc câu này từng phần được không",
        "Ngữ pháp nào quyết định đáp án câu hiện tại",
      ],
      noise: [
        "grammar point?",
        "loại từ gì",
        "tense câu này",
        "why to V",
        "cấu trúc pls",
      ],
    },
    hardNegatives: [
      { input: "Giải thích vì sao đáp án C đúng", expectedIntent: "question.explain_specific" },
      { input: "Dịch đoạn câu hỏi hiện tại sang tiếng Việt", expectedIntent: "question.translate_context" },
      { input: "Từ này trong câu nghĩa là gì", expectedIntent: "vocabulary.contextual" },
      { input: "Mệnh đề quan hệ trong TOEIC học thế nào", expectedIntent: "toeic_knowledge.general" },
      { input: "Cho mình thêm câu luyện cùng cấu trúc này", expectedIntent: "question.similar_practice" },
      { input: "Phân tích bài test gần nhất sai ngữ pháp nhiều không", expectedIntent: "test_attempt.analysis" },
      { input: "Kỹ năng grammar của mình đang yếu cỡ nào", expectedIntent: "user_progress.ability_map" },
      { input: "Tạo flashcard cho các cấu trúc hay gặp", expectedIntent: "flashcard.create" },
    ],
  },
  {
    focusIntent: "toeic_knowledge.general",
    positive: {
      clear: [
        "Part 7 TOEIC nên đọc câu hỏi trước hay passage trước",
        "Cách phân biệt because và because of trong TOEIC",
        "Người mất gốc nên học TOEIC theo thứ tự nào",
        "Part 2 thường có những dạng bẫy nào",
        "Làm sao tăng tốc độ đọc hiểu Reading",
        "TOEIC Listening gồm những phần nào",
        "Collocation quan trọng trong môi trường công sở là gì",
        "Chiến lược làm Part 5 khi thiếu thời gian",
        "Nên luyện đề TOEIC bao nhiêu lần mỗi tuần",
        "Cách ôn lại nhóm từ TOEIC sau mỗi đề cho nhớ chắc",
      ],
      paraphrase: [
        "Mình mới học TOEIC thì nên bắt đầu từ đâu",
        "Bạn giải thích format bài thi TOEIC cho mình",
        "Có mẹo nào nghe Part 3 đỡ mất ý không",
        "Reading 400 lên 500 nên tập trung gì",
        "Ngữ pháp TOEIC phần nào hay ra nhất",
        "Học từ vựng theo chủ đề hay theo đề tốt hơn",
        "Cách tránh bẫy trong câu điền từ là gì",
        "Muốn lên 650 thì lịch học nên chia sao",
      ],
      noise: [
        "toeic tips pls",
        "part 5 mẹo",
        "reading strategy?",
        "grammar toeic học gì",
        "600 target how",
      ],
    },
    hardNegatives: [
      { input: "Câu đang xem vì sao đáp án B đúng", expectedIntent: "question.explain_specific" },
      { input: "Dịch passage hiện tại sang tiếng Việt", expectedIntent: "question.translate_context" },
      { input: "Cụm được tô sáng trong passage này mang nghĩa gì", expectedIntent: "vocabulary.contextual" },
      { input: "Câu hiện tại cần dùng thì nào", expectedIntent: "grammar.contextual" },
      { input: "Tiến độ học cá nhân của mình tháng này sao rồi", expectedIntent: "user_progress.summary" },
      { input: "Bài test vừa rồi mình sai dạng nào nhiều nhất", expectedIntent: "test_attempt.analysis" },
      { input: "Mở roadmap cá nhân giúp mình", expectedIntent: "roadmap.guidance" },
      { input: "Tạo flashcard TOEIC chủ đề invoice", expectedIntent: "flashcard.create" },
    ],
  },
  {
    focusIntent: "roadmap.guidance",
    positive: {
      clear: [
        "Mở giúp mình trang lộ trình học",
        "Cho mình vào màn hình roadmap cá nhân",
        "Đi tới mục kế hoạch học trong app",
        "Bạn chuyển sang tab lộ trình giúp mình",
        "Mình muốn xem trang roadmap bây giờ",
        "Nút roadmap nằm đâu, mở luôn giúp mình",
        "Dẫn mình tới phần kế hoạch học TOEIC",
        "Bật màn hình lộ trình học hiện tại",
        "Cho mình xem trang plan học trong hệ thống",
        "Mở khu vực roadmap trên web này",
      ],
      paraphrase: [
        "Mình lạc rồi, đưa mình về lộ trình",
        "Có thể chuyển qua roadmap không",
        "Đi đến trang kế hoạch học giùm mình",
        "Mình muốn nhìn giao diện roadmap trước",
        "Cho mình mở nơi quản lý lộ trình",
        "Bạn điều hướng tới mục roadmap nhé",
        "Mở chỗ hiển thị đường học của mình",
        "Bấm giúp mình vào phần lộ trình",
      ],
      noise: [
        "open roadmap pls",
        "vào lộ trình",
        "roadmap tab",
        "show plan page",
        "mở roadmap now",
      ],
    },
    hardNegatives: [
      { input: "Roadmap hiện tại của mình đang tới bước nào", expectedIntent: "roadmap.summary" },
      { input: "Hôm nay roadmap đề xuất học gì tiếp", expectedIntent: "roadmap.next_step" },
      { input: "Tại sao hệ thống xếp bài Part 7 này", expectedIntent: "roadmap.explain_recommendation" },
      { input: "Mình muốn giảm khối lượng học trong lộ trình", expectedIntent: "roadmap.adjust" },
      { input: "Mở trang flashcard cá nhân", expectedIntent: "flashcard.personal" },
      { input: "Chỉ mình màn hình làm test nằm ở đâu", expectedIntent: "app.navigation_support" },
      { input: "Báo cáo chung việc học của mình tuần này", expectedIntent: "user_progress.summary" },
      { input: "Nên tự tạo roadmap TOEIC thế nào", expectedIntent: "toeic_knowledge.general" },
    ],
  },
  {
    focusIntent: "roadmap.summary",
    positive: {
      clear: [
        "Lộ trình của mình hiện đang ở giai đoạn nào",
        "Roadmap cá nhân còn bao nhiêu bước nữa",
        "Tổng quan kế hoạch học của mình hiện tại",
        "Mình đã hoàn thành phần nào trong roadmap",
        "Cycle hiện tại của lộ trình tập trung vào gì",
        "Cho mình xem trạng thái roadmap đang chạy",
        "Kế hoạch học hiện giờ tiến triển ra sao",
        "Roadmap của mình đang tới đâu rồi",
        "Mình còn những chặng nào trong lộ trình",
        "Tóm tắt nhanh lộ trình học hiện tại",
      ],
      paraphrase: [
        "Nhìn roadmap thì mình đang ở đoạn nào",
        "Bạn recap đường học của mình cho mình",
        "Lộ trình này đã đi được bao xa",
        "Mình muốn biết status kế hoạch học",
        "Roadmap còn dài không vậy",
        "Stage hiện tại là gì trong plan",
        "Kế hoạch học đang vận hành thế nào",
        "Bạn nói ngắn gọn tình trạng roadmap nhé",
      ],
      noise: [
        "roadmap status",
        "lộ trình tới đâu",
        "stage nào rồi",
        "plan progress?",
        "cycle hiện tại",
      ],
    },
    hardNegatives: [
      { input: "Mở trang roadmap cho mình xem", expectedIntent: "roadmap.guidance" },
      { input: "Tiếp theo trong roadmap mình phải học bài nào", expectedIntent: "roadmap.next_step" },
      { input: "Vì sao roadmap chọn kỹ năng Listening hôm nay", expectedIntent: "roadmap.explain_recommendation" },
      { input: "Cập nhật mục tiêu điểm trong lộ trình", expectedIntent: "roadmap.adjust" },
      { input: "Tổng tiến độ học TOEIC của mình thế nào", expectedIntent: "user_progress.summary" },
      { input: "Mình yếu Part nào theo bản đồ năng lực", expectedIntent: "user_progress.ability_map" },
      { input: "Chỗ xem lộ trình nằm mục nào trong app", expectedIntent: "roadmap.guidance" },
      { input: "Cách tự lập lộ trình TOEIC 3 tháng", expectedIntent: "toeic_knowledge.general" },
    ],
  },
  {
    focusIntent: "roadmap.next_step",
    positive: {
      clear: [
        "Bài tiếp theo trong roadmap của mình là gì",
        "Hôm nay lộ trình muốn mình học phần nào",
        "Sau bước hiện tại mình cần làm gì",
        "Roadmap đề xuất session nào kế tiếp",
        "Mình nên bấm học bài nào tiếp theo",
        "Cho mình biết nhiệm vụ kế tiếp trong plan",
        "Stage này còn hoạt động nào phải làm ngay",
        "Gợi ý next lesson theo roadmap cá nhân",
        "Mình học gì ngay bây giờ theo lộ trình",
        "Bước học ưu tiên tiếp theo là bài nào",
      ],
      paraphrase: [
        "Giờ mình nên làm gì tiếp",
        "Đến lượt học phần nào rồi",
        "Bạn chọn giúp hoạt động tiếp theo trong roadmap",
        "Hôm nay mở bài nào là hợp lý nhất",
        "Plan đang giao task gì kế tiếp",
        "Mình cần follow bước nào sau đây",
        "Roadmap bảo mình làm gì trước tiên",
        "Cho mình next action cụ thể đi",
      ],
      noise: [
        "next step?",
        "học gì next",
        "roadmap task now",
        "lesson tiếp",
        "today plan gì",
      ],
    },
    hardNegatives: [
      { input: "Roadmap hiện tại của mình đang ở stage nào", expectedIntent: "roadmap.summary" },
      { input: "Mở giao diện roadmap giúp mình", expectedIntent: "roadmap.guidance" },
      { input: "Vì lý do gì lesson này lại đứng trước các bài khác", expectedIntent: "roadmap.explain_recommendation" },
      { input: "Đổi lộ trình sang học ít hơn mỗi ngày", expectedIntent: "roadmap.adjust" },
      { input: "Cho mình xem trạng thái học tập tổng thể", expectedIntent: "user_progress.summary" },
      { input: "Tạo flashcard để học hôm nay", expectedIntent: "flashcard.create" },
      { input: "Cách chọn bài học TOEIC mỗi ngày", expectedIntent: "toeic_knowledge.general" },
      { input: "Mở trang kế hoạch hôm nay trong app", expectedIntent: "app.navigation_support" },
    ],
  },
  {
    focusIntent: "roadmap.explain_recommendation",
    positive: {
      clear: [
        "Vì sao roadmap lại đề xuất bài này cho mình",
        "Giải thích lý do hệ thống chọn Part 5 hôm nay",
        "Tại sao stage hiện tại tập trung vào Reading",
        "Bài học này được xếp ưu tiên dựa trên gì",
        "Cho mình biết logic gợi ý trong lộ trình",
        "Vì sao kế hoạch bắt mình luyện kỹ năng này trước",
        "Roadmap dựa vào dữ liệu nào để chọn hoạt động này",
        "Tại sao cycle này lại ưu tiên lỗi ngữ pháp",
        "Giải thích nguyên nhân bài tiếp theo là bài này",
        "Lý do recommendation hôm nay là gì",
      ],
      paraphrase: [
        "Mình muốn hiểu vì sao plan chọn như vậy",
        "Bạn nói rõ cơ sở đề xuất bài học này nhé",
        "Tại sao không học phần khác mà học phần này",
        "Roadmap có lý do gì khi đẩy task này lên đầu",
        "Hệ thống đang suy luận gì khi gợi ý lesson này",
        "Giải thích recommendation của roadmap cho dễ hiểu",
        "Bài này liên quan gì đến điểm yếu của mình",
        "Vì sao mục tiêu hiện tại dẫn tới hoạt động này",
      ],
      noise: [
        "why this lesson",
        "reason roadmap?",
        "vì sao bài này",
        "recommendation why",
        "plan chọn sao",
      ],
    },
    hardNegatives: [
      { input: "Hôm nay mình nên học bài nào tiếp theo", expectedIntent: "roadmap.next_step" },
      { input: "Roadmap hiện tại đang tới đâu", expectedIntent: "roadmap.summary" },
      { input: "Mở trang lộ trình cho mình", expectedIntent: "roadmap.guidance" },
      { input: "Điều chỉnh roadmap để học nhẹ hơn", expectedIntent: "roadmap.adjust" },
      { input: "Phân tích bài test vừa rồi vì sao điểm thấp", expectedIntent: "test_attempt.analysis" },
      { input: "Mình yếu kỹ năng nào nên roadmap mới chọn bài này", expectedIntent: "user_progress.ability_map" },
      { input: "Cách chọn tài liệu TOEIC phù hợp trình độ", expectedIntent: "toeic_knowledge.general" },
      { input: "Chỉ mình nút xem lý do đề xuất nằm đâu", expectedIntent: "app.navigation_support" },
    ],
  },
  {
    focusIntent: "roadmap.adjust",
    positive: {
      clear: [
        "Điều chỉnh lộ trình để mỗi ngày học ít hơn",
        "Mình muốn đổi mục tiêu điểm trong roadmap",
        "Cập nhật kế hoạch học sang buổi tối",
        "Tăng thời lượng luyện Listening trong lộ trình",
        "Giảm số bài phải làm mỗi ngày giúp mình",
        "Thay đổi roadmap vì mình bận tuần này",
        "Chỉnh lại plan học cho phù hợp lịch mới",
        "Mình muốn ưu tiên Reading trong kế hoạch",
        "Cập nhật lộ trình theo target 750",
        "Đổi nhịp học trong roadmap cá nhân",
      ],
      paraphrase: [
        "Plan này hơi nặng, sửa lại được không",
        "Mình cần học chậm hơn trong vài ngày",
        "Bạn cập nhật roadmap theo thời gian rảnh mới",
        "Cho mình đổi chiến lược học trong lộ trình",
        "Mình muốn giảm áp lực bài tập hằng ngày",
        "Roadmap hiện tại không hợp lịch của mình",
        "Sắp xếp lại kế hoạch học giúp mình",
        "Điều chỉnh target và kế hoạch cho thực tế hơn",
      ],
      noise: [
        "adjust roadmap",
        "đổi plan",
        "giảm task nha",
        "update target",
        "roadmap nhẹ hơn",
      ],
    },
    hardNegatives: [
      { input: "Roadmap của mình hiện tại đang ở bước nào", expectedIntent: "roadmap.summary" },
      { input: "Bước tiếp theo mình phải học là gì", expectedIntent: "roadmap.next_step" },
      { input: "Mở màn hình roadmap để mình xem", expectedIntent: "roadmap.guidance" },
      { input: "Vì sao roadmap ưu tiên Part 6", expectedIntent: "roadmap.explain_recommendation" },
      { input: "Tổng quan tiến độ học cá nhân của mình", expectedIntent: "user_progress.summary" },
      { input: "Cách tự điều chỉnh lịch học TOEIC", expectedIntent: "toeic_knowledge.general" },
      { input: "Chỉ chỗ chỉnh mục tiêu học trong app", expectedIntent: "app.navigation_support" },
      { input: "Tạo flashcard theo kế hoạch hôm nay", expectedIntent: "flashcard.create" },
    ],
  },
  {
    focusIntent: "flashcard.create",
    positive: {
      clear: [
        "Tạo cho mình 12 flashcard chủ đề hợp đồng",
        "Sinh bộ từ vựng TOEIC về tuyển dụng",
        "Lưu các từ khó trong câu này thành flashcard",
        "Tạo danh sách 20 từ về airport để ôn",
        "Làm một bộ flashcard về email công việc",
        "Thêm từ đang chọn vào bộ thẻ của mình",
        "Tạo nhanh flashcard từ lỗi vocabulary vừa gặp",
        "Sinh 15 thẻ từ vựng chủ đề customer service",
        "Lập bộ từ mới về invoice cho mình học",
        "Tạo flashcard từ các từ mình sai trong bài này",
      ],
      paraphrase: [
        "Mình muốn có bộ thẻ mới để học từ này",
        "Bạn gom vocab câu này thành flashcard nhé",
        "Tạo giúp vài thẻ ôn từ vựng văn phòng",
        "Lưu phrase này để mình ôn lại sau",
        "Cho mình một deck mới về meeting",
        "Biến các từ khó ở đây thành thẻ học",
        "Build flashcard set cho topic travel",
        "Mình cần tạo bộ từ mới từ bài vừa làm",
      ],
      noise: [
        "make flashcards",
        "tạo 10 cards",
        "add word deck",
        "flashcard invoice pls",
        "save vocab này",
      ],
    },
    hardNegatives: [
      { input: "Mở trang flashcard cá nhân để mình ôn", expectedIntent: "flashcard.personal" },
      { input: "Từ này trong câu hiện tại nghĩa là gì", expectedIntent: "vocabulary.contextual" },
      { input: "Cách học từ vựng TOEIC bằng flashcard hiệu quả", expectedIntent: "toeic_knowledge.general" },
      { input: "Chỉ mình nút tạo flashcard nằm ở đâu", expectedIntent: "app.navigation_support" },
      { input: "Cho mình câu luyện tương tự để nhớ từ này", expectedIntent: "question.similar_practice" },
      { input: "Tổng quan mình đã học bao nhiêu từ", expectedIntent: "user_progress.summary" },
      { input: "Dịch cụm từ trong câu này sang tiếng Việt", expectedIntent: "question.translate_context" },
      { input: "Roadmap hôm nay yêu cầu ôn flashcard nào", expectedIntent: "roadmap.next_step" },
    ],
  },
  {
    focusIntent: "flashcard.personal",
    positive: {
      clear: [
        "Mở trang flashcard cá nhân cho mình",
        "Cho mình vào phần ôn thẻ từ vựng",
        "Đi tới màn hình flashcard đang học",
        "Mình muốn xem bộ flashcard của mình",
        "Chuyển sang tab ôn từ bằng thẻ",
        "Mở khu vực quản lý deck từ vựng",
        "Dẫn mình tới trang flashcard trên app",
        "Cho mình xem các bộ thẻ đã lưu",
        "Mở phần review flashcard hôm nay",
        "Bật màn hình học từ bằng flashcard",
      ],
      paraphrase: [
        "Mình muốn ôn lại thẻ từ ngay bây giờ",
        "Đưa mình tới chỗ học flashcard",
        "Có thể mở deck từ vựng của mình không",
        "Mình cần vào trang các thẻ đã lưu",
        "Chuyển qua khu ôn vocab bằng card nhé",
        "Mở nơi mình xem flashcard cá nhân",
        "Cho mình vào mục học từ đã tạo",
        "Đi đến trang ôn từ bằng thẻ giúp mình",
      ],
      noise: [
        "open flashcards",
        "flashcard của mình đâu",
        "deck của tôi",
        "review cards",
        "flashcard tab",
      ],
    },
    hardNegatives: [
      { input: "Tạo bộ flashcard mới về chủ đề workplace", expectedIntent: "flashcard.create" },
      { input: "Từ được chọn trong câu này nghĩa là gì", expectedIntent: "vocabulary.contextual" },
      { input: "Mở trang roadmap cá nhân", expectedIntent: "roadmap.guidance" },
      { input: "Chỉ mình cách vào phần review câu sai", expectedIntent: "app.navigation_support" },
      { input: "Cách ôn flashcard sao cho nhớ lâu", expectedIntent: "toeic_knowledge.general" },
      { input: "Hôm nay roadmap muốn mình ôn gì", expectedIntent: "roadmap.next_step" },
      { input: "Mình đã học được bao nhiêu từ vựng rồi", expectedIntent: "user_progress.summary" },
      { input: "Lưu từ hiện tại vào flashcard", expectedIntent: "flashcard.create" },
    ],
  },
  {
    focusIntent: "app.navigation_support",
    positive: {
      clear: [
        "Làm bài test mới ở mục nào trong app",
        "Chỉ mình chỗ xem lại câu sai",
        "Nút nộp bài test nằm ở đâu",
        "Mình muốn mở màn hình luyện kỹ năng",
        "Trang lịch sử làm bài nằm chỗ nào",
        "Làm sao xem đáp án đúng sau khi nộp",
        "Hướng dẫn mình vào phần review mistake",
        "Mở trang kết quả bài làm giúp mình",
        "Chỉ đường tới màn hình practice skill",
        "Mình không thấy tab dashboard ở đâu",
      ],
      paraphrase: [
        "Trong web này muốn luyện đề thì bấm đâu",
        "Bạn dẫn mình tới nơi xem bài đã làm",
        "Mình bị lạc giao diện, chỉ chỗ làm test",
        "Muốn xem chi tiết kết quả thì vào đâu",
        "Có mục nào để review đáp án sai không",
        "Chỗ bắt đầu bài học mới nằm tab nào",
        "Mình cần tìm lại màn hình thống kê",
        "Hướng dẫn thao tác mở phần luyện tập",
      ],
      noise: [
        "test ở đâu",
        "open result page",
        "review sai đâu",
        "practice tab?",
        "dashboard where",
      ],
    },
    hardNegatives: [
      { input: "Mở roadmap cá nhân cho mình", expectedIntent: "roadmap.guidance" },
      { input: "Mở trang flashcard của mình", expectedIntent: "flashcard.personal" },
      { input: "Tổng quan tiến độ học của mình", expectedIntent: "user_progress.summary" },
      { input: "Phân tích bài test mới nộp", expectedIntent: "test_attempt.analysis" },
      { input: "Câu này vì sao đáp án D đúng", expectedIntent: "question.explain_specific" },
      { input: "TOEIC Part 1 cần chú ý gì", expectedIntent: "toeic_knowledge.general" },
      { input: "Tạo bộ từ vựng chủ đề conference", expectedIntent: "flashcard.create" },
      { input: "Thời tiết ngày mai ở Hà Nội thế nào", expectedIntent: "out_of_project.general" },
    ],
  },
];

function slug(value: string) {
  return value.replace(/[^a-z0-9]+/gi, "_").replace(/^_+|_+$/g, "").toLowerCase();
}

function buildPositiveCases(
  focusIntent: ChatIntent,
  category: Exclude<IntentDifferentiationCategory, "hardNegative">,
  inputs: string[]
): IntentDifferentiationCase[] {
  return inputs.map((input, index) => ({
    id: `${slug(focusIntent)}_${category}_${index + 1}`,
    focusIntent,
    category,
    input,
    expectedIntent: focusIntent,
  }));
}

function buildHardNegativeCases(
  focusIntent: ChatIntent,
  inputs: RawHardNegativeCase[]
): IntentDifferentiationCase[] {
  return inputs.map((item, index) => ({
    id: `${slug(focusIntent)}_hard_negative_${index + 1}`,
    focusIntent,
    category: "hardNegative",
    input: item.input,
    expectedIntent: item.expectedIntent,
    forbiddenIntents: [focusIntent],
    notes: item.notes,
  }));
}

export const CHAT_INTENT_DIFFERENTIATION_CASES: IntentDifferentiationCase[] =
  CHAT_INTENT_DIFFERENTIATION_GROUPS.flatMap((group) => [
    ...buildPositiveCases(group.focusIntent, "clear", group.positive.clear),
    ...buildPositiveCases(group.focusIntent, "paraphrase", group.positive.paraphrase),
    ...buildPositiveCases(group.focusIntent, "noise", group.positive.noise),
    ...buildHardNegativeCases(group.focusIntent, group.hardNegatives),
  ]);
